Asimov - Agentbased Passenger & Train Delay Simulation: com.github.aptd.simulation.elements.common.CUnit Class Reference
com.github.aptd.simulation.elements.common.CUnit Class Reference
simulation units
Public Member Functions
final double accelerationtospeed (final double p_acceleration)
returns the speed change in one timestep
final double cellsize ()
returns the cell size
final double celltokilometer (final int p_cells)
returns cell number to distance in kilometer
final double celltometer (final int p_cells)
returns cell number to distance in meter
final int speedofdistance (final double p_distance)
returns the speed for traveling the given distance in one timestep
final int speedtocell (final int p_speed)
returns the speed in cell positions at one timestep
final double speedtodistance (final int p_speed)
returns the distance in meter which can moved in one timestep
final double time ()
returns the timestep in seconds
final double time (final int p_step)
returns the time in seconds for n steps
final double timeinminutes (final int p_step)
returns the time in minutes for n steps
Static Public Attributes
static final CUnit INSTANCE = new CUnit()
singletone instance
Private Member Functions
CUnit ()
private ctor
Private Attributes
final double m_cellsize = CConfiguration.INSTANCE.<Number>getOrDefault(1.5, "units", "cellsize_in_meter").doubleValue()
cell size in meter
final int m_celltimestep = (int) Math.floor(m_distancetimestep / m_cellsize)
number of cells which can be moved at one timestep
final double m_distancetimestep = KMINMS * m_timestep
meter which can be moved at one timestep
final double m_timestep = CConfiguration.INSTANCE.<Number>getOrDefault(0.5, "units", "time_in_minutes").doubleValue()
timestep in seconds
Static Private Attributes
static final double KMINMS = 1000.0 / 3600.0
constant value to scale km/h in m/s
static final double MSINKMH = 1 / KMINMS
constant value to scale m/s in km/h
Detailed Description
Todo:
refactor
Definition at line 33 of file elements/common/CUnit.java.
Constructor & Destructor Documentation
CUnit()
com.github.aptd.simulation.elements.common.CUnit.CUnit () private
Definition at line 69 of file elements/common/CUnit.java.
Member Function Documentation
accelerationtospeed()
final double com.github.aptd.simulation.elements.common.CUnit.accelerationtospeed (final double p_acceleration)
Parameters
p_acceleration acceleration or deceleration in m/sec^2
Returns
speed change in km/h
Definition at line 79 of file elements/common/CUnit.java.
References com.github.aptd.simulation.elements.common.CUnit.m_timestep.
cellsize()
final double com.github.aptd.simulation.elements.common.CUnit.cellsize ()
Returns
cell size in meter
Definition at line 89 of file elements/common/CUnit.java.
References com.github.aptd.simulation.elements.common.CUnit.m_cellsize.
celltokilometer()
final double com.github.aptd.simulation.elements.common.CUnit.celltokilometer (final int p_cells)
Parameters
p_cells cell number
Returns
kilometer value
Definition at line 111 of file elements/common/CUnit.java.
References com.github.aptd.simulation.elements.common.CUnit.celltometer().
celltometer()
final double com.github.aptd.simulation.elements.common.CUnit.celltometer (final int p_cells)
Parameters
p_cells cell number
Returns
meter value
Definition at line 100 of file elements/common/CUnit.java.
References com.github.aptd.simulation.elements.common.CUnit.m_cellsize.
Referenced by com.github.aptd.simulation.elements.common.CUnit.celltokilometer().
speedofdistance()
final int com.github.aptd.simulation.elements.common.CUnit.speedofdistance (final double p_distance)
Parameters
p_distance distance in meter
Returns
speed in km/h
Definition at line 122 of file elements/common/CUnit.java.
References com.github.aptd.simulation.elements.common.CUnit.MSINKMH.
speedtocell()
final int com.github.aptd.simulation.elements.common.CUnit.speedtocell (final int p_speed)
Parameters
p_speed speed in km/h
Returns
amount of cells / timestep
Definition at line 133 of file elements/common/CUnit.java.
References com.github.aptd.simulation.elements.common.CUnit.m_celltimestep.
speedtodistance()
final double com.github.aptd.simulation.elements.common.CUnit.speedtodistance (final int p_speed)
Parameters
p_speed speed in km/h
Returns
meter
Definition at line 145 of file elements/common/CUnit.java.
References com.github.aptd.simulation.elements.common.CUnit.m_timestep.
time() [1/2]
final double com.github.aptd.simulation.elements.common.CUnit.time ()
Returns
timestep
Definition at line 155 of file elements/common/CUnit.java.
References com.github.aptd.simulation.elements.common.CUnit.m_timestep.
Referenced by com.github.aptd.simulation.elements.common.CUnit.timeinminutes().
time() [2/2]
final double com.github.aptd.simulation.elements.common.CUnit.time (final int p_step)
Parameters
p_step step number
Returns
time in seconds
Definition at line 166 of file elements/common/CUnit.java.
timeinminutes()
final double com.github.aptd.simulation.elements.common.CUnit.timeinminutes (final int p_step)
Parameters
p_step step number
Returns
time in minutes
Definition at line 177 of file elements/common/CUnit.java.
References com.github.aptd.simulation.elements.common.CUnit.time().
Member Data Documentation
INSTANCE
final CUnit com.github.aptd.simulation.elements.common.CUnit.INSTANCE = new CUnit() static
Definition at line 38 of file elements/common/CUnit.java.
KMINMS
final double com.github.aptd.simulation.elements.common.CUnit.KMINMS = 1000.0 / 3600.0 static private
Definition at line 42 of file elements/common/CUnit.java.
m_cellsize
final double com.github.aptd.simulation.elements.common.CUnit.m_cellsize = CConfiguration.INSTANCE.<Number>getOrDefault(1.5, "units", "cellsize_in_meter").doubleValue() private
Definition at line 50 of file elements/common/CUnit.java.
Referenced by com.github.aptd.simulation.elements.common.CUnit.cellsize(), and com.github.aptd.simulation.elements.common.CUnit.celltometer().
m_celltimestep
final int com.github.aptd.simulation.elements.common.CUnit.m_celltimestep = (int) Math.floor(m_distancetimestep / m_cellsize) private
Definition at line 62 of file elements/common/CUnit.java.
Referenced by com.github.aptd.simulation.elements.common.CUnit.speedtocell().
m_distancetimestep
final double com.github.aptd.simulation.elements.common.CUnit.m_distancetimestep = KMINMS * m_timestep private
Definition at line 58 of file elements/common/CUnit.java.
m_timestep
final double com.github.aptd.simulation.elements.common.CUnit.m_timestep = CConfiguration.INSTANCE.<Number>getOrDefault(0.5, "units", "time_in_minutes").doubleValue() private
Definition at line 54 of file elements/common/CUnit.java.
Referenced by com.github.aptd.simulation.elements.common.CUnit.accelerationtospeed(), com.github.aptd.simulation.elements.common.CUnit.speedtodistance(), and com.github.aptd.simulation.elements.common.CUnit.time().
MSINKMH
final double com.github.aptd.simulation.elements.common.CUnit.MSINKMH = 1 / KMINMS static private
Definition at line 46 of file elements/common/CUnit.java.
Referenced by com.github.aptd.simulation.elements.common.CUnit.speedofdistance().