Asimov - Agentbased Passenger & Train Delay Simulation: com.github.aptd.simulation.elements.passenger.CPassengerSource Class Reference
com.github.aptd.simulation.elements.passenger.CPassengerSource Class Reference
passenger source: an agent creating Passenger agents according to statistical distributions
Classes
class CGenerator
generator
Protected Member Functions
synchronized Instant determinenextstatechange ()
Stream< ILiteral > individualliteral (final Stream< IElement<?>> p_object)
define object literal addons
boolean updatecontinuous (final Duration p_elapsed)
synchronized boolean updatestate ()
void writeState (final JsonGenerator p_generator) throws IOException
Protected Member Functions inherited from com.github.aptd.simulation.elements.IStatefulElement< N extends IElement<?>
IStatefulElement (final IAgentConfiguration< N > p_configuration, final String p_functor, final String p_id, final ITime p_time)
ctor
final synchronized void continuousupdate ()
abstract Instant determinenextstatechange ()
calculates the time instant at which the next (internal) state change happens unless the agent is interrupted by input.
final void flushOutput ()
final void output (final IMessage p_message)
final synchronized void transition ()
abstract boolean updatecontinuous (final Duration p_elapsed)
apart from updatestate(), this is the only place where continuous state shall be changed; discrete state must not be changed here
abstract boolean updatestate ()
this is the ONLY place where the discrete state shall be touched.
abstract void writeState (final JsonGenerator p_generator) throws IOException
every implementing class must provide this method that serializes the current state of the object into the provided JsonGenerator (fasterxml-core)
Protected Member Functions inherited from com.github.aptd.simulation.elements.IBaseElement< N >
IBaseElement (final IAgentConfiguration< N > p_configuration, final String p_functor, final String p_id, final ITime p_time)
ctor
abstract Stream< ILiteral > individualliteral (final Stream< IElement<?>> p_object)
define object literal addons
Private Member Functions
CPassengerSource (final IAgentConfiguration< IPassengerSource<?>> p_configuration, final String p_id, final ITime p_time, final RealDistribution p_distribution, final long p_startmillis, final int p_passengers, final IGenerator<?> p_generator, final IExperiment p_experiment, final IStation<?> p_station, final RealDistribution p_distpassengerspeedatstation)
ctor
synchronized void generatepassenger ()
Stream< CPassenger.CItineraryEntry > itinerary ()
Private Attributes
RealDistribution m_distpassengerspeedatstation
RealDistribution m_distribution
IExperiment m_experiment
IElement.IGenerator<?> m_generator
int m_passengers
int m_passengersgenerated
long m_startmillis
IStation<?> m_station
Static Private Attributes
static final String FUNCTOR = "passengersource"
literal functor
static final long serialVersionUID = 5248638076491134344L
serial id
Additional Inherited Members
Public Member Functions inherited from com.github.aptd.simulation.elements.IStatefulElement< N extends IElement<?>
final Instant nextstatechange ()
synchronized Stream< IMessage > output ()
Public Member Functions inherited from com.github.aptd.simulation.elements.IBaseElement< N >
N call () throws Exception
final IElement< N > environment (final IEnvironment< N, ?> p_environment)
final boolean equals (final Object p_object)
final int hashCode ()
final String id ()
boolean imminent ()
whether the element has a scheduled activation at the current time
N input (final IMessage p_message)
store an incoming message to be processed
final Stream< ILiteral > literal (final IElement<?>... p_object)
final Stream< ILiteral > literal (final Stream< IElement<?>> p_object)
Instant nextactivation ()
Stream< IMessage > output ()
get outgoing messages.
String toString ()
Static Public Member Functions inherited from com.github.aptd.simulation.elements.IStatefulElement< N extends IElement<?>
static final String getDefaultAsl (final String p_name)
generates a default asl script string calling "state/transition" upon "!activate", and greeting upon initialisation
Protected Attributes inherited from com.github.aptd.simulation.elements.IStatefulElement< N extends IElement<?>
Instant m_lastcontinuousupdate
Instant m_laststatechange
Instant m_nextstatechange
Protected Attributes inherited from com.github.aptd.simulation.elements.IBaseElement< N >
final String m_id
agent name
final ListMultimap< EMessageType, IMessage > m_input
set of inputs to be processed
Instant m_nextactivation
simulated time at which the agent will become active again on its own
final ITime m_time
reference to time
Detailed Description
Definition at line 54 of file CPassengerSource.java.
Constructor & Destructor Documentation
CPassengerSource()
com.github.aptd.simulation.elements.passenger.CPassengerSource.CPassengerSource (final IAgentConfiguration< IPassengerSource<?>> p_configuration, final String p_id, final ITime p_time, final RealDistribution p_distribution, final long p_startmillis, final int p_passengers, final IGenerator<?> p_generator, final IExperiment p_experiment, final IStation<?> p_station, final RealDistribution p_distpassengerspeedatstation) private
Parameters
p_configuration agent configuration
p_id ...
p_time time reference
p_distribution distribution according to which passengers are generated over time (in milliseconds)
p_startmillis the start timestamp, in milliseconds (to anchor the distribution)
p_passengers how many passengers will be generated in total
p_generator agent generator of passenger agent class to be generated
p_experiment reference to the experiment instance into which the agents will be added
p_station station agent at which the passengers will begin their lives
Definition at line 90 of file CPassengerSource.java.
References com.github.aptd.simulation.elements.passenger.CPassengerSource.determinenextstatechange(), com.github.aptd.simulation.elements.passenger.CPassengerSource.m_generator, and com.github.aptd.simulation.elements.IBaseElement< N >.m_nextactivation.
Referenced by com.github.aptd.simulation.elements.passenger.CPassengerSource.CGenerator.generate().
Member Function Documentation
determinenextstatechange()
synchronized Instant com.github.aptd.simulation.elements.passenger.CPassengerSource.determinenextstatechange () protected
Definition at line 127 of file CPassengerSource.java.
Referenced by com.github.aptd.simulation.elements.passenger.CPassengerSource.CPassengerSource().
generatepassenger()
synchronized void com.github.aptd.simulation.elements.passenger.CPassengerSource.generatepassenger () private
Definition at line 153 of file CPassengerSource.java.
References com.github.aptd.simulation.core.experiment.IExperiment.addAgent(), com.github.aptd.simulation.elements.IElement< T extends IAgent<?>.id(), com.github.aptd.simulation.elements.passenger.CPassengerSource.itinerary(), com.github.aptd.simulation.elements.passenger.CPassengerSource.m_generator, and com.github.aptd.simulation.elements.passenger.CPassengerSource.m_passengersgenerated.
Referenced by com.github.aptd.simulation.elements.passenger.CPassengerSource.updatestate().
individualliteral()
Stream<ILiteral> com.github.aptd.simulation.elements.passenger.CPassengerSource.individualliteral (final Stream< IElement<?>> p_object) protected
Parameters
p_object calling objects
Returns
literal stream
Definition at line 122 of file CPassengerSource.java.
itinerary()
Stream<CPassenger.CItineraryEntry> com.github.aptd.simulation.elements.passenger.CPassengerSource.itinerary () private
Definition at line 162 of file CPassengerSource.java.
Referenced by com.github.aptd.simulation.elements.passenger.CPassengerSource.generatepassenger().
updatecontinuous()
boolean com.github.aptd.simulation.elements.passenger.CPassengerSource.updatecontinuous (final Duration p_elapsed) protected
Definition at line 142 of file CPassengerSource.java.
updatestate()
synchronized boolean com.github.aptd.simulation.elements.passenger.CPassengerSource.updatestate () protected
Definition at line 134 of file CPassengerSource.java.
References com.github.aptd.simulation.core.time.ITime.current(), com.github.aptd.simulation.elements.passenger.CPassengerSource.generatepassenger(), and com.github.aptd.simulation.elements.IBaseElement< N >.m_time.
writeState()
void com.github.aptd.simulation.elements.passenger.CPassengerSource.writeState (final JsonGenerator p_generator) throws IOException protected
Definition at line 148 of file CPassengerSource.java.
Member Data Documentation
FUNCTOR
final String com.github.aptd.simulation.elements.passenger.CPassengerSource.FUNCTOR = "passengersource" static private
Definition at line 65 of file CPassengerSource.java.
m_distpassengerspeedatstation
RealDistribution com.github.aptd.simulation.elements.passenger.CPassengerSource.m_distpassengerspeedatstation private
Definition at line 76 of file CPassengerSource.java.
m_distribution
RealDistribution com.github.aptd.simulation.elements.passenger.CPassengerSource.m_distribution private
Definition at line 71 of file CPassengerSource.java.
m_experiment
IExperiment com.github.aptd.simulation.elements.passenger.CPassengerSource.m_experiment private
Definition at line 68 of file CPassengerSource.java.
m_generator
IElement.IGenerator<?> com.github.aptd.simulation.elements.passenger.CPassengerSource.m_generator private
Definition at line 67 of file CPassengerSource.java.
Referenced by com.github.aptd.simulation.elements.passenger.CPassengerSource.CPassengerSource(), and com.github.aptd.simulation.elements.passenger.CPassengerSource.generatepassenger().
m_passengers
int com.github.aptd.simulation.elements.passenger.CPassengerSource.m_passengers private
Definition at line 73 of file CPassengerSource.java.
m_passengersgenerated
int com.github.aptd.simulation.elements.passenger.CPassengerSource.m_passengersgenerated private
Definition at line 74 of file CPassengerSource.java.
Referenced by com.github.aptd.simulation.elements.passenger.CPassengerSource.generatepassenger().
m_startmillis
long com.github.aptd.simulation.elements.passenger.CPassengerSource.m_startmillis private
Definition at line 72 of file CPassengerSource.java.
m_station
IStation<?> com.github.aptd.simulation.elements.passenger.CPassengerSource.m_station private
Definition at line 69 of file CPassengerSource.java.
serialVersionUID
final long com.github.aptd.simulation.elements.passenger.CPassengerSource.serialVersionUID = 5248638076491134344L static private
Definition at line 61 of file CPassengerSource.java.