Asimov - Agentbased Passenger & Train Delay Simulation: com.github.aptd.simulation.factory.IFactory Interface Reference
com.github.aptd.simulation.factory.IFactory Interface Reference
factory to generate all simulation entities
Public Member Functions
IElement.IGenerator< IDoor<?> > door (@Nonnull final InputStream p_stream, @Nonnull final Set< IAction > p_actions, final ITime p_time) throws Exception
creates a train door generator
IGraph< IStation<?>, ITrack<?> > network (@Nonnull final Stream< ITrack<?>> p_edge, @Nullable final Function< ITrack<?>, ? extends Number >... p_weight)
network generating
IElement.IGenerator< IPassenger<?> > passenger (@Nonnull final InputStream p_stream, @Nonnull final Set< IAction > p_actions, final ITime p_time) throws Exception
creates a passenger generator, which is used to generate passengers
IElement.IGenerator< IPassengerSource<?> > passengersource (@Nonnull final InputStream p_stream, @Nonnull final Set< IAction > p_actions, final ITime p_time) throws Exception
creates a PassengerSource generator, which is used to generate a passenger source
IElement.IGenerator< IPlatform<?> > platform (@Nonnull final InputStream p_stream, @Nonnull final Set< IAction > p_actions, final ITime p_time) throws Exception
creates a platform generator, which is used to generate platforms within stations
IElement.IGenerator< IStation<?> > station (@Nonnull final InputStream p_stream, @Nonnull final Set< IAction > p_actions, final ITime p_time) throws Exception
creates a full station generator, which is used to simulate also the station in detail
IElement.IGenerator< ITrain<?> > train (@Nonnull final InputStream p_stream, @Nonnull final Set< IAction > p_actions, final ITime p_time) throws Exception
creates a train generator
IElement.IGenerator< IStation<?> > transit (@Nonnull final InputStream p_stream, @Nonnull final Set< IAction > p_actions, final ITime p_time) throws Exception
creates a transit station generator, which is used to simulate demand only
IElement.IGenerator< IStation<?> > virtual (@Nonnull final InputStream p_stream, @Nonnull final Set< IAction > p_actions, final ITime p_time) throws Exception
creates a virtual station generator, which is used to simulate events only
Detailed Description
Bug:
incomplete
Definition at line 50 of file IFactory.java.
Member Function Documentation
door()
IElement.IGenerator<IDoor<?> > com.github.aptd.simulation.factory.IFactory.door (@Nonnull final InputStream p_stream, @Nonnull final Set< IAction > p_actions, final ITime p_time) throws Exception
Parameters
p_stream ASL stream
p_actions default actions
p_time time reference
Returns
generator
Exceptions
Exception is thrown on any error
Implemented in com.github.aptd.simulation.factory.CLocal.
Referenced by com.github.aptd.simulation.datamodel.CXMLReader.doorgenerator().
network()
IGraph<IStation<?>, ITrack<?> > com.github.aptd.simulation.factory.IFactory.network (@Nonnull final Stream< ITrack<?>> p_edge, @Nullable final Function< ITrack<?>, ? extends Number >... p_weight)
Parameters
p_edge edges
p_weight optional weight functions
Returns
network graph
Implemented in com.github.aptd.simulation.factory.CLocal.
passenger()
IElement.IGenerator<IPassenger<?> > com.github.aptd.simulation.factory.IFactory.passenger (@Nonnull final InputStream p_stream, @Nonnull final Set< IAction > p_actions, final ITime p_time) throws Exception
Parameters
p_stream ASL stream
p_actions default actions
p_time time reference
Returns
generator
Exceptions
Exception is thrown on any error
Implemented in com.github.aptd.simulation.factory.CLocal.
Referenced by com.github.aptd.simulation.datamodel.CXMLReader.passengergenerator().
passengersource()
IElement.IGenerator<IPassengerSource<?> > com.github.aptd.simulation.factory.IFactory.passengersource (@Nonnull final InputStream p_stream, @Nonnull final Set< IAction > p_actions, final ITime p_time) throws Exception
Parameters
p_stream ASL stream
p_actions default actions
p_time time reference
Returns
generator
Exceptions
Exception is thrown on any error
Implemented in com.github.aptd.simulation.factory.CLocal.
Referenced by com.github.aptd.simulation.datamodel.CXMLReader.passengersourcegenerator().
platform()
IElement.IGenerator<IPlatform<?> > com.github.aptd.simulation.factory.IFactory.platform (@Nonnull final InputStream p_stream, @Nonnull final Set< IAction > p_actions, final ITime p_time) throws Exception
Parameters
p_stream ASL stream
p_actions default actions
p_time time reference
Returns
generator
Exceptions
Exception is thrown on any error
Implemented in com.github.aptd.simulation.factory.CLocal.
Referenced by com.github.aptd.simulation.datamodel.CXMLReader.platformgenerator().
station()
IElement.IGenerator<IStation<?> > com.github.aptd.simulation.factory.IFactory.station (@Nonnull final InputStream p_stream, @Nonnull final Set< IAction > p_actions, final ITime p_time) throws Exception
Parameters
p_stream ASL stream
p_actions default actions
p_time time reference
Returns
generator
Exceptions
Exception is thrown on any error
Implemented in com.github.aptd.simulation.factory.CLocal.
Referenced by com.github.aptd.simulation.datamodel.CXMLReader.stationgenerator().
train()
IElement.IGenerator<ITrain<?> > com.github.aptd.simulation.factory.IFactory.train (@Nonnull final InputStream p_stream, @Nonnull final Set< IAction > p_actions, final ITime p_time) throws Exception
Parameters
p_stream ASL stream
p_actions default actions
p_time time reference
Returns
generator
Exceptions
Exception is thrown on any error
Implemented in com.github.aptd.simulation.factory.CLocal.
Referenced by com.github.aptd.simulation.datamodel.CXMLReader.traingenerator().
transit()
IElement.IGenerator<IStation<?> > com.github.aptd.simulation.factory.IFactory.transit (@Nonnull final InputStream p_stream, @Nonnull final Set< IAction > p_actions, final ITime p_time) throws Exception
Parameters
p_stream ASL stream
p_actions default actions
p_time time reference
Returns
generator
Exceptions
Exception is thrown on any error
Implemented in com.github.aptd.simulation.factory.CLocal.
virtual()
IElement.IGenerator<IStation<?> > com.github.aptd.simulation.factory.IFactory.virtual (@Nonnull final InputStream p_stream, @Nonnull final Set< IAction > p_actions, final ITime p_time) throws Exception
Parameters
p_stream ASL stream
p_actions default actions
p_time time reference
Returns
generator
Exceptions
Exception is thrown on any error
Implemented in com.github.aptd.simulation.factory.CLocal.