Asimov - Agentbased Passenger & Train Delay Simulation: com.github.aptd.simulation.core.runtime.local.CRuntime Class Reference
com.github.aptd.simulation.core.runtime.local.CRuntime Class Reference
local runtime
Public Member Functions
final IExperiment execute (final IExperiment p_experiment)
execute experiment
final IRuntime next ()
execution call on step-by-step execution
Static Private Member Functions
static void execute (final Callable<?> p_object)
execute callable object with catching exception
static< T > Stream< T > optionalparallelstream (final Stream< T > p_stream, final boolean p_parallel)
creates an optional parallel stream
Detailed Description
Todo:
refactor with logger
add step-by-step execution
Definition at line 39 of file CRuntime.java.
Member Function Documentation
execute() [1/2]
final IExperiment com.github.aptd.simulation.core.runtime.local.CRuntime.execute (final IExperiment p_experiment)
Parameters
p_experiment experiment
Returns
executed experiment
Implements com.github.aptd.simulation.core.runtime.IRuntime.
Definition at line 43 of file CRuntime.java.
References com.github.aptd.simulation.core.time.ITime.active(), com.github.aptd.simulation.core.experiment.IExperiment.objects(), com.github.aptd.simulation.core.runtime.local.CRuntime.optionalparallelstream(), com.github.aptd.simulation.core.experiment.IExperiment.parallel(), com.github.aptd.simulation.core.experiment.IExperiment.preprocess(), and com.github.aptd.simulation.core.experiment.IExperiment.time().
execute() [2/2]
static void com.github.aptd.simulation.core.runtime.local.CRuntime.execute (final Callable<?> p_object) static private
Parameters
p_object callable
Definition at line 80 of file CRuntime.java.
next()
final IRuntime com.github.aptd.simulation.core.runtime.local.CRuntime.next ()
Returns
self-reference
Implements com.github.aptd.simulation.core.runtime.IRuntime.
Definition at line 56 of file CRuntime.java.
optionalparallelstream()
static <T> Stream<T> com.github.aptd.simulation.core.runtime.local.CRuntime.optionalparallelstream (final Stream< T > p_stream, final boolean p_parallel) static private
Parameters
p_stream input stream
Returns
stream
Template Parameters
T stream element type
Definition at line 69 of file CRuntime.java.
Referenced by com.github.aptd.simulation.core.runtime.local.CRuntime.execute().