Asimov - Agentbased Passenger & Train Delay Simulation: com.github.aptd.simulation.elements.graph.network.local.CNetwork Class Reference
com.github.aptd.simulation.elements.graph.network.local.CNetwork Class Reference
graph class with local data
Public Member Functions
CNetwork (final Stream< ITrack<?>> p_edges)
ctor
CNetwork (final Stream< ITrack<?>> p_edges, final Function< ITrack<?>, ? extends Number > p_weightfunction)
ctor
final boolean containsedge (final IStation<?> p_start, final IStation<?> p_end)
final boolean containsedge (final ITrack<?> p_id)
final boolean containsvertex (final IStation<?> p_id)
final ITrack<?> edge (final IStation<?> p_start, final IStation<?> p_end)
final boolean equals (final Object p_object)
final int hashCode ()
final Stream< IStation<?> > neighbours (final IStation<?> p_id)
final List< ITrack<?> > route (final IStation<?> p_start, final IStation<?> p_end)
final String toString ()
Public Member Functions inherited from com.github.aptd.simulation.elements.graph.IGraph< V extends IVertex<?, E extends IEdge< V >
boolean containsedge (final V p_start, final V p_end)
checks if an edge exists
boolean containsedge (final E p_id)
boolean containsvertex (final V p_id)
checks if a vertex exist
E edge (final V p_start, final V p_end)
returns an edge
Stream< V > neighbours (final V p_id)
returns the neighbours of a node
List< E > route (final V p_start, final V p_end)
calculate a route
Private Attributes
final DijkstraShortestPath< IStation<?>, ITrack<?> > m_dijekstra
shortest-path algorthm
final DirectedSparseGraph< IStation<?>, ITrack<?> > m_graph = new DirectedSparseGraph<>()
graph data structure
Detailed Description
Template Parameters
T node identifier type
See also
http://jung.sourceforge.net/doc/api/edu/uci/ics/jung/graph/package-summary.html
Definition at line 42 of file CNetwork.java.
Constructor & Destructor Documentation
CNetwork() [1/2]
com.github.aptd.simulation.elements.graph.network.local.CNetwork.CNetwork (final Stream< ITrack<?>> p_edges)
Parameters
p_edges edge elements
Definition at line 60 of file CNetwork.java.
CNetwork() [2/2]
com.github.aptd.simulation.elements.graph.network.local.CNetwork.CNetwork (final Stream< ITrack<?>> p_edges, final Function< ITrack<?>, ? extends Number > p_weightfunction)
Parameters
p_edges edge elements
p_weightfunction weight function
Definition at line 71 of file CNetwork.java.
References com.github.aptd.simulation.elements.graph.network.local.CNetwork.m_graph.
Member Function Documentation
containsedge() [1/2]
final boolean com.github.aptd.simulation.elements.graph.network.local.CNetwork.containsedge (final IStation<?> p_start, final IStation<?> p_end)
Definition at line 123 of file CNetwork.java.
containsedge() [2/2]
final boolean com.github.aptd.simulation.elements.graph.network.local.CNetwork.containsedge (final ITrack<?> p_id)
Definition at line 129 of file CNetwork.java.
containsvertex()
final boolean com.github.aptd.simulation.elements.graph.network.local.CNetwork.containsvertex (final IStation<?> p_id)
Definition at line 117 of file CNetwork.java.
edge()
final ITrack<?> com.github.aptd.simulation.elements.graph.network.local.CNetwork.edge (final IStation<?> p_start, final IStation<?> p_end)
Definition at line 103 of file CNetwork.java.
equals()
final boolean com.github.aptd.simulation.elements.graph.network.local.CNetwork.equals (final Object p_object)
Definition at line 85 of file CNetwork.java.
References com.github.aptd.simulation.elements.graph.network.local.CNetwork.hashCode().
hashCode()
final int com.github.aptd.simulation.elements.graph.network.local.CNetwork.hashCode ()
Definition at line 79 of file CNetwork.java.
Referenced by com.github.aptd.simulation.elements.graph.network.local.CNetwork.equals().
neighbours()
final Stream<IStation<?> > com.github.aptd.simulation.elements.graph.network.local.CNetwork.neighbours (final IStation<?> p_id)
Definition at line 109 of file CNetwork.java.
route()
final List<ITrack<?> > com.github.aptd.simulation.elements.graph.network.local.CNetwork.route (final IStation<?> p_start, final IStation<?> p_end)
Definition at line 97 of file CNetwork.java.
toString()
final String com.github.aptd.simulation.elements.graph.network.local.CNetwork.toString ()
Definition at line 91 of file CNetwork.java.
Member Data Documentation
m_dijekstra
final DijkstraShortestPath<IStation<?>, ITrack<?> > com.github.aptd.simulation.elements.graph.network.local.CNetwork.m_dijekstra private
Definition at line 51 of file CNetwork.java.
m_graph
final DirectedSparseGraph<IStation<?>, ITrack<?> > com.github.aptd.simulation.elements.graph.network.local.CNetwork.m_graph = new DirectedSparseGraph<>() private
Definition at line 47 of file CNetwork.java.
Referenced by com.github.aptd.simulation.elements.graph.network.local.CNetwork.CNetwork().