# open browsers window on start-up
openbrowser : true


# HTTP server binding for UI
httpserver:
    enable: true
    port: 8000
    host: localhost


# default elements
default:
  datamodel: xml
  #iteration: 10

# runtime configuration
runtime:
    type: local
    parallel: true
    stepbystep: false


# simulation units
units:
    cellsize_in_meter: 1.5
    time_in_minutes: 1.25

