Asimov - Agentbased Passenger & Train Delay Simulation: com.github.aptd.simulation.CMain Class Reference
com.github.aptd.simulation.CMain Class Reference
main class
Static Public Member Functions
static void main (final String[] p_args) throws IOException
main method
Static Package Functions
[static initializer]
Private Member Functions
CMain ()
ctor
Static Private Member Functions
static Stream< Pair< EDataModel, String > > datamodel (final CommandLine p_options)
returns the experiment data models
static void execute (final CommandLine p_cli)
Detailed Description
Definition at line 56 of file CMain.java.
Constructor & Destructor Documentation
CMain()
com.github.aptd.simulation.CMain.CMain () private
Definition at line 66 of file CMain.java.
Member Function Documentation
[static initializer]()
com.github.aptd.simulation.CMain.[static initializer] () static package
datamodel()
static Stream<Pair<EDataModel, String> > com.github.aptd.simulation.CMain.datamodel (final CommandLine p_options) static private
Parameters
p_options commandline options
Returns
stream of experiments
Definition at line 179 of file CMain.java.
References com.github.aptd.simulation.datamodel.EDataModel.from(), com.github.aptd.simulation.common.CConfiguration.getOrDefault(), and com.github.aptd.simulation.common.CConfiguration.INSTANCE.
Referenced by com.github.aptd.simulation.CMain.execute().
execute()
static void com.github.aptd.simulation.CMain.execute (final CommandLine p_cli) static private
Definition at line 130 of file CMain.java.
References com.github.aptd.simulation.CMain.datamodel(), com.github.aptd.simulation.ui.CHTTPServer.execute(), com.github.aptd.simulation.factory.EFactory.from(), com.github.aptd.simulation.common.CConfiguration.getOrDefault(), com.github.aptd.simulation.common.CConfiguration.INSTANCE, com.github.aptd.simulation.common.CConfiguration.loadfile(), and com.github.aptd.simulation.core.runtime.ERuntime.LOCAL.
Referenced by com.github.aptd.simulation.CMain.main().
main()
static void com.github.aptd.simulation.CMain.main (final String [] p_args) throws IOException static
Parameters
p_args command-line parameters
Exceptions
IOException error on io errors
Definition at line 74 of file CMain.java.
References com.github.aptd.simulation.common.CConfiguration.createdefault(), com.github.aptd.simulation.CMain.execute(), and com.github.aptd.simulation.common.CCommon.languagestring().