Asimov - Agentbased Passenger & Train Delay Simulation: com.github.aptd.simulation.common.CConfiguration Class Reference
com.github.aptd.simulation.common.CConfiguration Class Reference
configuration
Public Member Functions
final Set< IAction > agentaction (final IAction... p_action)
returns a set with all agent actions
final Set< IAction > agentaction (final Stream< IAction > p_action)
returns a set with all agent actions
final< T > T get (final String... p_path)
returns a configuration value
final< T > T getOrDefault (final T p_default, final String... p_path)
returns a configuration value or on not existing the default value
final CConfiguration loadfile (final String p_path)
loads the configuration
final CConfiguration loadstring (final String p_yaml)
loads the configuration from a string
Static Public Member Functions
static String createdefault () throws IOException
creates the default configuration
Static Public Attributes
static final CConfiguration INSTANCE = new CConfiguration()
singleton instance
Private Member Functions
CConfiguration ()
ctor
Static Private Member Functions
static String orDefaultPath (final String p_path)
set default path
static< T > T recursivedescent (final Map< String, ?> p_map, final String... p_path)
recursive descent
Private Attributes
final Set< IAction > m_agentaction = org.lightjason.agentspeak.common.CCommon.actionsFromPackage().collect(Collectors.toSet())
all global agent actions
final Map< String, Object > m_configuration = new ConcurrentHashMap<>()
map with configuration data
Detailed Description
Todo:
check on hadoop access
Definition at line 50 of file CConfiguration.java.
Constructor & Destructor Documentation
CConfiguration()
com.github.aptd.simulation.common.CConfiguration.CConfiguration () private
Definition at line 69 of file CConfiguration.java.
Member Function Documentation
agentaction() [1/2]
final Set<IAction> com.github.aptd.simulation.common.CConfiguration.agentaction (final IAction... p_action)
Parameters
p_action arguments with additional actions
Returns
action set
Definition at line 168 of file CConfiguration.java.
Referenced by com.github.aptd.simulation.elements.graph.TestCNetwork.ininitialize().
agentaction() [2/2]
final Set<IAction> com.github.aptd.simulation.common.CConfiguration.agentaction (final Stream< IAction > p_action)
Parameters
p_action stream with additional actions
Returns
action set
Definition at line 181 of file CConfiguration.java.
createdefault()
static String com.github.aptd.simulation.common.CConfiguration.createdefault () throws IOException static
Returns
full path
Exceptions
IOException on any io error
Definition at line 145 of file CConfiguration.java.
Referenced by com.github.aptd.simulation.CMain.main().
get()
final<T> T com.github.aptd.simulation.common.CConfiguration.get (final String... p_path)
Parameters
p_path path of the element
Template Parameters
T returning type
Returns
value or null
Definition at line 193 of file CConfiguration.java.
References com.github.aptd.simulation.common.CConfiguration.recursivedescent().
getOrDefault()
final<T> T com.github.aptd.simulation.common.CConfiguration.getOrDefault (final T p_default, final String... p_path)
Parameters
p_default default value
p_path path of the element
Template Parameters
T returning type
Returns
value / default vaue
Definition at line 207 of file CConfiguration.java.
References com.github.aptd.simulation.common.CConfiguration.recursivedescent().
Referenced by com.github.aptd.simulation.CMain.datamodel(), and com.github.aptd.simulation.CMain.execute().
loadfile()
final CConfiguration com.github.aptd.simulation.common.CConfiguration.loadfile (final String p_path)
Parameters
p_path path elements
Returns
self reference
Definition at line 79 of file CConfiguration.java.
References com.github.aptd.simulation.common.CConfiguration.orDefaultPath().
Referenced by com.github.aptd.simulation.CMain.execute().
loadstring()
final CConfiguration com.github.aptd.simulation.common.CConfiguration.loadstring (final String p_yaml)
Parameters
p_yaml yaml string
Returns
self reference
Definition at line 111 of file CConfiguration.java.
Referenced by com.github.aptd.simulation.elements.graph.TestCNetwork.ininitialize().
orDefaultPath()
static String com.github.aptd.simulation.common.CConfiguration.orDefaultPath (final String p_path) static private
Parameters
p_path path or null / empty
Returns
default path on empty or input path
Definition at line 128 of file CConfiguration.java.
Referenced by com.github.aptd.simulation.common.CConfiguration.loadfile().
recursivedescent()
static <T> T com.github.aptd.simulation.common.CConfiguration.recursivedescent (final Map< String, ?> p_map, final String... p_path) static private
Parameters
p_map configuration map
p_path path
Template Parameters
T returning type parameter
Returns
value
Definition at line 225 of file CConfiguration.java.
Referenced by com.github.aptd.simulation.common.CConfiguration.get(), and com.github.aptd.simulation.common.CConfiguration.getOrDefault().
Member Data Documentation
INSTANCE
final CConfiguration com.github.aptd.simulation.common.CConfiguration.INSTANCE = new CConfiguration() static
Definition at line 55 of file CConfiguration.java.
Referenced by com.github.aptd.simulation.ui.CHTTPServer.CHTTPServer(), com.github.aptd.simulation.CMain.datamodel(), com.github.aptd.simulation.ui.CHTTPServer.execute(), com.github.aptd.simulation.CMain.execute(), and com.github.aptd.simulation.elements.graph.TestCNetwork.ininitialize().
m_agentaction
final Set<IAction> com.github.aptd.simulation.common.CConfiguration.m_agentaction = org.lightjason.agentspeak.common.CCommon.actionsFromPackage().collect(Collectors.toSet()) private
Definition at line 63 of file CConfiguration.java.
m_configuration
final Map<String, Object> com.github.aptd.simulation.common.CConfiguration.m_configuration = new ConcurrentHashMap<>() private
Definition at line 59 of file CConfiguration.java.