Asimov - Agentbased Passenger & Train Delay Simulation: com.github.aptd.simulation.datamodel.CXMLReader Class Reference
com.github.aptd.simulation.datamodel.CXMLReader Class Reference
data-model XML reader
Public Member Functions
CXMLReader ()
ctor
final IExperiment get (final IFactory p_factory, final String p_datamodel, final long p_simulationsteps, final boolean p_parallel, final String p_timemodel, final Supplier< RealDistribution > p_passengerspeedatstationdistributionsupplier)
transfer the data-model into an experiment based on given factory
Static Private Member Functions
static< T > Pair< T, String > agentname (final T p_value, final List< Object > p_list)
get an agent-reference name
static Map< String, String > agents (final Iagents p_ai)
creates the agent structure
static IElement.IGenerator< IDoor<?> > doorgenerator (final IFactory p_factory, final String p_asl, final Set< IAction > p_actions, final ITime p_time)
creates a train door agent generator
static boolean hasagentname (final List< Object > p_list)
filter an object list
static IElement.IGenerator< IPassenger<?> > passengergenerator (final IFactory p_factory, final String p_asl, final Set< IAction > p_actions, final ITime p_time)
creates a Passenger agent generator
static IElement.IGenerator< IPassengerSource<?> > passengersourcegenerator (final IFactory p_factory, final String p_asl, final Set< IAction > p_actions, final ITime p_time)
creates a PassengerSource agent generator
static Map< String, IPlatform<?> > platform (final Network p_network, final Map< String, String > p_agents, final IFactory p_factory, final ITime p_time)
create the platforms of all stations
static IElement.IGenerator< IPlatform<?> > platformgenerator (final IFactory p_factory, final String p_asl, final Set< IAction > p_actions, final ITime p_time)
creates a platform agent generator
static Map< String, IStation<?> > station (final Network p_network, final Map< String, String > p_agents, final IFactory p_factory, final ITime p_time, final Map< String, IPlatform<?>> p_platforms)
create the station list
static IElement.IGenerator< IStation<?> > stationgenerator (final IFactory p_factory, final String p_asl, final Set< IAction > p_actions, final ITime p_time)
creates a station agent generator
static Pair< Map< String, ITrain<?> >, Map< String, IDoor<?> > > train (final Network p_network, final Map< String, String > p_agents, final IFactory p_factory, final ITime p_time)
create the train list
static IElement.IGenerator< ITrain<?> > traingenerator (final IFactory p_factory, final String p_asl, final Set< IAction > p_actions, final ITime p_time)
creates a train agent generator
Private Attributes
final JAXBContext m_context
jaxb context
Static Private Attributes
static final QName PLATFORM_REF_ATTRIBUTE
Detailed Description
Bug:
incomplete
Definition at line 100 of file CXMLReader.java.
Constructor & Destructor Documentation
CXMLReader()
com.github.aptd.simulation.datamodel.CXMLReader.CXMLReader ()
Definition at line 114 of file CXMLReader.java.
Member Function Documentation
agentname()
static <T> Pair<T, String> com.github.aptd.simulation.datamodel.CXMLReader.agentname (final T p_value, final List< Object > p_list) static private
Parameters
p_value value of the agent-reference
p_list object list
Returns
agent-reference name
Exceptions
CNotFoundException is thrown on not found
Definition at line 553 of file CXMLReader.java.
Referenced by com.github.aptd.simulation.datamodel.CXMLReader.station(), and com.github.aptd.simulation.datamodel.CXMLReader.train().
agents()
static Map<String, String> com.github.aptd.simulation.datamodel.CXMLReader.agents (final Iagents p_ai) static private
Parameters
p_ai AI component
Returns
unmodifyable agent map
Definition at line 212 of file CXMLReader.java.
Referenced by com.github.aptd.simulation.datamodel.CXMLReader.get().
doorgenerator()
static IElement.IGenerator<IDoor<?> > com.github.aptd.simulation.datamodel.CXMLReader.doorgenerator (final IFactory p_factory, final String p_asl, final Set< IAction > p_actions, final ITime p_time) static private
Parameters
p_factory factory
p_asl asl script as String
p_actions actions
Returns
train door generator
Definition at line 474 of file CXMLReader.java.
References com.github.aptd.simulation.factory.IFactory.door().
Referenced by com.github.aptd.simulation.datamodel.CXMLReader.train().
get()
final IExperiment com.github.aptd.simulation.datamodel.CXMLReader.get (final IFactory p_factory, final String p_datamodel, final long p_simulationsteps, final boolean p_parallel, final String p_timemodel, final Supplier< RealDistribution > p_passengerspeedatstationdistributionsupplier)
Parameters
p_factory building factory
p_datamodel any representation of the datamodel
Returns
experiment
Implements com.github.aptd.simulation.datamodel.IDataModel.
Definition at line 128 of file CXMLReader.java.
References com.github.aptd.simulation.core.experiment.local.CExperiment.addAgent(), com.github.aptd.simulation.datamodel.CXMLReader.agents(), com.github.aptd.simulation.core.statistic.IStatistic.EMPTY, com.github.aptd.simulation.datamodel.CXMLReader.passengergenerator(), com.github.aptd.simulation.datamodel.CXMLReader.passengersourcegenerator(), com.github.aptd.simulation.datamodel.CXMLReader.platform(), com.github.aptd.simulation.datamodel.CXMLReader.station(), and com.github.aptd.simulation.datamodel.CXMLReader.train().
hasagentname()
static boolean com.github.aptd.simulation.datamodel.CXMLReader.hasagentname (final List< Object > p_list) static private
Parameters
p_list object list
Returns
agent-reference exist
Definition at line 572 of file CXMLReader.java.
Referenced by com.github.aptd.simulation.datamodel.CXMLReader.station(), and com.github.aptd.simulation.datamodel.CXMLReader.train().
passengergenerator()
static IElement.IGenerator<IPassenger<?> > com.github.aptd.simulation.datamodel.CXMLReader.passengergenerator (final IFactory p_factory, final String p_asl, final Set< IAction > p_actions, final ITime p_time) static private
Parameters
p_factory factory
p_asl asl script as String
p_actions actions
Returns
Passenger generator
Definition at line 526 of file CXMLReader.java.
References com.github.aptd.simulation.factory.IFactory.passenger().
Referenced by com.github.aptd.simulation.datamodel.CXMLReader.get().
passengersourcegenerator()
static IElement.IGenerator<IPassengerSource<?> > com.github.aptd.simulation.datamodel.CXMLReader.passengersourcegenerator (final IFactory p_factory, final String p_asl, final Set< IAction > p_actions, final ITime p_time) static private
Parameters
p_factory factory
p_asl asl script as String
p_actions actions
Returns
PassengerSource generator
Definition at line 500 of file CXMLReader.java.
References com.github.aptd.simulation.factory.IFactory.passengersource().
Referenced by com.github.aptd.simulation.datamodel.CXMLReader.get().
platform()
static Map<String, IPlatform<?> > com.github.aptd.simulation.datamodel.CXMLReader.platform (final Network p_network, final Map< String, String > p_agents, final IFactory p_factory, final ITime p_time) static private
Parameters
p_network network component
p_agents map with agent asl scripts
p_factory factory
p_time time reference
Returns
unmodifyable map with platforms
Definition at line 296 of file CXMLReader.java.
References com.github.aptd.simulation.elements.IElement< T extends IAgent<?>.id(), and com.github.aptd.simulation.datamodel.CXMLReader.platformgenerator().
Referenced by com.github.aptd.simulation.datamodel.CXMLReader.get().
platformgenerator()
static IElement.IGenerator<IPlatform<?> > com.github.aptd.simulation.datamodel.CXMLReader.platformgenerator (final IFactory p_factory, final String p_asl, final Set< IAction > p_actions, final ITime p_time) static private
Parameters
p_factory factory
p_asl asl script as String
p_actions actions
Returns
platform generator
Definition at line 332 of file CXMLReader.java.
References com.github.aptd.simulation.factory.IFactory.platform().
Referenced by com.github.aptd.simulation.datamodel.CXMLReader.platform().
station()
static Map<String, IStation<?> > com.github.aptd.simulation.datamodel.CXMLReader.station (final Network p_network, final Map< String, String > p_agents, final IFactory p_factory, final ITime p_time, final Map< String, IPlatform<?>> p_platforms) static private
Parameters
p_network network component
p_agents map with agent asl scripts
p_factory factory
p_time time reference
p_platforms map with already generated platforms
Returns
unmodifyable map with stations
Definition at line 233 of file CXMLReader.java.
References com.github.aptd.simulation.datamodel.CXMLReader.agentname(), com.github.aptd.simulation.datamodel.CXMLReader.hasagentname(), com.github.aptd.simulation.elements.IElement< T extends IAgent<?>.id(), com.github.aptd.simulation.datamodel.CXMLReader.stationgenerator(), and com.github.aptd.simulation.elements.graph.network.IPlatform< T extends IPlatform<?>.stationid().
Referenced by com.github.aptd.simulation.datamodel.CXMLReader.get().
stationgenerator()
static IElement.IGenerator<IStation<?> > com.github.aptd.simulation.datamodel.CXMLReader.stationgenerator (final IFactory p_factory, final String p_asl, final Set< IAction > p_actions, final ITime p_time) static private
Parameters
p_factory factory
p_asl asl script as String
p_actions actions
Returns
station generator
Definition at line 269 of file CXMLReader.java.
References com.github.aptd.simulation.factory.IFactory.station().
Referenced by com.github.aptd.simulation.datamodel.CXMLReader.station().
train()
static Pair<Map<String, ITrain<?> >, Map<String, IDoor<?> > > com.github.aptd.simulation.datamodel.CXMLReader.train (final Network p_network, final Map< String, String > p_agents, final IFactory p_factory, final ITime p_time) static private
Parameters
p_network network component
p_agents map with agent asl scripts
p_factory factory
Returns
unmodifiable map with trains
Definition at line 358 of file CXMLReader.java.
References com.github.aptd.simulation.datamodel.CXMLReader.agentname(), com.github.aptd.simulation.core.time.ITime.current(), com.github.aptd.simulation.datamodel.CXMLReader.doorgenerator(), com.github.aptd.simulation.elements.IStatefulElement< N extends IElement<?>.getDefaultAsl(), com.github.aptd.simulation.datamodel.CXMLReader.hasagentname(), com.github.aptd.simulation.elements.IElement< T extends IAgent<?>.id(), com.github.aptd.simulation.datamodel.CXMLReader.PLATFORM_REF_ATTRIBUTE, and com.github.aptd.simulation.datamodel.CXMLReader.traingenerator().
Referenced by com.github.aptd.simulation.datamodel.CXMLReader.get().
traingenerator()
static IElement.IGenerator<ITrain<?> > com.github.aptd.simulation.datamodel.CXMLReader.traingenerator (final IFactory p_factory, final String p_asl, final Set< IAction > p_actions, final ITime p_time) static private
Parameters
p_factory factory
p_asl asl script as String
p_actions actions
Returns
train generator
Definition at line 448 of file CXMLReader.java.
References com.github.aptd.simulation.factory.IFactory.train().
Referenced by com.github.aptd.simulation.datamodel.CXMLReader.train().
Member Data Documentation
m_context
final JAXBContext com.github.aptd.simulation.datamodel.CXMLReader.m_context private
Definition at line 109 of file CXMLReader.java.
PLATFORM_REF_ATTRIBUTE
final QName com.github.aptd.simulation.datamodel.CXMLReader.PLATFORM_REF_ATTRIBUTE static private
Initial value:
= new QName(
        "https://raw.githubusercontent.com/APTD/Simulation/master/src/main/xsd",
        "platformRef"
    )
Definition at line 102 of file CXMLReader.java.
Referenced by com.github.aptd.simulation.datamodel.CXMLReader.train().