Asimov - Agentbased Passenger & Train Delay Simulation: com.github.aptd.simulation.elements.graph.eventactivitynetwork.local.CEventActivityNetwork Class Reference
com.github.aptd.simulation.elements.graph.eventactivitynetwork.local.CEventActivityNetwork Class Reference
event-activity-network
Public Member Functions
CEventActivityNetwork (final Stream< IActivity > p_edges)
ctor
final boolean containsedge (final INode p_start, final INode p_end)
final boolean containsedge (final IActivity p_id)
final boolean containsvertex (final INode p_id)
final IActivity edge (final INode p_start, final INode p_end)
final boolean equals (final Object p_object)
final int hashCode ()
final ILinearProgram linearprogram ()
returns the linear-program of the graph
final Stream< INode > neighbours (final INode p_id)
final List< IActivity > route (final INode p_start, final INode p_end)
Public Member Functions inherited from com.github.aptd.simulation.elements.graph.IGraph< V extends IVertex<?, E extends IEdge< V >
boolean containsedge (final V p_start, final V p_end)
checks if an edge exists
boolean containsedge (final E p_id)
boolean containsvertex (final V p_id)
checks if a vertex exist
E edge (final V p_start, final V p_end)
returns an edge
Stream< V > neighbours (final V p_id)
returns the neighbours of a node
List< E > route (final V p_start, final V p_end)
calculate a route
Private Attributes
final DijkstraShortestPath< INode, IActivity > m_dijekstra
shortest-path algorthm
final DirectedSparseGraph< INode, IActivity > m_graph = new DirectedSparseGraph<>()
graph data structure
Detailed Description
Bug:
incomplete
Definition at line 42 of file CEventActivityNetwork.java.
Constructor & Destructor Documentation
CEventActivityNetwork()
com.github.aptd.simulation.elements.graph.eventactivitynetwork.local.CEventActivityNetwork.CEventActivityNetwork (final Stream< IActivity > p_edges)
Parameters
p_edges edge elements
Definition at line 60 of file CEventActivityNetwork.java.
References com.github.aptd.simulation.elements.graph.eventactivitynetwork.local.CEventActivityNetwork.m_graph.
Member Function Documentation
containsedge() [1/2]
final boolean com.github.aptd.simulation.elements.graph.eventactivitynetwork.local.CEventActivityNetwork.containsedge (final INode p_start, final INode p_end)
Definition at line 106 of file CEventActivityNetwork.java.
containsedge() [2/2]
final boolean com.github.aptd.simulation.elements.graph.eventactivitynetwork.local.CEventActivityNetwork.containsedge (final IActivity p_id)
Definition at line 112 of file CEventActivityNetwork.java.
containsvertex()
final boolean com.github.aptd.simulation.elements.graph.eventactivitynetwork.local.CEventActivityNetwork.containsvertex (final INode p_id)
Definition at line 100 of file CEventActivityNetwork.java.
edge()
final IActivity com.github.aptd.simulation.elements.graph.eventactivitynetwork.local.CEventActivityNetwork.edge (final INode p_start, final INode p_end)
Definition at line 86 of file CEventActivityNetwork.java.
equals()
final boolean com.github.aptd.simulation.elements.graph.eventactivitynetwork.local.CEventActivityNetwork.equals (final Object p_object)
Definition at line 74 of file CEventActivityNetwork.java.
References com.github.aptd.simulation.elements.graph.eventactivitynetwork.local.CEventActivityNetwork.hashCode().
hashCode()
final int com.github.aptd.simulation.elements.graph.eventactivitynetwork.local.CEventActivityNetwork.hashCode ()
Definition at line 68 of file CEventActivityNetwork.java.
Referenced by com.github.aptd.simulation.elements.graph.eventactivitynetwork.local.CEventActivityNetwork.equals().
linearprogram()
final ILinearProgram com.github.aptd.simulation.elements.graph.eventactivitynetwork.local.CEventActivityNetwork.linearprogram ()
Returns
linear-program
Implements com.github.aptd.simulation.elements.graph.eventactivitynetwork.IEventActivityNetwork.
Definition at line 118 of file CEventActivityNetwork.java.
neighbours()
final Stream<INode> com.github.aptd.simulation.elements.graph.eventactivitynetwork.local.CEventActivityNetwork.neighbours (final INode p_id)
Definition at line 92 of file CEventActivityNetwork.java.
route()
final List<IActivity> com.github.aptd.simulation.elements.graph.eventactivitynetwork.local.CEventActivityNetwork.route (final INode p_start, final INode p_end)
Definition at line 80 of file CEventActivityNetwork.java.
Member Data Documentation
m_dijekstra
final DijkstraShortestPath<INode, IActivity> com.github.aptd.simulation.elements.graph.eventactivitynetwork.local.CEventActivityNetwork.m_dijekstra private
Definition at line 51 of file CEventActivityNetwork.java.
m_graph
final DirectedSparseGraph<INode, IActivity> com.github.aptd.simulation.elements.graph.eventactivitynetwork.local.CEventActivityNetwork.m_graph = new DirectedSparseGraph<>() private
Definition at line 47 of file CEventActivityNetwork.java.
Referenced by com.github.aptd.simulation.elements.graph.eventactivitynetwork.local.CEventActivityNetwork.CEventActivityNetwork().