Asimov - Agentbased Passenger & Train Delay Simulation: com.github.aptd.simulation.core.experiment.local.CExperiment Class Reference
com.github.aptd.simulation.core.experiment.local.CExperiment Class Reference
experiment definition
Classes
class CMessageSendAction
agent send action for agent communication
Public Member Functions
CExperiment (final long p_steps, final boolean p_parallel, @Nonnull final IStatistic p_statistic, @Nonnull final Map< String, ? extends IElement<?>> p_agents, @Nonnull final ITime p_time, @Nonnull final IMessenger p_messenger)
ctor
final Stream< IAction > actions ()
returns internal experiment actions
IElement<?> addAgent (final String p_key, final IElement<?> p_value)
add agent to the experiment
IElement<?> getAgent (final String p_key)
get agent by key (ID)
final Stream< IElement<?> > objects ()
returns a stream of all executable objects
final boolean parallel ()
execute agents in parallel
final Stream< Callable<?> > preprocess ()
preprocessing objects
final long simulationsteps ()
maximum simulation steps
final IExperiment statistic (@Nonnull final IWriter p_writer)
statistic writer
final ITime time ()
get the time object
Private Attributes
final Set< IAction > m_actions
set with actions
final Map< String, IElement<?> > m_agents = new ConcurrentHashMap<>()
agents
final IMessenger m_messenger
messenger object
final boolean m_parallel
parallel execution
final IStatistic m_statistic
statistic object
final long m_steps
simulation steps
final ITime m_time
time object
Additional Inherited Members
Public Attributes inherited from com.github.aptd.simulation.core.experiment.IExperiment
IExperiment EMPTY = new CEmptyExperiment()
empty experiment
Detailed Description
Definition at line 59 of file CExperiment.java.
Constructor & Destructor Documentation
CExperiment()
com.github.aptd.simulation.core.experiment.local.CExperiment.CExperiment (final long p_steps, final boolean p_parallel, @Nonnull final IStatistic p_statistic, @Nonnull final Map< String, ? extends IElement<?>> p_agents, @Nonnull final ITime p_time, @Nonnull final IMessenger p_messenger)
Parameters
p_steps number of simulation steps
p_parallel parallel object execution
p_statistic statistic object
p_agents stream with agents
p_time time object
Definition at line 102 of file CExperiment.java.
Member Function Documentation
actions()
final Stream<IAction> com.github.aptd.simulation.core.experiment.local.CExperiment.actions ()
Returns
action stream
Implements com.github.aptd.simulation.core.experiment.IExperiment.
Definition at line 176 of file CExperiment.java.
References com.github.aptd.simulation.core.statistic.IStatistic.action().
addAgent()
IElement<?> com.github.aptd.simulation.core.experiment.local.CExperiment.addAgent (final String p_key, final IElement<?> p_value)
Parameters
p_key agent key
p_value agent
Returns
added agent or existing agent with same id
Implements com.github.aptd.simulation.core.experiment.IExperiment.
Definition at line 128 of file CExperiment.java.
References com.github.aptd.simulation.core.time.ITime.addagent().
Referenced by com.github.aptd.simulation.datamodel.CXMLReader.get().
getAgent()
IElement<?> com.github.aptd.simulation.core.experiment.local.CExperiment.getAgent (final String p_key)
Parameters
p_key agent key
Returns
agent
Implements com.github.aptd.simulation.core.experiment.IExperiment.
Definition at line 140 of file CExperiment.java.
objects()
final Stream<IElement<?> > com.github.aptd.simulation.core.experiment.local.CExperiment.objects ()
Returns
callable stream
Implements com.github.aptd.simulation.core.experiment.IExperiment.
Definition at line 147 of file CExperiment.java.
parallel()
final boolean com.github.aptd.simulation.core.experiment.local.CExperiment.parallel ()
Returns
boolean flag for parallel execution
Implements com.github.aptd.simulation.core.experiment.IExperiment.
Definition at line 182 of file CExperiment.java.
References com.github.aptd.simulation.core.experiment.local.CExperiment.m_parallel.
preprocess()
final Stream<Callable<?> > com.github.aptd.simulation.core.experiment.local.CExperiment.preprocess ()
Returns
object stream
Implements com.github.aptd.simulation.core.experiment.IExperiment.
Definition at line 154 of file CExperiment.java.
simulationsteps()
final long com.github.aptd.simulation.core.experiment.local.CExperiment.simulationsteps ()
Returns
simulation steps
Implements com.github.aptd.simulation.core.experiment.IExperiment.
Definition at line 161 of file CExperiment.java.
References com.github.aptd.simulation.core.experiment.local.CExperiment.m_steps.
statistic()
final IExperiment com.github.aptd.simulation.core.experiment.local.CExperiment.statistic (@Nonnull final IWriter p_writer)
Returns
self-reference
Implements com.github.aptd.simulation.core.experiment.IExperiment.
Definition at line 168 of file CExperiment.java.
References com.github.aptd.simulation.core.statistic.IStatistic.write().
time()
final ITime com.github.aptd.simulation.core.experiment.local.CExperiment.time ()
Returns
time object
Implements com.github.aptd.simulation.core.experiment.IExperiment.
Definition at line 188 of file CExperiment.java.
References com.github.aptd.simulation.core.experiment.local.CExperiment.m_time.
Member Data Documentation
m_actions
final Set<IAction> com.github.aptd.simulation.core.experiment.local.CExperiment.m_actions private
Definition at line 90 of file CExperiment.java.
m_agents
final Map<String, IElement<?> > com.github.aptd.simulation.core.experiment.local.CExperiment.m_agents = new ConcurrentHashMap<>() private
Definition at line 86 of file CExperiment.java.
m_messenger
final IMessenger com.github.aptd.simulation.core.experiment.local.CExperiment.m_messenger private
Definition at line 82 of file CExperiment.java.
m_parallel
final boolean com.github.aptd.simulation.core.experiment.local.CExperiment.m_parallel private
Definition at line 70 of file CExperiment.java.
Referenced by com.github.aptd.simulation.core.experiment.local.CExperiment.parallel().
m_statistic
final IStatistic com.github.aptd.simulation.core.experiment.local.CExperiment.m_statistic private
Definition at line 74 of file CExperiment.java.
m_steps
final long com.github.aptd.simulation.core.experiment.local.CExperiment.m_steps private
Definition at line 66 of file CExperiment.java.
Referenced by com.github.aptd.simulation.core.experiment.local.CExperiment.simulationsteps().
m_time
final ITime com.github.aptd.simulation.core.experiment.local.CExperiment.m_time private
Definition at line 78 of file CExperiment.java.
Referenced by com.github.aptd.simulation.core.experiment.local.CExperiment.time().