Asimov - Agentbased Passenger & Train Delay Simulation: com.github.aptd.simulation.elements.IPerceiveable Interface Reference
com.github.aptd.simulation.elements.IPerceiveable Interface Reference
any object which be perceived by an agent
Public Member Functions
Stream< ILiteral > literal (final IElement<?>... p_object)
get literal of the object
Stream< ILiteral > literal (final Stream< IElement<?>> p_object)
get literal of the object
Detailed Description
Definition at line 33 of file IPerceiveable.java.
Member Function Documentation
literal() [1/2]
Stream<ILiteral> com.github.aptd.simulation.elements.IPerceiveable.literal (final IElement<?>... p_object)
Parameters
p_object objects
Returns
stream of literal
Implemented in com.github.aptd.simulation.core.time.IBaseTime, and com.github.aptd.simulation.elements.common.CGPS.
Referenced by com.github.aptd.simulation.elements.IBaseElement< N extends IElement<?>.CTimeBeliefbase.containsLiteral(), com.github.aptd.simulation.elements.IBaseElement< N extends IElement<?>.CTimeBeliefbase.empty(), com.github.aptd.simulation.elements.graph.network.local.IBaseStation.individualliteral(), com.github.aptd.simulation.elements.IBaseElement< N extends IElement<?>.CTimeBeliefbase.literal(), com.github.aptd.simulation.elements.IBaseElement< N extends IElement<?>.CTimeBeliefbase.size(), and com.github.aptd.simulation.elements.IBaseElement< N extends IElement<?>.CTimeBeliefbase.streamLiteral().
literal() [2/2]
Stream<ILiteral> com.github.aptd.simulation.elements.IPerceiveable.literal (final Stream< IElement<?>> p_object)
Parameters
p_object objects
Returns
stream of literal
Implemented in com.github.aptd.simulation.core.time.IBaseTime, and com.github.aptd.simulation.elements.common.CGPS.