Asimov - Agentbased Passenger & Train Delay Simulation: com.github.aptd.simulation.common.CCommon Class Reference
com.github.aptd.simulation.common.CCommon Class Reference
class for any helper calls
Classes
class CUTF8Control
class to read UTF-8 encoded property file
Static Public Member Functions
static URL concaturl (final URL p_base, final String p_string) throws MalformedURLException, URISyntaxException
concats an URL with a path
static ResourceBundle configuration ()
returns the property data of the package
static ResourceBundle languagebundle ()
returns the language bundle
static String [] languages ()
list of usable languages
static< T > String languagestring (final T p_source, final String p_label, final Object... p_parameter)
returns the language depend string on any object
static String languagestring (final Class<?> p_class, final String p_label, final Object... p_parameter)
returns a string of the resource file
static Logger logger (final Class<?> p_class)
returns a logger instance
static URL resourceurl ()
returns root path of the resource
static URL resourceurl (final String p_file) throws URISyntaxException, MalformedURLException
returns a file from a resource e.g.
Static Public Attributes
static final String PACKAGEROOT = "com.github.aptd.simulation"
package name
Private Member Functions
CCommon ()
private ctor - avoid instantiation
Static Private Member Functions
static String languagelabel (final Class<?> p_class, final String p_label)
returns the label of a class and string to get access to the resource
static URL resourceurl (final File p_file) throws URISyntaxException, MalformedURLException
returns a file from a resource e.g.
Static Private Attributes
static final ResourceBundle LANGUAGE
language resource bundle
static final Logger LOGGER = CCommon.logger(CCommon.class)
logger
static final ResourceBundle PROPERTIES
properties of the package
Detailed Description
Definition at line 45 of file CCommon.java.
Constructor & Destructor Documentation
CCommon()
com.github.aptd.simulation.common.CCommon.CCommon () private
Definition at line 76 of file CCommon.java.
Member Function Documentation
concaturl()
static URL com.github.aptd.simulation.common.CCommon.concaturl (final URL p_base, final String p_string) throws MalformedURLException, URISyntaxException static
Parameters
p_base base URL
p_string additional path
Returns
new URL
Exceptions
URISyntaxException thrown on syntax error
MalformedURLException thrown on malformat
Definition at line 133 of file CCommon.java.
configuration()
static ResourceBundle com.github.aptd.simulation.common.CCommon.configuration () static
Returns
bundle object
Definition at line 116 of file CCommon.java.
References com.github.aptd.simulation.common.CCommon.PROPERTIES.
Referenced by com.github.aptd.simulation.TestCLanguageLabels.testTranslation().
languagebundle()
static ResourceBundle com.github.aptd.simulation.common.CCommon.languagebundle () static
Returns
bundle
Definition at line 106 of file CCommon.java.
References com.github.aptd.simulation.common.CCommon.LANGUAGE.
languagelabel()
static String com.github.aptd.simulation.common.CCommon.languagelabel (final Class<?> p_class, final String p_label) static private
Parameters
p_class class for static calls
p_label label name of the object
Returns
label name
Definition at line 223 of file CCommon.java.
Referenced by com.github.aptd.simulation.common.CCommon.languagestring().
languages()
static String [] com.github.aptd.simulation.common.CCommon.languages () static
Returns
list of language pattern
Definition at line 96 of file CCommon.java.
languagestring() [1/2]
static <T> String com.github.aptd.simulation.common.CCommon.languagestring (final T p_source, final String p_label, final Object... p_parameter) static
Parameters
p_source any object
p_label label name
p_parameter parameter
Returns
translated string
Template Parameters
T object type
Definition at line 191 of file CCommon.java.
Referenced by com.github.aptd.simulation.core.runtime.ERuntime.get(), com.github.aptd.simulation.CMain.main(), and com.github.aptd.simulation.elements.linearprogram.CCombinedSolver.typespecific().
languagestring() [2/2]
static String com.github.aptd.simulation.common.CCommon.languagestring (final Class<?> p_class, final String p_label, final Object... p_parameter) static
Parameters
p_class class for static calls
p_label label name of the object
p_parameter object array with substitutions
Returns
resource string
Definition at line 204 of file CCommon.java.
References com.github.aptd.simulation.common.CCommon.languagelabel().
logger()
static Logger com.github.aptd.simulation.common.CCommon.logger (final Class<?> p_class) static
Parameters
p_class class type
Returns
logger
Definition at line 86 of file CCommon.java.
resourceurl() [1/3]
static URL com.github.aptd.simulation.common.CCommon.resourceurl () static
Returns
URL of file or null
Definition at line 143 of file CCommon.java.
Referenced by com.github.aptd.simulation.common.CCommon.resourceurl().
resourceurl() [2/3]
static URL com.github.aptd.simulation.common.CCommon.resourceurl (final String p_file) throws URISyntaxException, MalformedURLException static
Jar file
Parameters
p_file file
Returns
URL of file or null
Exceptions
URISyntaxException thrown on syntax error
MalformedURLException thrown on malformat
Definition at line 157 of file CCommon.java.
References com.github.aptd.simulation.common.CCommon.resourceurl().
resourceurl() [3/3]
static URL com.github.aptd.simulation.common.CCommon.resourceurl (final File p_file) throws URISyntaxException, MalformedURLException static private
Jar file
Parameters
p_file file relative to the CMain
Returns
URL of file or null
Exceptions
URISyntaxException is thrown on URI errors
MalformedURLException is thrown on malformat
Definition at line 171 of file CCommon.java.
Member Data Documentation
LANGUAGE
final ResourceBundle com.github.aptd.simulation.common.CCommon.LANGUAGE static private
Initial value:
= ResourceBundle.getBundle(
        MessageFormat.format( "{0}.{1}", PACKAGEROOT, "language" ),
        Locale.getDefault(),
        new CUTF8Control()
    )
Definition at line 58 of file CCommon.java.
Referenced by com.github.aptd.simulation.common.CCommon.languagebundle().
LOGGER
final Logger com.github.aptd.simulation.common.CCommon.LOGGER = CCommon.logger(CCommon.class) static private
Definition at line 54 of file CCommon.java.
PACKAGEROOT
final String com.github.aptd.simulation.common.CCommon.PACKAGEROOT = "com.github.aptd.simulation" static
Definition at line 50 of file CCommon.java.
Referenced by com.github.aptd.simulation.ui.CHTTPServer.CHTTPServer(), com.github.aptd.simulation.ui.CRestApi.CRestApi(), com.github.aptd.simulation.TestCLanguageLabels.CJavaVistor.label(), and com.github.aptd.simulation.TestCLanguageLabels.testResourceString().
PROPERTIES
final ResourceBundle com.github.aptd.simulation.common.CCommon.PROPERTIES static private
Initial value:
= ResourceBundle.getBundle(
        MessageFormat.format( "{0}.{1}", PACKAGEROOT, "configuration" ),
        Locale.getDefault(),
        new CUTF8Control()
    )
Definition at line 66 of file CCommon.java.
Referenced by com.github.aptd.simulation.common.CCommon.configuration().