Asimov - Agentbased Passenger & Train Delay Simulation: com.github.aptd.simulation.elements.passenger.CPassenger Class Reference
com.github.aptd.simulation.elements.passenger.CPassenger Class Reference
passenger
Classes
class CGenerator
generator
class CItineraryEntry
a part of a passenger's itinerary train, track and station information is represented via Strings rather than object references for two reasons:
Protected Member Functions
Instant determinenextstatechange ()
final Stream< ILiteral > individualliteral (final Stream< IElement<?>> p_object)
boolean updatecontinuous (final Duration p_elapsed)
boolean updatestate ()
void writeState (final JsonGenerator p_generator) throws IOException
Protected Member Functions inherited from com.github.aptd.simulation.elements.IStatefulElement< N extends IElement<?>
IStatefulElement (final IAgentConfiguration< N > p_configuration, final String p_functor, final String p_id, final ITime p_time)
ctor
final synchronized void continuousupdate ()
abstract Instant determinenextstatechange ()
calculates the time instant at which the next (internal) state change happens unless the agent is interrupted by input.
final void flushOutput ()
final void output (final IMessage p_message)
final synchronized void transition ()
abstract boolean updatecontinuous (final Duration p_elapsed)
apart from updatestate(), this is the only place where continuous state shall be changed; discrete state must not be changed here
abstract boolean updatestate ()
this is the ONLY place where the discrete state shall be touched.
abstract void writeState (final JsonGenerator p_generator) throws IOException
every implementing class must provide this method that serializes the current state of the object into the provided JsonGenerator (fasterxml-core)
Protected Member Functions inherited from com.github.aptd.simulation.elements.IBaseElement< N >
IBaseElement (final IAgentConfiguration< N > p_configuration, final String p_functor, final String p_id, final ITime p_time)
ctor
abstract Stream< ILiteral > individualliteral (final Stream< IElement<?>> p_object)
define object literal addons
Private Member Functions
CPassenger (final IAgentConfiguration< IPassenger<?>> p_configuration, final String p_id, final ITime p_time, final Stream< CItineraryEntry > p_itinerary, final double p_speedatstation)
ctor
boolean handledoormessage ()
boolean handleplatformmessages ()
Private Attributes
String m_destination
the passenger's destination (station)
double m_distancetonextplatform = 150.0
the distance from the previous to the next platform (meters)
double m_distancewalked
distance already walked to the next platform (meters) (continuous state variable for MOVING_THROUGH_STATION)
IDoor<?> m_door
the door currently being used
double m_dooruse
how long the passenger is already using the door (seconds) (continuous state variable for ENTERING_TRAIN and LEAVING_TRAIN)
double m_entranceduration = 5.0
how long the passenger needs to enter a train when it's their turn (seconds)
double m_exitduration = 5.0
how long the passenger needs to leave a train when it's their turn (seconds)
int m_itindex
index into the itinerary
List< CItineraryEntry > m_itinerary
how the passenger currently intends to get from their origin to their destination
String m_origin
the passenger's origin (station) from where they begin their journey
double m_speedatstation = 1.5
the passenger's individual speed at the station (moving to another platform) (meters per second)
EPassengerState m_state = EPassengerState.MOVING_THROUGH_STATION
qualitative state of the passenger
IStation<?> m_station
station that the passenger is currently at (may be null, especially if they are on a train instead)
ITrain<?> m_train
train that the passenger is currently on (may be null, especially if they are at a station instead)
Static Private Attributes
static final String FUNCTOR = "passenger"
literal functor
static final long serialVersionUID = -2850497411803927233L
serial id
Additional Inherited Members
Public Member Functions inherited from com.github.aptd.simulation.elements.IStatefulElement< N extends IElement<?>
final Instant nextstatechange ()
synchronized Stream< IMessage > output ()
Public Member Functions inherited from com.github.aptd.simulation.elements.IBaseElement< N >
N call () throws Exception
final IElement< N > environment (final IEnvironment< N, ?> p_environment)
final boolean equals (final Object p_object)
final int hashCode ()
final String id ()
boolean imminent ()
whether the element has a scheduled activation at the current time
N input (final IMessage p_message)
store an incoming message to be processed
final Stream< ILiteral > literal (final IElement<?>... p_object)
final Stream< ILiteral > literal (final Stream< IElement<?>> p_object)
Instant nextactivation ()
Stream< IMessage > output ()
get outgoing messages.
String toString ()
Static Public Member Functions inherited from com.github.aptd.simulation.elements.IStatefulElement< N extends IElement<?>
static final String getDefaultAsl (final String p_name)
generates a default asl script string calling "state/transition" upon "!activate", and greeting upon initialisation
Protected Attributes inherited from com.github.aptd.simulation.elements.IStatefulElement< N extends IElement<?>
Instant m_lastcontinuousupdate
Instant m_laststatechange
Instant m_nextstatechange
Protected Attributes inherited from com.github.aptd.simulation.elements.IBaseElement< N >
final String m_id
agent name
final ListMultimap< EMessageType, IMessage > m_input
set of inputs to be processed
Instant m_nextactivation
simulated time at which the agent will become active again on its own
final ITime m_time
reference to time
Detailed Description
Definition at line 60 of file CPassenger.java.
Constructor & Destructor Documentation
CPassenger()
com.github.aptd.simulation.elements.passenger.CPassenger.CPassenger (final IAgentConfiguration< IPassenger<?>> p_configuration, final String p_id, final ITime p_time, final Stream< CItineraryEntry > p_itinerary, final double p_speedatstation) private
Parameters
p_configuration agent configuration
p_id passenger identifier
p_time time reference
Definition at line 136 of file CPassenger.java.
References com.github.aptd.simulation.elements.passenger.CPassenger.determinenextstatechange(), com.github.aptd.simulation.elements.IBaseElement< N >.m_id, com.github.aptd.simulation.elements.IBaseElement< N >.m_nextactivation, and com.github.aptd.simulation.elements.IStatefulElement< N extends IElement<?>.m_nextstatechange.
Referenced by com.github.aptd.simulation.elements.passenger.CPassenger.CGenerator.generate().
Member Function Documentation
determinenextstatechange()
Instant com.github.aptd.simulation.elements.passenger.CPassenger.determinenextstatechange () protected
Definition at line 155 of file CPassenger.java.
References com.github.aptd.simulation.elements.IStatefulElement< N extends IElement<?>.m_lastcontinuousupdate.
Referenced by com.github.aptd.simulation.elements.passenger.CPassenger.CPassenger().
handledoormessage()
boolean com.github.aptd.simulation.elements.passenger.CPassenger.handledoormessage () private
Definition at line 237 of file CPassenger.java.
References com.github.aptd.simulation.core.messaging.EMessageType.DOOR_TO_PASSENGER_YOURTURN, com.github.aptd.simulation.elements.passenger.EPassengerState.ENTERING_TRAIN, com.github.aptd.simulation.elements.passenger.EPassengerState.IN_ENTRANCE_QUEUE, com.github.aptd.simulation.elements.passenger.EPassengerState.IN_EXIT_QUEUE, com.github.aptd.simulation.elements.passenger.EPassengerState.LEAVING_TRAIN, com.github.aptd.simulation.elements.IBaseElement< N >.m_id, com.github.aptd.simulation.elements.IBaseElement< N >.m_input, com.github.aptd.simulation.elements.passenger.CPassenger.m_state, com.github.aptd.simulation.elements.IStatefulElement< N extends IElement<?>.output(), com.github.aptd.simulation.core.messaging.EMessageType.PASSENGER_TO_PLATFORM_UNSUBSCRIBE, and com.github.aptd.simulation.core.messaging.EMessageType.PASSENGER_TO_TRAIN_UNSUBSCRIBE.
Referenced by com.github.aptd.simulation.elements.passenger.CPassenger.updatestate().
handleplatformmessages()
boolean com.github.aptd.simulation.elements.passenger.CPassenger.handleplatformmessages () private
Definition at line 261 of file CPassenger.java.
References com.github.aptd.simulation.elements.passenger.EPassengerState.IN_ENTRANCE_QUEUE, com.github.aptd.simulation.elements.IBaseElement< N >.m_id, com.github.aptd.simulation.elements.IBaseElement< N >.m_input, com.github.aptd.simulation.elements.passenger.EPassengerState.ON_PLATFORM_WAITING_FOR_TRAIN, com.github.aptd.simulation.elements.IStatefulElement< N extends IElement<?>.output(), com.github.aptd.simulation.core.messaging.EMessageType.PASSENGER_TO_DOOR_ENQUEUE_ENTRANCE, com.github.aptd.simulation.core.messaging.EMessageType.PLATFORM_TO_PASSENGER_TRAINARRIVED, and com.github.aptd.simulation.core.messaging.EMessageType.PLATFORM_TO_PASSENGER_TRAINDEPARTED.
Referenced by com.github.aptd.simulation.elements.passenger.CPassenger.updatestate().
individualliteral()
final Stream<ILiteral> com.github.aptd.simulation.elements.passenger.CPassenger.individualliteral (final Stream< IElement<?>> p_object) protected
Definition at line 148 of file CPassenger.java.
updatecontinuous()
boolean com.github.aptd.simulation.elements.passenger.CPassenger.updatecontinuous (final Duration p_elapsed) protected
Definition at line 294 of file CPassenger.java.
References com.github.aptd.simulation.elements.passenger.CPassenger.m_speedatstation.
updatestate()
boolean com.github.aptd.simulation.elements.passenger.CPassenger.updatestate () protected
Definition at line 180 of file CPassenger.java.
References com.github.aptd.simulation.core.time.ITime.current(), com.github.aptd.simulation.elements.passenger.CPassenger.handledoormessage(), com.github.aptd.simulation.elements.passenger.CPassenger.handleplatformmessages(), com.github.aptd.simulation.elements.passenger.EPassengerState.IDLE_AT_STATION, com.github.aptd.simulation.elements.passenger.EPassengerState.IN_EXIT_QUEUE, com.github.aptd.simulation.elements.IBaseElement< N >.m_id, com.github.aptd.simulation.elements.IBaseElement< N >.m_input, com.github.aptd.simulation.elements.IStatefulElement< N extends IElement<?>.m_nextstatechange, com.github.aptd.simulation.elements.IBaseElement< N >.m_time, com.github.aptd.simulation.elements.passenger.EPassengerState.MOVING_THROUGH_STATION, com.github.aptd.simulation.elements.passenger.EPassengerState.ON_PLATFORM_WAITING_FOR_TRAIN, com.github.aptd.simulation.elements.passenger.EPassengerState.ON_TRAIN, com.github.aptd.simulation.elements.IStatefulElement< N extends IElement<?>.output(), com.github.aptd.simulation.core.messaging.EMessageType.PASSENGER_TO_DOOR_ENQUEUE_EXIT, com.github.aptd.simulation.core.messaging.EMessageType.PASSENGER_TO_DOOR_FINISHED, com.github.aptd.simulation.core.messaging.EMessageType.PASSENGER_TO_PLATFORM_SUBSCRIBE, com.github.aptd.simulation.core.messaging.EMessageType.PASSENGER_TO_TRAIN_SUBSCRIBE, and com.github.aptd.simulation.core.messaging.EMessageType.TRAIN_TO_PASSENGER_ARRIVING.
writeState()
void com.github.aptd.simulation.elements.passenger.CPassenger.writeState (final JsonGenerator p_generator) throws IOException protected
Definition at line 312 of file CPassenger.java.
Member Data Documentation
FUNCTOR
final String com.github.aptd.simulation.elements.passenger.CPassenger.FUNCTOR = "passenger" static private
Definition at line 69 of file CPassenger.java.
m_destination
String com.github.aptd.simulation.elements.passenger.CPassenger.m_destination private
Definition at line 91 of file CPassenger.java.
m_distancetonextplatform
double com.github.aptd.simulation.elements.passenger.CPassenger.m_distancetonextplatform = 150.0 private
Definition at line 107 of file CPassenger.java.
m_distancewalked
double com.github.aptd.simulation.elements.passenger.CPassenger.m_distancewalked private
Definition at line 111 of file CPassenger.java.
m_door
IDoor<?> com.github.aptd.simulation.elements.passenger.CPassenger.m_door private
Definition at line 127 of file CPassenger.java.
m_dooruse
double com.github.aptd.simulation.elements.passenger.CPassenger.m_dooruse private
Definition at line 123 of file CPassenger.java.
m_entranceduration
double com.github.aptd.simulation.elements.passenger.CPassenger.m_entranceduration = 5.0 private
Definition at line 115 of file CPassenger.java.
m_exitduration
double com.github.aptd.simulation.elements.passenger.CPassenger.m_exitduration = 5.0 private
Definition at line 119 of file CPassenger.java.
m_itindex
int com.github.aptd.simulation.elements.passenger.CPassenger.m_itindex private
Definition at line 99 of file CPassenger.java.
m_itinerary
List<CItineraryEntry> com.github.aptd.simulation.elements.passenger.CPassenger.m_itinerary private
Definition at line 95 of file CPassenger.java.
m_origin
String com.github.aptd.simulation.elements.passenger.CPassenger.m_origin private
Definition at line 87 of file CPassenger.java.
m_speedatstation
double com.github.aptd.simulation.elements.passenger.CPassenger.m_speedatstation = 1.5 private
Definition at line 103 of file CPassenger.java.
Referenced by com.github.aptd.simulation.elements.passenger.CPassenger.updatecontinuous().
m_state
EPassengerState com.github.aptd.simulation.elements.passenger.CPassenger.m_state = EPassengerState.MOVING_THROUGH_STATION private
Definition at line 74 of file CPassenger.java.
Referenced by com.github.aptd.simulation.elements.passenger.CPassenger.handledoormessage().
m_station
IStation<?> com.github.aptd.simulation.elements.passenger.CPassenger.m_station private
Definition at line 78 of file CPassenger.java.
m_train
ITrain<?> com.github.aptd.simulation.elements.passenger.CPassenger.m_train private
Definition at line 82 of file CPassenger.java.
serialVersionUID
final long com.github.aptd.simulation.elements.passenger.CPassenger.serialVersionUID = -2850497411803927233L static private
Definition at line 65 of file CPassenger.java.