Asimov - Agentbased Passenger & Train Delay Simulation: com.github.aptd.simulation.elements.IElement< T extends IAgent<?> Interface Template Reference
com.github.aptd.simulation.elements.IElement< T extends IAgent<?> Interface Template Reference
any object interface
Classes
interface IGenerator
generator interface
Public Member Functions
IElement< T > environment (final IEnvironment< T, ?> p_environment)
changes the environment of the agent
String id ()
name of the object
boolean imminent ()
T input (IMessage p_message)
Instant nextactivation ()
Stream< IMessage > output ()
get pending output messages
Public Member Functions inherited from com.github.aptd.simulation.elements.IPerceiveable
Stream< ILiteral > literal (final IElement<?>... p_object)
get literal of the object
Stream< ILiteral > literal (final Stream< IElement<?>> p_object)
get literal of the object
Detailed Description
Template Parameters
T domain specific type
Definition at line 40 of file IElement.java.
Member Function Documentation
environment()
IElement<T> com.github.aptd.simulation.elements.IElement< T extends IAgent<?>.environment (final IEnvironment< T, ?> p_environment)
Parameters
p_environment environment
Returns
self reference
Todo:
should be moved - incomplete
id()
String com.github.aptd.simulation.elements.IElement< T extends IAgent<?>.id ()
Returns
string name
Referenced by com.github.aptd.simulation.elements.passenger.CPassengerSource.generatepassenger(), com.github.aptd.simulation.elements.graph.TestCNetwork.networkbuild(), com.github.aptd.simulation.elements.train.CDoor.passengerfinished(), com.github.aptd.simulation.datamodel.CXMLReader.platform(), com.github.aptd.simulation.datamodel.CXMLReader.station(), com.github.aptd.simulation.datamodel.CXMLReader.train(), com.github.aptd.simulation.elements.graph.network.local.CPlatform.updatestate(), and com.github.aptd.simulation.core.messaging.local.CMessage.write().
imminent()
boolean com.github.aptd.simulation.elements.IElement< T extends IAgent<?>.imminent ()
Referenced by com.github.aptd.simulation.core.messaging.local.CMessenger.call().
input()
T com.github.aptd.simulation.elements.IElement< T extends IAgent<?>.input (IMessage p_message)
nextactivation()
Instant com.github.aptd.simulation.elements.IElement< T extends IAgent<?>.nextactivation ()
Referenced by com.github.aptd.simulation.core.time.local.CJumpTime.call().
output()
Stream<IMessage> com.github.aptd.simulation.elements.IElement< T extends IAgent<?>.output ()
Returns
Stream of messages
Referenced by com.github.aptd.simulation.core.messaging.local.CMessenger.call().