Asimov - Agentbased Passenger & Train Delay Simulation: com.github.aptd.simulation.elements.train.CDoor Class Reference
com.github.aptd.simulation.elements.train.CDoor Class Reference
door class
Classes
class CGenerator
generator
Protected Member Functions
CDoor (final IAgentConfiguration< IDoor<?>> p_configuration, final String p_id, final ITime p_time, final String p_train, final double p_width)
ctor
Instant determinenextstatechange ()
Stream< ILiteral > individualliteral (final Stream< IElement<?>> p_object)
boolean updatecontinuous (final Duration p_elapsed)
boolean updatestate ()
void writeState (final JsonGenerator p_generator) throws IOException
Protected Member Functions inherited from com.github.aptd.simulation.elements.IStatefulElement< N extends IElement<?>
IStatefulElement (final IAgentConfiguration< N > p_configuration, final String p_functor, final String p_id, final ITime p_time)
ctor
final synchronized void continuousupdate ()
abstract Instant determinenextstatechange ()
calculates the time instant at which the next (internal) state change happens unless the agent is interrupted by input.
final void flushOutput ()
final void output (final IMessage p_message)
final synchronized void transition ()
abstract boolean updatecontinuous (final Duration p_elapsed)
apart from updatestate(), this is the only place where continuous state shall be changed; discrete state must not be changed here
abstract boolean updatestate ()
this is the ONLY place where the discrete state shall be touched.
abstract void writeState (final JsonGenerator p_generator) throws IOException
every implementing class must provide this method that serializes the current state of the object into the provided JsonGenerator (fasterxml-core)
Protected Member Functions inherited from com.github.aptd.simulation.elements.IBaseElement< N >
IBaseElement (final IAgentConfiguration< N > p_configuration, final String p_functor, final String p_id, final ITime p_time)
ctor
abstract Stream< ILiteral > individualliteral (final Stream< IElement<?>> p_object)
define object literal addons
Private Member Functions
void debugPrintState ()
void handletrainmessages ()
void lockifrequested (final List< IMessage > p_lockrequests)
void nextpassengerifpossible (final Queue< IPassenger<?>> p_queue)
void passengerfinished (final IMessage p_message)
void timedstatechangeifnecessary (final Queue< IPassenger<?>> p_queue)
void unlockifrequested (final List< IMessage > p_unlockrequests)
Private Attributes
double m_closingspeed = 0.4
how fast the door closes (meters per second)
Queue< IPassenger<?> > m_entryqueue = new LinkedList<>()
Queue< IPassenger<?> > m_exitqueue = new LinkedList<>()
double m_freetime
for how long the door has not been used (seconds)
double m_minfreetimetoclose = 10
for how long the door must have been unused before it can close (seconds)
double m_openingspeed = 0.4
how fast the door opens (meters per second)
double m_openwidth
how far the door is actually open at the moment (min 0.0, max m_width), in between in OPENING and CLOSING states (meters)
String m_platformid
agent ID of the platform the door is currently at
EDoorState m_state = EDoorState.CLOSED_RELEASED
String m_stationid
agent ID of the station the door is currently at
String m_train
the train agent this door belongs to
double m_width
the total width of the door (when fully open) (meters)
Static Private Attributes
static final String FUNCTOR = "door"
literal functor
static final long serialVersionUID = -5363342346164082638L
serial id
Additional Inherited Members
Public Member Functions inherited from com.github.aptd.simulation.elements.IStatefulElement< N extends IElement<?>
final Instant nextstatechange ()
synchronized Stream< IMessage > output ()
Public Member Functions inherited from com.github.aptd.simulation.elements.IBaseElement< N >
N call () throws Exception
final IElement< N > environment (final IEnvironment< N, ?> p_environment)
final boolean equals (final Object p_object)
final int hashCode ()
final String id ()
boolean imminent ()
whether the element has a scheduled activation at the current time
N input (final IMessage p_message)
store an incoming message to be processed
final Stream< ILiteral > literal (final IElement<?>... p_object)
final Stream< ILiteral > literal (final Stream< IElement<?>> p_object)
Instant nextactivation ()
Stream< IMessage > output ()
get outgoing messages.
String toString ()
Static Public Member Functions inherited from com.github.aptd.simulation.elements.IStatefulElement< N extends IElement<?>
static final String getDefaultAsl (final String p_name)
generates a default asl script string calling "state/transition" upon "!activate", and greeting upon initialisation
Protected Attributes inherited from com.github.aptd.simulation.elements.IStatefulElement< N extends IElement<?>
Instant m_lastcontinuousupdate
Instant m_laststatechange
Instant m_nextstatechange
Protected Attributes inherited from com.github.aptd.simulation.elements.IBaseElement< N >
final String m_id
agent name
final ListMultimap< EMessageType, IMessage > m_input
set of inputs to be processed
Instant m_nextactivation
simulated time at which the agent will become active again on its own
final ITime m_time
reference to time
Detailed Description
Definition at line 55 of file CDoor.java.
Constructor & Destructor Documentation
CDoor()
com.github.aptd.simulation.elements.train.CDoor.CDoor (final IAgentConfiguration< IDoor<?>> p_configuration, final String p_id, final ITime p_time, final String p_train, final double p_width) protected
Parameters
p_configuration agent configuration
p_id ...
p_time time reference
p_train train id
Definition at line 117 of file CDoor.java.
References com.github.aptd.simulation.elements.train.CDoor.determinenextstatechange(), and com.github.aptd.simulation.elements.IStatefulElement< N extends IElement<?>.m_nextstatechange.
Referenced by com.github.aptd.simulation.elements.train.CDoor.CGenerator.generate().
Member Function Documentation
debugPrintState()
void com.github.aptd.simulation.elements.train.CDoor.debugPrintState () private
Definition at line 200 of file CDoor.java.
References com.github.aptd.simulation.elements.IBaseElement< N >.m_id.
determinenextstatechange()
Instant com.github.aptd.simulation.elements.train.CDoor.determinenextstatechange () protected
Definition at line 132 of file CDoor.java.
References com.github.aptd.simulation.elements.IStatefulElement< N extends IElement<?>.m_lastcontinuousupdate.
Referenced by com.github.aptd.simulation.elements.train.CDoor.CDoor().
handletrainmessages()
void com.github.aptd.simulation.elements.train.CDoor.handletrainmessages () private
Definition at line 205 of file CDoor.java.
References com.github.aptd.simulation.elements.train.EDoorState.CLOSED_LOCKED, com.github.aptd.simulation.elements.train.CDoor.lockifrequested(), com.github.aptd.simulation.elements.IBaseElement< N >.m_id, com.github.aptd.simulation.elements.IBaseElement< N >.m_input, com.github.aptd.simulation.core.messaging.EMessageType.TRAIN_TO_DOOR_DEPARTING, com.github.aptd.simulation.core.messaging.EMessageType.TRAIN_TO_DOOR_LOCK, com.github.aptd.simulation.core.messaging.EMessageType.TRAIN_TO_DOOR_UNLOCK, and com.github.aptd.simulation.elements.train.CDoor.unlockifrequested().
Referenced by com.github.aptd.simulation.elements.train.CDoor.updatestate().
individualliteral()
Stream<ILiteral> com.github.aptd.simulation.elements.train.CDoor.individualliteral (final Stream< IElement<?>> p_object) protected
Definition at line 126 of file CDoor.java.
lockifrequested()
void com.github.aptd.simulation.elements.train.CDoor.lockifrequested (final List< IMessage > p_lockrequests) private
Definition at line 271 of file CDoor.java.
References com.github.aptd.simulation.elements.train.EDoorState.CLOSED_LOCKED, com.github.aptd.simulation.elements.train.EDoorState.CLOSING_LOCKED, com.github.aptd.simulation.core.messaging.EMessageType.DOOR_TO_TRAIN_CLOSED_LOCKED, com.github.aptd.simulation.elements.IBaseElement< N >.m_id, com.github.aptd.simulation.elements.train.EDoorState.OPEN_BUSY_SHALL_CLOSE, com.github.aptd.simulation.elements.train.EDoorState.OPEN_FREE_SHALL_CLOSE, com.github.aptd.simulation.elements.train.EDoorState.OPENING_SHALL_CLOSE, and com.github.aptd.simulation.elements.IStatefulElement< N extends IElement<?>.output().
Referenced by com.github.aptd.simulation.elements.train.CDoor.handletrainmessages().
nextpassengerifpossible()
void com.github.aptd.simulation.elements.train.CDoor.nextpassengerifpossible (final Queue< IPassenger<?>> p_queue) private
Definition at line 365 of file CDoor.java.
References com.github.aptd.simulation.core.messaging.EMessageType.DOOR_TO_PASSENGER_YOURTURN, com.github.aptd.simulation.elements.train.CDoor.m_platformid, com.github.aptd.simulation.elements.train.CDoor.m_stationid, com.github.aptd.simulation.elements.train.EDoorState.OPEN_BUSY, com.github.aptd.simulation.elements.train.EDoorState.OPEN_BUSY_SHALL_CLOSE, com.github.aptd.simulation.elements.train.EDoorState.OPENING, com.github.aptd.simulation.elements.train.EDoorState.OPENING_SHALL_CLOSE, and com.github.aptd.simulation.elements.IStatefulElement< N extends IElement<?>.output().
Referenced by com.github.aptd.simulation.elements.train.CDoor.updatestate().
passengerfinished()
void com.github.aptd.simulation.elements.train.CDoor.passengerfinished (final IMessage p_message) private
Definition at line 344 of file CDoor.java.
References com.github.aptd.simulation.elements.IElement< T extends IAgent<?>.id(), com.github.aptd.simulation.elements.IBaseElement< N >.m_id, com.github.aptd.simulation.elements.train.EDoorState.OPEN_FREE, com.github.aptd.simulation.elements.train.EDoorState.OPEN_FREE_SHALL_CLOSE, and com.github.aptd.simulation.core.messaging.IMessage.sender().
Referenced by com.github.aptd.simulation.elements.train.CDoor.updatestate().
timedstatechangeifnecessary()
void com.github.aptd.simulation.elements.train.CDoor.timedstatechangeifnecessary (final Queue< IPassenger<?>> p_queue) private
Definition at line 308 of file CDoor.java.
References com.github.aptd.simulation.elements.train.EDoorState.CLOSED_LOCKED, com.github.aptd.simulation.elements.train.EDoorState.CLOSED_RELEASED, com.github.aptd.simulation.elements.train.EDoorState.CLOSING_LOCKED, com.github.aptd.simulation.core.time.ITime.current(), com.github.aptd.simulation.core.messaging.EMessageType.DOOR_TO_TRAIN_CLOSED_LOCKED, com.github.aptd.simulation.elements.IStatefulElement< N extends IElement<?>.m_nextstatechange, com.github.aptd.simulation.elements.IBaseElement< N >.m_time, com.github.aptd.simulation.elements.train.CDoor.m_width, com.github.aptd.simulation.elements.train.EDoorState.OPEN_CLOSEABLE, com.github.aptd.simulation.elements.train.EDoorState.OPEN_FREE, com.github.aptd.simulation.elements.train.EDoorState.OPEN_FREE_SHALL_CLOSE, com.github.aptd.simulation.elements.train.EDoorState.OPENING, and com.github.aptd.simulation.elements.IStatefulElement< N extends IElement<?>.output().
Referenced by com.github.aptd.simulation.elements.train.CDoor.updatestate().
unlockifrequested()
void com.github.aptd.simulation.elements.train.CDoor.unlockifrequested (final List< IMessage > p_unlockrequests) private
Definition at line 233 of file CDoor.java.
References com.github.aptd.simulation.elements.train.EDoorState.CLOSED_RELEASED, com.github.aptd.simulation.elements.train.EDoorState.CLOSING, com.github.aptd.simulation.core.time.ITime.current(), com.github.aptd.simulation.elements.IBaseElement< N >.m_id, com.github.aptd.simulation.elements.IBaseElement< N >.m_time, com.github.aptd.simulation.elements.train.EDoorState.OPEN_BUSY, com.github.aptd.simulation.elements.train.EDoorState.OPEN_FREE, and com.github.aptd.simulation.elements.train.EDoorState.OPENING.
Referenced by com.github.aptd.simulation.elements.train.CDoor.handletrainmessages().
updatecontinuous()
boolean com.github.aptd.simulation.elements.train.CDoor.updatecontinuous (final Duration p_elapsed) protected
Definition at line 394 of file CDoor.java.
References com.github.aptd.simulation.elements.train.CDoor.m_closingspeed, and com.github.aptd.simulation.elements.train.CDoor.m_openingspeed.
updatestate()
boolean com.github.aptd.simulation.elements.train.CDoor.updatestate () protected
Definition at line 166 of file CDoor.java.
References com.github.aptd.simulation.elements.train.CDoor.handletrainmessages(), com.github.aptd.simulation.elements.train.CDoor.m_entryqueue, com.github.aptd.simulation.elements.train.CDoor.m_exitqueue, com.github.aptd.simulation.elements.IBaseElement< N >.m_id, com.github.aptd.simulation.elements.IBaseElement< N >.m_input, com.github.aptd.simulation.elements.train.CDoor.m_state, com.github.aptd.simulation.elements.train.CDoor.nextpassengerifpossible(), com.github.aptd.simulation.core.messaging.EMessageType.PASSENGER_TO_DOOR_ENQUEUE_ENTRANCE, com.github.aptd.simulation.core.messaging.EMessageType.PASSENGER_TO_DOOR_ENQUEUE_EXIT, com.github.aptd.simulation.core.messaging.EMessageType.PASSENGER_TO_DOOR_FINISHED, com.github.aptd.simulation.elements.train.CDoor.passengerfinished(), and com.github.aptd.simulation.elements.train.CDoor.timedstatechangeifnecessary().
writeState()
void com.github.aptd.simulation.elements.train.CDoor.writeState (final JsonGenerator p_generator) throws IOException protected
Definition at line 418 of file CDoor.java.
Member Data Documentation
FUNCTOR
final String com.github.aptd.simulation.elements.train.CDoor.FUNCTOR = "door" static private
Definition at line 65 of file CDoor.java.
m_closingspeed
double com.github.aptd.simulation.elements.train.CDoor.m_closingspeed = 0.4 private
Definition at line 99 of file CDoor.java.
Referenced by com.github.aptd.simulation.elements.train.CDoor.updatecontinuous().
m_entryqueue
Queue<IPassenger<?> > com.github.aptd.simulation.elements.train.CDoor.m_entryqueue = new LinkedList<>() private
Definition at line 68 of file CDoor.java.
Referenced by com.github.aptd.simulation.elements.train.CDoor.updatestate().
m_exitqueue
Queue<IPassenger<?> > com.github.aptd.simulation.elements.train.CDoor.m_exitqueue = new LinkedList<>() private
Definition at line 67 of file CDoor.java.
Referenced by com.github.aptd.simulation.elements.train.CDoor.updatestate().
m_freetime
double com.github.aptd.simulation.elements.train.CDoor.m_freetime private
Definition at line 91 of file CDoor.java.
m_minfreetimetoclose
double com.github.aptd.simulation.elements.train.CDoor.m_minfreetimetoclose = 10 private
Definition at line 87 of file CDoor.java.
m_openingspeed
double com.github.aptd.simulation.elements.train.CDoor.m_openingspeed = 0.4 private
Definition at line 95 of file CDoor.java.
Referenced by com.github.aptd.simulation.elements.train.CDoor.updatecontinuous().
m_openwidth
double com.github.aptd.simulation.elements.train.CDoor.m_openwidth private
Definition at line 83 of file CDoor.java.
m_platformid
String com.github.aptd.simulation.elements.train.CDoor.m_platformid private
Definition at line 107 of file CDoor.java.
Referenced by com.github.aptd.simulation.elements.train.CDoor.nextpassengerifpossible().
m_state
EDoorState com.github.aptd.simulation.elements.train.CDoor.m_state = EDoorState.CLOSED_RELEASED private
Definition at line 75 of file CDoor.java.
Referenced by com.github.aptd.simulation.elements.train.CDoor.updatestate().
m_stationid
String com.github.aptd.simulation.elements.train.CDoor.m_stationid private
Definition at line 103 of file CDoor.java.
Referenced by com.github.aptd.simulation.elements.train.CDoor.nextpassengerifpossible().
m_train
String com.github.aptd.simulation.elements.train.CDoor.m_train private
Definition at line 73 of file CDoor.java.
m_width
double com.github.aptd.simulation.elements.train.CDoor.m_width private
Definition at line 79 of file CDoor.java.
Referenced by com.github.aptd.simulation.elements.train.CDoor.timedstatechangeifnecessary().
serialVersionUID
final long com.github.aptd.simulation.elements.train.CDoor.serialVersionUID = -5363342346164082638L static private
Definition at line 61 of file CDoor.java.