Asimov - Agentbased Passenger & Train Delay Simulation: com.github.aptd.simulation.elements.grid.local.CJPSPlusStatic Class Reference
com.github.aptd.simulation.elements.grid.local.CJPSPlusStatic Class Reference
JPS+ algorithm with static chaching.
Classes
class CCompareJumpPoint
class to compare two jump-points
class CJumpPoint
jump-point with a static class "static" means that the class can exists without the CJPSPlus object "final" no inheritance can be create
Public Member Functions
final double estimatedtime (final Stream< DoubleMatrix1D > p_route, final double p_speed)
calculated the estimated time to move the path
final IRouting initialize (final ObjectMatrix2D p_objects)
runs the initialization process from the environment
final List< DoubleMatrix1D > route (final ObjectMatrix2D p_objects, final DoubleMatrix1D p_currentposition, final DoubleMatrix1D p_targetposition)
routing algorithm
Private Member Functions
void addsuccessors (final DoubleMatrix1D p_nextjumpnode, final ArrayList< DoubleMatrix1D > p_closedlist, final Set< CJumpPoint > p_openlist, final CJumpPoint p_curnode, final DoubleMatrix1D p_target)
Validated successors are added to open list.
void calculateScore (final CJumpPoint p_jumpnode, final DoubleMatrix1D p_target)
Calculates the given node's score using the Manhattan distance formula.
DoubleMatrix1D diagjump (final double p_nextrow, final double p_nextcolumn, final DoubleMatrix1D p_nextnode, final DoubleMatrix1D p_target, final double p_row, final double p_col, final ObjectMatrix2D p_objects)
In order to identify diagonal jump point.
boolean diagonal (final double p_nextrow, final double p_nextcolumn, final double p_row, final double p_col, final double p_hzon, final double p_ver, final ObjectMatrix2D p_objects)
Helper function to identify diagonal jump point.
boolean horizontal (final double p_nextrow, final double p_nextcol, final double p_row, final ObjectMatrix2D p_objects, final double p_value)
Helper function to identify horizontal jump point.
boolean isNotCoordinate (final ObjectMatrix2D p_objects, final double p_row, final double p_column)
To check any point is in the grid environment or out of environment.
boolean isNotNeighbour (final ObjectMatrix2D p_objects, final double p_row, final double p_column, final ArrayList< DoubleMatrix1D > p_closedlist)
Finds the non valid successors of any grid.
boolean isOccupied (final ObjectMatrix2D p_objects, final double p_row, final double p_column)
To check any point in the grid environment is free or occupied.
DoubleMatrix1D jump (final DoubleMatrix1D p_curnode, final DoubleMatrix1D p_target, final double p_row, final double p_col, final ObjectMatrix2D p_objects)
In order to identify individual jump point successors heading in a given direction (run recursively until find a jump point or failure)
void successors (final ObjectMatrix2D p_objects, final CJumpPoint p_curnode, final DoubleMatrix1D p_target, final ArrayList< DoubleMatrix1D > p_closedlist, final Set< CJumpPoint > p_openlist)
individual jump point successors are identified
boolean vertical (final double p_nextrow, final double p_nextcol, final double p_col, final ObjectMatrix2D p_objects, final double p_value)
Helper function to identify vertical jump point.
Detailed Description
Todo:
refactory & clean-up execution with speed-up
create a unit-test
See also
http://www.gdcvault.com/play/1022094/JPS-Over-100x-Faster-than
Definition at line 50 of file CJPSPlusStatic.java.
Member Function Documentation
addsuccessors()
void com.github.aptd.simulation.elements.grid.local.CJPSPlusStatic.addsuccessors (final DoubleMatrix1D p_nextjumpnode, final ArrayList< DoubleMatrix1D > p_closedlist, final Set< CJumpPoint > p_openlist, final CJumpPoint p_curnode, final DoubleMatrix1D p_target) private
Parameters
p_nextjumpnode successors that need to be validated
p_closedlist the list of coordinate that already explored
p_openlist the set of CJumpPoint that will be explored
p_curnode the current node to search for successors
p_target the goal node
Definition at line 150 of file CJPSPlusStatic.java.
References com.github.aptd.simulation.elements.grid.local.CJPSPlusStatic.calculateScore(), com.github.aptd.simulation.elements.grid.local.CJPSPlusStatic.CJumpPoint.coordinate(), and com.github.aptd.simulation.elements.grid.local.CJPSPlusStatic.CJumpPoint.fscore().
Referenced by com.github.aptd.simulation.elements.grid.local.CJPSPlusStatic.successors().
calculateScore()
void com.github.aptd.simulation.elements.grid.local.CJPSPlusStatic.calculateScore (final CJumpPoint p_jumpnode, final DoubleMatrix1D p_target) private
Parameters
p_jumpnode The node to calculate
p_target the target node
Definition at line 321 of file CJPSPlusStatic.java.
References com.github.aptd.simulation.elements.grid.local.CJPSPlusStatic.CJumpPoint.coordinate(), com.github.aptd.simulation.elements.grid.local.CJPSPlusStatic.CJumpPoint.gscore(), com.github.aptd.simulation.elements.grid.local.CJPSPlusStatic.CJumpPoint.hscore(), and com.github.aptd.simulation.elements.grid.local.CJPSPlusStatic.CJumpPoint.parent().
Referenced by com.github.aptd.simulation.elements.grid.local.CJPSPlusStatic.addsuccessors().
diagjump()
DoubleMatrix1D com.github.aptd.simulation.elements.grid.local.CJPSPlusStatic.diagjump (final double p_nextrow, final double p_nextcolumn, final DoubleMatrix1D p_nextnode, final DoubleMatrix1D p_target, final double p_row, final double p_col, final ObjectMatrix2D p_objects) private
Parameters
p_nextrow row of the next node to search for
p_nextcolumn column of the next node to search for
p_nextnode next node
p_target the goal node
p_row to increase or decrease row by adding p_row
p_col to increase or decrease column by adding p_col
p_objects snapshot of the environment
Returns
diagonal jump point
Definition at line 217 of file CJPSPlusStatic.java.
References com.github.aptd.simulation.elements.grid.local.CJPSPlusStatic.diagonal(), and com.github.aptd.simulation.elements.grid.local.CJPSPlusStatic.jump().
Referenced by com.github.aptd.simulation.elements.grid.local.CJPSPlusStatic.jump().
diagonal()
boolean com.github.aptd.simulation.elements.grid.local.CJPSPlusStatic.diagonal (final double p_nextrow, final double p_nextcolumn, final double p_row, final double p_col, final double p_hzon, final double p_ver, final ObjectMatrix2D p_objects) private
Parameters
p_nextrow row of the next node to search for
p_nextcolumn column of the next node to search for
p_row to increase or decrease row by adding p_row
p_col to increase or decrease column by adding p_col
p_hzon top or bottom direction
p_ver left or right direction
p_objects Snapshot of the environment
Returns
true or false
Definition at line 241 of file CJPSPlusStatic.java.
References com.github.aptd.simulation.elements.grid.local.CJPSPlusStatic.isNotCoordinate(), and com.github.aptd.simulation.elements.grid.local.CJPSPlusStatic.isOccupied().
Referenced by com.github.aptd.simulation.elements.grid.local.CJPSPlusStatic.diagjump().
estimatedtime()
final double com.github.aptd.simulation.elements.grid.local.CJPSPlusStatic.estimatedtime (final Stream< DoubleMatrix1D > p_route, final double p_speed)
Parameters
p_route stream of route landmarks
p_speed estimated speed
Returns
estimated time
Implements com.github.aptd.simulation.elements.grid.IRouting.
Definition at line 96 of file CJPSPlusStatic.java.
horizontal()
boolean com.github.aptd.simulation.elements.grid.local.CJPSPlusStatic.horizontal (final double p_nextrow, final double p_nextcol, final double p_row, final ObjectMatrix2D p_objects, final double p_value) private
Parameters
p_nextrow row of the next node to search for
p_nextcol column of the next node to search for
p_row to increase or decrease row by adding p_row
p_objects Snapshot of the environment
p_value direction
Returns
true or false
Definition at line 257 of file CJPSPlusStatic.java.
References com.github.aptd.simulation.elements.grid.local.CJPSPlusStatic.isNotCoordinate(), and com.github.aptd.simulation.elements.grid.local.CJPSPlusStatic.isOccupied().
Referenced by com.github.aptd.simulation.elements.grid.local.CJPSPlusStatic.jump().
initialize()
final IRouting com.github.aptd.simulation.elements.grid.local.CJPSPlusStatic.initialize (final ObjectMatrix2D p_objects)
Parameters
p_objects full initialized environment grid (static elements)
Returns
self reference
Implements com.github.aptd.simulation.elements.grid.IRouting.
Definition at line 55 of file CJPSPlusStatic.java.
isNotCoordinate()
boolean com.github.aptd.simulation.elements.grid.local.CJPSPlusStatic.isNotCoordinate (final ObjectMatrix2D p_objects, final double p_row, final double p_column) private
Parameters
p_objects Snapshot of the environment
p_row the row number of the coordinate to check
p_column the column number of the coordinate to check
Returns
return true or false
Definition at line 299 of file CJPSPlusStatic.java.
Referenced by com.github.aptd.simulation.elements.grid.local.CJPSPlusStatic.diagonal(), com.github.aptd.simulation.elements.grid.local.CJPSPlusStatic.horizontal(), com.github.aptd.simulation.elements.grid.local.CJPSPlusStatic.isNotNeighbour(), com.github.aptd.simulation.elements.grid.local.CJPSPlusStatic.jump(), and com.github.aptd.simulation.elements.grid.local.CJPSPlusStatic.vertical().
isNotNeighbour()
boolean com.github.aptd.simulation.elements.grid.local.CJPSPlusStatic.isNotNeighbour (final ObjectMatrix2D p_objects, final double p_row, final double p_column, final ArrayList< DoubleMatrix1D > p_closedlist) private
Parameters
p_objects Snapshot of the environment
p_row the row number of the coordinate to check
p_column the column number of the coordinate to check
p_closedlist the list of coordinate that already explored
Definition at line 311 of file CJPSPlusStatic.java.
References com.github.aptd.simulation.elements.grid.local.CJPSPlusStatic.isNotCoordinate().
Referenced by com.github.aptd.simulation.elements.grid.local.CJPSPlusStatic.successors().
isOccupied()
boolean com.github.aptd.simulation.elements.grid.local.CJPSPlusStatic.isOccupied (final ObjectMatrix2D p_objects, final double p_row, final double p_column) private
Parameters
p_objects Snapshot of the environment
p_row the row number of the coordinate to check
p_column the column number of the coordinate to check
Returns
return true or false
Definition at line 287 of file CJPSPlusStatic.java.
Referenced by com.github.aptd.simulation.elements.grid.local.CJPSPlusStatic.diagonal(), com.github.aptd.simulation.elements.grid.local.CJPSPlusStatic.horizontal(), com.github.aptd.simulation.elements.grid.local.CJPSPlusStatic.jump(), com.github.aptd.simulation.elements.grid.local.CJPSPlusStatic.successors(), and com.github.aptd.simulation.elements.grid.local.CJPSPlusStatic.vertical().
jump()
DoubleMatrix1D com.github.aptd.simulation.elements.grid.local.CJPSPlusStatic.jump (final DoubleMatrix1D p_curnode, final DoubleMatrix1D p_target, final double p_row, final double p_col, final ObjectMatrix2D p_objects) private
Parameters
p_curnode the current node to search for
p_target the goal node
p_row to increase or decrease row by adding p_row
p_col to increase or decrease column by adding p_col
p_objects Snapshot of the environment
Returns
l_nextnode next jump point
Definition at line 175 of file CJPSPlusStatic.java.
References com.github.aptd.simulation.elements.grid.local.CJPSPlusStatic.diagjump(), com.github.aptd.simulation.elements.grid.local.CJPSPlusStatic.horizontal(), com.github.aptd.simulation.elements.grid.local.CJPSPlusStatic.isNotCoordinate(), com.github.aptd.simulation.elements.grid.local.CJPSPlusStatic.isOccupied(), and com.github.aptd.simulation.elements.grid.local.CJPSPlusStatic.vertical().
Referenced by com.github.aptd.simulation.elements.grid.local.CJPSPlusStatic.diagjump(), and com.github.aptd.simulation.elements.grid.local.CJPSPlusStatic.successors().
route()
final List<DoubleMatrix1D> com.github.aptd.simulation.elements.grid.local.CJPSPlusStatic.route (final ObjectMatrix2D p_objects, final DoubleMatrix1D p_source, final DoubleMatrix1D p_target)
Parameters
p_objects object matrix
p_source current position
p_target target position
Returns
list of tuples of the cellindex
Implements com.github.aptd.simulation.elements.grid.IRouting.
Definition at line 61 of file CJPSPlusStatic.java.
References com.github.aptd.simulation.elements.grid.local.CJPSPlusStatic.CJumpPoint.coordinate(), com.github.aptd.simulation.elements.grid.local.CJPSPlusStatic.CJumpPoint.parent(), and com.github.aptd.simulation.elements.grid.local.CJPSPlusStatic.successors().
successors()
void com.github.aptd.simulation.elements.grid.local.CJPSPlusStatic.successors (final ObjectMatrix2D p_objects, final CJumpPoint p_curnode, final DoubleMatrix1D p_target, final ArrayList< DoubleMatrix1D > p_closedlist, final Set< CJumpPoint > p_openlist) private
Parameters
p_objects Snapshot of the environment
p_curnode the current node to search for successors
p_target the goal node
p_closedlist the list of coordinate that already explored
p_openlist the set of CJumpPoint that will be explored
Definition at line 117 of file CJPSPlusStatic.java.
References com.github.aptd.simulation.elements.grid.local.CJPSPlusStatic.addsuccessors(), com.github.aptd.simulation.elements.grid.local.CJPSPlusStatic.CJumpPoint.coordinate(), com.github.aptd.simulation.elements.grid.local.CJPSPlusStatic.isNotNeighbour(), com.github.aptd.simulation.elements.grid.local.CJPSPlusStatic.isOccupied(), and com.github.aptd.simulation.elements.grid.local.CJPSPlusStatic.jump().
Referenced by com.github.aptd.simulation.elements.grid.local.CJPSPlusStatic.route().
vertical()
boolean com.github.aptd.simulation.elements.grid.local.CJPSPlusStatic.vertical (final double p_nextrow, final double p_nextcol, final double p_col, final ObjectMatrix2D p_objects, final double p_value) private
Parameters
p_nextrow row of the next node to search for
p_nextcol column of the next node to search for
p_col to increase or decrease column by adding p_col
p_objects Snapshot of the environment
p_value direction
Returns
true or false
Definition at line 273 of file CJPSPlusStatic.java.
References com.github.aptd.simulation.elements.grid.local.CJPSPlusStatic.isNotCoordinate(), and com.github.aptd.simulation.elements.grid.local.CJPSPlusStatic.isOccupied().
Referenced by com.github.aptd.simulation.elements.grid.local.CJPSPlusStatic.jump().