Asimov - Agentbased Passenger & Train Delay Simulation: com.github.aptd.simulation.elements.train.CTrain Class Reference
com.github.aptd.simulation.elements.train.CTrain Class Reference
train class
Classes
class CGenerator
generator
class CTimetableEntry
an entry in the timetable of the train
Public Member Functions
final ITrain< ITrain<?> > addwagon (final IWagon<?> p_wagon)
final IWagon<?> removewagon ()
final int wagon ()
Public Member Functions inherited from com.github.aptd.simulation.elements.IStatefulElement< N extends IElement<?>
final Instant nextstatechange ()
synchronized Stream< IMessage > output ()
Public Member Functions inherited from com.github.aptd.simulation.elements.IBaseElement< N >
N call () throws Exception
final IElement< N > environment (final IEnvironment< N, ?> p_environment)
final boolean equals (final Object p_object)
final int hashCode ()
final String id ()
boolean imminent ()
whether the element has a scheduled activation at the current time
N input (final IMessage p_message)
store an incoming message to be processed
final Stream< ILiteral > literal (final IElement<?>... p_object)
final Stream< ILiteral > literal (final Stream< IElement<?>> p_object)
Instant nextactivation ()
Stream< IMessage > output ()
get outgoing messages.
String toString ()
Public Member Functions inherited from com.github.aptd.simulation.elements.train.ITrain< ITrain<?> >
ITrain< T > addwagon (final IWagon<?> p_wagon)
adds a new wagon
IWagon<?> removewagon ()
removes the last wagon
int wagon ()
wagon number
Protected Member Functions
final synchronized Instant determinenextstatechange ()
Stream< ILiteral > individualliteral (final Stream< com.github.aptd.simulation.elements.IElement<?>> p_object)
final synchronized boolean updatecontinuous (final Duration p_elapsed)
final synchronized boolean updatestate ()
void writeState (final JsonGenerator p_generator) throws IOException
Protected Member Functions inherited from com.github.aptd.simulation.elements.IStatefulElement< N extends IElement<?>
IStatefulElement (final IAgentConfiguration< N > p_configuration, final String p_functor, final String p_id, final ITime p_time)
ctor
final synchronized void continuousupdate ()
abstract Instant determinenextstatechange ()
calculates the time instant at which the next (internal) state change happens unless the agent is interrupted by input.
final void flushOutput ()
final void output (final IMessage p_message)
final synchronized void transition ()
abstract boolean updatecontinuous (final Duration p_elapsed)
apart from updatestate(), this is the only place where continuous state shall be changed; discrete state must not be changed here
abstract boolean updatestate ()
this is the ONLY place where the discrete state shall be touched.
abstract void writeState (final JsonGenerator p_generator) throws IOException
every implementing class must provide this method that serializes the current state of the object into the provided JsonGenerator (fasterxml-core)
Protected Member Functions inherited from com.github.aptd.simulation.elements.IBaseElement< N >
IBaseElement (final IAgentConfiguration< N > p_configuration, final String p_functor, final String p_id, final ITime p_time)
ctor
abstract Stream< ILiteral > individualliteral (final Stream< IElement<?>> p_object)
define object literal addons
Private Member Functions
CTrain (final IAgentConfiguration< ITrain<?>> p_configuration, final String p_id, final Stream< CTimetableEntry > p_timetable, final List< IDoor<?>> p_doors, final Stream< IWagon<?>> p_wagon, final ITime p_time)
ctor
void debugPrintState ()
Private Attributes
final Set< IDoor<?> > m_doorsclosedlocked = Collections.synchronizedSet(new HashSet<>())
lists of doors
final Set< IDoor<?> > m_doorsnotclosedlocked = Collections.synchronizedSet(new HashSet<>())
final Set< IPassenger<?> > m_passengers = Collections.synchronizedSet(new HashSet<>())
set of passengers on the train (subscribers to notifcations of arrivals at stations)
final IGPS m_position = null
current GPS position
double m_positionontrack
ETrainState m_state = ETrainState.ARRIVED
final List< CTimetableEntry > m_timetable
int m_ttindex
final List< IWagon<?> > m_wagon
list of wagons
Static Private Attributes
static final double DRIVING_SPEED = 40.0
average driving speed (not considering acceleration and braking at the moment)
static final String FUNCTOR = "train"
literal functor
static final long serialVersionUID = 7268435045100070725L
serial id
Additional Inherited Members
Static Public Member Functions inherited from com.github.aptd.simulation.elements.IStatefulElement< N extends IElement<?>
static final String getDefaultAsl (final String p_name)
generates a default asl script string calling "state/transition" upon "!activate", and greeting upon initialisation
Protected Attributes inherited from com.github.aptd.simulation.elements.IStatefulElement< N extends IElement<?>
Instant m_lastcontinuousupdate
Instant m_laststatechange
Instant m_nextstatechange
Protected Attributes inherited from com.github.aptd.simulation.elements.IBaseElement< N >
final String m_id
agent name
final ListMultimap< EMessageType, IMessage > m_input
set of inputs to be processed
Instant m_nextactivation
simulated time at which the agent will become active again on its own
final ITime m_time
reference to time
Detailed Description
Definition at line 61 of file CTrain.java.
Constructor & Destructor Documentation
CTrain()
com.github.aptd.simulation.elements.train.CTrain.CTrain (final IAgentConfiguration< ITrain<?>> p_configuration, final String p_id, final Stream< CTimetableEntry > p_timetable, final List< IDoor<?>> p_doors, final Stream< IWagon<?>> p_wagon, final ITime p_time) private
Parameters
p_configuration agent configuration
p_id train identifier
p_timetable stream of timetable entries
p_doors list of door agent references
p_wagon stream of wagon references
p_time environment
Definition at line 111 of file CTrain.java.
References com.github.aptd.simulation.core.time.ITime.current(), com.github.aptd.simulation.elements.train.CTrain.determinenextstatechange(), com.github.aptd.simulation.elements.IBaseElement< N >.m_nextactivation, com.github.aptd.simulation.elements.IStatefulElement< N extends IElement<?>.m_nextstatechange, com.github.aptd.simulation.elements.IBaseElement< N >.m_time, com.github.aptd.simulation.elements.IStatefulElement< N extends IElement<?>.output(), and com.github.aptd.simulation.core.messaging.EMessageType.TRAIN_TO_PLATFORM_ARRIVING.
Referenced by com.github.aptd.simulation.elements.train.CTrain.CGenerator.generate().
Member Function Documentation
addwagon()
final ITrain<ITrain<?> > com.github.aptd.simulation.elements.train.CTrain.addwagon (final IWagon<?> p_wagon)
Definition at line 132 of file CTrain.java.
debugPrintState()
void com.github.aptd.simulation.elements.train.CTrain.debugPrintState () private
Definition at line 278 of file CTrain.java.
References com.github.aptd.simulation.elements.IBaseElement< N >.m_id.
Referenced by com.github.aptd.simulation.elements.train.CTrain.updatestate().
determinenextstatechange()
final synchronized Instant com.github.aptd.simulation.elements.train.CTrain.determinenextstatechange () protected
Definition at line 157 of file CTrain.java.
References com.github.aptd.simulation.elements.IStatefulElement< N extends IElement<?>.m_lastcontinuousupdate, com.github.aptd.simulation.elements.IStatefulElement< N extends IElement<?>.m_laststatechange, and com.github.aptd.simulation.elements.train.CTrain.m_positionontrack.
Referenced by com.github.aptd.simulation.elements.train.CTrain.CTrain().
individualliteral()
Stream<ILiteral> com.github.aptd.simulation.elements.train.CTrain.individualliteral (final Stream< com.github.aptd.simulation.elements.IElement<?>> p_object) protected
Definition at line 149 of file CTrain.java.
removewagon()
final IWagon<?> com.github.aptd.simulation.elements.train.CTrain.removewagon ()
Definition at line 139 of file CTrain.java.
References com.github.aptd.simulation.elements.IBaseElement< N >.m_id.
updatecontinuous()
final synchronized boolean com.github.aptd.simulation.elements.train.CTrain.updatecontinuous (final Duration p_elapsed) protected
Definition at line 248 of file CTrain.java.
References com.github.aptd.simulation.elements.train.CTrain.DRIVING_SPEED.
updatestate()
final synchronized boolean com.github.aptd.simulation.elements.train.CTrain.updatestate () protected
Definition at line 177 of file CTrain.java.
References com.github.aptd.simulation.elements.train.ETrainState.ARRIVED, com.github.aptd.simulation.core.time.ITime.current(), com.github.aptd.simulation.elements.train.CTrain.debugPrintState(), com.github.aptd.simulation.core.messaging.EMessageType.DOOR_TO_TRAIN_CLOSED_LOCKED, com.github.aptd.simulation.elements.train.ETrainState.DRIVING, com.github.aptd.simulation.elements.IBaseElement< N >.m_id, com.github.aptd.simulation.elements.IBaseElement< N >.m_input, com.github.aptd.simulation.elements.IStatefulElement< N extends IElement<?>.m_nextstatechange, com.github.aptd.simulation.elements.IBaseElement< N >.m_time, com.github.aptd.simulation.elements.IStatefulElement< N extends IElement<?>.output(), com.github.aptd.simulation.core.messaging.EMessageType.PASSENGER_TO_TRAIN_SUBSCRIBE, com.github.aptd.simulation.core.messaging.EMessageType.PASSENGER_TO_TRAIN_UNSUBSCRIBE, com.github.aptd.simulation.core.messaging.EMessageType.TRAIN_TO_DOOR_LOCK, com.github.aptd.simulation.core.messaging.EMessageType.TRAIN_TO_DOOR_UNLOCK, com.github.aptd.simulation.core.messaging.EMessageType.TRAIN_TO_PASSENGER_ARRIVING, com.github.aptd.simulation.core.messaging.EMessageType.TRAIN_TO_PLATFORM_ARRIVING, com.github.aptd.simulation.core.messaging.EMessageType.TRAIN_TO_PLATFORM_DEPARTING, and com.github.aptd.simulation.elements.train.ETrainState.WAITING_TO_DRIVE.
wagon()
final int com.github.aptd.simulation.elements.train.CTrain.wagon ()
Definition at line 126 of file CTrain.java.
writeState()
void com.github.aptd.simulation.elements.train.CTrain.writeState (final JsonGenerator p_generator) throws IOException protected
Definition at line 262 of file CTrain.java.
Member Data Documentation
DRIVING_SPEED
final double com.github.aptd.simulation.elements.train.CTrain.DRIVING_SPEED = 40.0 static private
Todo:
make a non-static field for instances
Definition at line 75 of file CTrain.java.
Referenced by com.github.aptd.simulation.elements.train.CTrain.updatecontinuous().
FUNCTOR
final String com.github.aptd.simulation.elements.train.CTrain.FUNCTOR = "train" static private
Definition at line 70 of file CTrain.java.
m_doorsclosedlocked
final Set<IDoor<?> > com.github.aptd.simulation.elements.train.CTrain.m_doorsclosedlocked = Collections.synchronizedSet(new HashSet<>()) private
Definition at line 84 of file CTrain.java.
m_doorsnotclosedlocked
final Set<IDoor<?> > com.github.aptd.simulation.elements.train.CTrain.m_doorsnotclosedlocked = Collections.synchronizedSet(new HashSet<>()) private
Definition at line 85 of file CTrain.java.
m_passengers
final Set<IPassenger<?> > com.github.aptd.simulation.elements.train.CTrain.m_passengers = Collections.synchronizedSet(new HashSet<>()) private
Definition at line 89 of file CTrain.java.
m_position
final IGPS com.github.aptd.simulation.elements.train.CTrain.m_position = null private
Definition at line 93 of file CTrain.java.
m_positionontrack
double com.github.aptd.simulation.elements.train.CTrain.m_positionontrack private
Definition at line 99 of file CTrain.java.
Referenced by com.github.aptd.simulation.elements.train.CTrain.determinenextstatechange().
m_state
ETrainState com.github.aptd.simulation.elements.train.CTrain.m_state = ETrainState.ARRIVED private
Definition at line 95 of file CTrain.java.
m_timetable
final List<CTimetableEntry> com.github.aptd.simulation.elements.train.CTrain.m_timetable private
Definition at line 97 of file CTrain.java.
m_ttindex
int com.github.aptd.simulation.elements.train.CTrain.m_ttindex private
Definition at line 98 of file CTrain.java.
m_wagon
final List<IWagon<?> > com.github.aptd.simulation.elements.train.CTrain.m_wagon private
Todo:
change to map with wagon names and ordering
Definition at line 80 of file CTrain.java.
serialVersionUID
final long com.github.aptd.simulation.elements.train.CTrain.serialVersionUID = 7268435045100070725L static private
Definition at line 66 of file CTrain.java.