Asimov - Agentbased Passenger & Train Delay Simulation: com.github.aptd.simulation.elements.grid.local.CJPSPlusStatic.CJumpPoint Class Reference
com.github.aptd.simulation.elements.grid.local.CJPSPlusStatic.CJumpPoint Class Reference
jump-point with a static class "static" means that the class can exists without the CJPSPlus object "final" no inheritance can be create
Static Public Attributes
static final CJumpPoint ZERO = new CJumpPoint()
for avoid zero-jump-points we create exactly one
Package Functions
CJumpPoint (final DoubleMatrix1D p_coordinate, final CJumpPoint p_parent)
ctor
final DoubleMatrix1D coordinate ()
getter for coordinate
final double fscore ()
getter for f_score
final double gscore ()
getter for g-score
final CJumpPoint gscore (final double p_gscore)
setter for g_score
final CJumpPoint hscore (final double p_hscore)
setter for h_score
final CJumpPoint parent ()
getter for parent
Private Member Functions
CJumpPoint ()
ctor - with default values
Private Attributes
final DoubleMatrix1D m_coordinate
position
double m_gscore
jump-point g-score value
double m_hscore
jump-point h-score value
CJumpPoint m_parent
parent node of current JumpPoint
Detailed Description
Definition at line 352 of file CJPSPlusStatic.java.
Constructor & Destructor Documentation
CJumpPoint() [1/2]
com.github.aptd.simulation.elements.grid.local.CJPSPlusStatic.CJumpPoint.CJumpPoint () private
Definition at line 381 of file CJPSPlusStatic.java.
CJumpPoint() [2/2]
com.github.aptd.simulation.elements.grid.local.CJPSPlusStatic.CJumpPoint.CJumpPoint (final DoubleMatrix1D p_coordinate, final CJumpPoint p_parent) package
Parameters
p_coordinate postion value
p_parent parent of the current jump point
Definition at line 392 of file CJPSPlusStatic.java.
Member Function Documentation
coordinate()
final DoubleMatrix1D com.github.aptd.simulation.elements.grid.local.CJPSPlusStatic.CJumpPoint.coordinate () package
Returns
coordinate
Definition at line 403 of file CJPSPlusStatic.java.
Referenced by com.github.aptd.simulation.elements.grid.local.CJPSPlusStatic.addsuccessors(), com.github.aptd.simulation.elements.grid.local.CJPSPlusStatic.calculateScore(), com.github.aptd.simulation.elements.grid.local.CJPSPlusStatic.route(), and com.github.aptd.simulation.elements.grid.local.CJPSPlusStatic.successors().
fscore()
final double com.github.aptd.simulation.elements.grid.local.CJPSPlusStatic.CJumpPoint.fscore () package
Returns
f-score
Definition at line 423 of file CJPSPlusStatic.java.
Referenced by com.github.aptd.simulation.elements.grid.local.CJPSPlusStatic.addsuccessors(), and com.github.aptd.simulation.elements.grid.local.CJPSPlusStatic.CCompareJumpPoint.compare().
gscore() [1/2]
final double com.github.aptd.simulation.elements.grid.local.CJPSPlusStatic.CJumpPoint.gscore () package
Returns
g-score
Definition at line 413 of file CJPSPlusStatic.java.
Referenced by com.github.aptd.simulation.elements.grid.local.CJPSPlusStatic.calculateScore().
gscore() [2/2]
final CJumpPoint com.github.aptd.simulation.elements.grid.local.CJPSPlusStatic.CJumpPoint.gscore (final double p_gscore) package
Returns
CJumpPoint
Definition at line 443 of file CJPSPlusStatic.java.
hscore()
final CJumpPoint com.github.aptd.simulation.elements.grid.local.CJPSPlusStatic.CJumpPoint.hscore (final double p_hscore) package
Returns
CJumpPoint
Definition at line 454 of file CJPSPlusStatic.java.
Referenced by com.github.aptd.simulation.elements.grid.local.CJPSPlusStatic.calculateScore().
parent()
final CJumpPoint com.github.aptd.simulation.elements.grid.local.CJPSPlusStatic.CJumpPoint.parent () package
Returns
parent
Definition at line 433 of file CJPSPlusStatic.java.
Referenced by com.github.aptd.simulation.elements.grid.local.CJPSPlusStatic.calculateScore(), and com.github.aptd.simulation.elements.grid.local.CJPSPlusStatic.route().
Member Data Documentation
m_coordinate
final DoubleMatrix1D com.github.aptd.simulation.elements.grid.local.CJPSPlusStatic.CJumpPoint.m_coordinate private
Definition at line 376 of file CJPSPlusStatic.java.
m_gscore
double com.github.aptd.simulation.elements.grid.local.CJPSPlusStatic.CJumpPoint.m_gscore private
Definition at line 362 of file CJPSPlusStatic.java.
m_hscore
double com.github.aptd.simulation.elements.grid.local.CJPSPlusStatic.CJumpPoint.m_hscore private
Definition at line 367 of file CJPSPlusStatic.java.
m_parent
CJumpPoint com.github.aptd.simulation.elements.grid.local.CJPSPlusStatic.CJumpPoint.m_parent private
Definition at line 372 of file CJPSPlusStatic.java.
ZERO
final CJumpPoint com.github.aptd.simulation.elements.grid.local.CJPSPlusStatic.CJumpPoint.ZERO = new CJumpPoint() static
Definition at line 357 of file CJPSPlusStatic.java.