Asimov - Agentbased Passenger & Train Delay Simulation: com.github.aptd.simulation.elements.IStatefulElement< N extends IElement<?> Class Template Reference
com.github.aptd.simulation.elements.IStatefulElement< N extends IElement<?> Class Template Reference abstract
stateful base element with internal transitions and output queueing
Public Member Functions
final Instant nextstatechange ()
synchronized Stream< IMessage > output ()
Public Member Functions inherited from com.github.aptd.simulation.elements.IBaseElement< N >
N call () throws Exception
final IElement< N > environment (final IEnvironment< N, ?> p_environment)
final boolean equals (final Object p_object)
final int hashCode ()
final String id ()
boolean imminent ()
whether the element has a scheduled activation at the current time
N input (final IMessage p_message)
store an incoming message to be processed
final Stream< ILiteral > literal (final IElement<?>... p_object)
final Stream< ILiteral > literal (final Stream< IElement<?>> p_object)
Instant nextactivation ()
Stream< IMessage > output ()
get outgoing messages.
String toString ()
Static Public Member Functions
static final String getDefaultAsl (final String p_name)
generates a default asl script string calling "state/transition" upon "!activate", and greeting upon initialisation
Protected Member Functions
IStatefulElement (final IAgentConfiguration< N > p_configuration, final String p_functor, final String p_id, final ITime p_time)
ctor
final synchronized void continuousupdate ()
abstract Instant determinenextstatechange ()
calculates the time instant at which the next (internal) state change happens unless the agent is interrupted by input.
final void flushOutput ()
final void output (final IMessage p_message)
final synchronized void transition ()
abstract boolean updatecontinuous (final Duration p_elapsed)
apart from updatestate(), this is the only place where continuous state shall be changed; discrete state must not be changed here
abstract boolean updatestate ()
this is the ONLY place where the discrete state shall be touched.
abstract void writeState (final JsonGenerator p_generator) throws IOException
every implementing class must provide this method that serializes the current state of the object into the provided JsonGenerator (fasterxml-core)
Protected Member Functions inherited from com.github.aptd.simulation.elements.IBaseElement< N >
IBaseElement (final IAgentConfiguration< N > p_configuration, final String p_functor, final String p_id, final ITime p_time)
ctor
abstract Stream< ILiteral > individualliteral (final Stream< IElement<?>> p_object)
define object literal addons
Protected Attributes
Instant m_lastcontinuousupdate
Instant m_laststatechange
Instant m_nextstatechange
Protected Attributes inherited from com.github.aptd.simulation.elements.IBaseElement< N >
final String m_id
agent name
final ListMultimap< EMessageType, IMessage > m_input
set of inputs to be processed
Instant m_nextactivation
simulated time at which the agent will become active again on its own
final ITime m_time
reference to time
Private Attributes
JsonFactory m_factory
final Set< IMessage > m_output = Collections.synchronizedSet(new HashSet<>())
Static Private Attributes
static final long serialVersionUID = 446803774238459492L
serial id
Detailed Description
Definition at line 50 of file IStatefulElement.java.
Constructor & Destructor Documentation
IStatefulElement()
com.github.aptd.simulation.elements.IStatefulElement< N extends IElement<?>.IStatefulElement (final IAgentConfiguration< N > p_configuration, final String p_functor, final String p_id, final ITime p_time) protected
Parameters
p_configuration agent configuration
p_functor ...
p_id ...
p_time time reference
Definition at line 73 of file IStatefulElement.java.
Member Function Documentation
continuousupdate()
final synchronized void com.github.aptd.simulation.elements.IStatefulElement< N extends IElement<?>.continuousupdate () protected
Definition at line 171 of file IStatefulElement.java.
determinenextstatechange()
abstract Instant com.github.aptd.simulation.elements.IStatefulElement< N extends IElement<?>.determinenextstatechange () abstract protected
pending output is ignored.
Returns
time instant of next planned internal state change (apart from pending output)
Referenced by com.github.aptd.simulation.elements.IStatefulElement< IPassenger<?> >.continuousupdate(), and com.github.aptd.simulation.elements.IStatefulElement< IPassenger<?> >.transition().
flushOutput()
final void com.github.aptd.simulation.elements.IStatefulElement< N extends IElement<?>.flushOutput () protected
Definition at line 82 of file IStatefulElement.java.
getDefaultAsl()
static final String com.github.aptd.simulation.elements.IStatefulElement< N extends IElement<?>.getDefaultAsl (final String p_name) static
Parameters
p_name the name to print with "hello" after initialisation
Returns
asl script as String
Definition at line 222 of file IStatefulElement.java.
Referenced by com.github.aptd.simulation.datamodel.CXMLReader.train().
nextstatechange()
final Instant com.github.aptd.simulation.elements.IStatefulElement< N extends IElement<?>.nextstatechange ()
Definition at line 102 of file IStatefulElement.java.
output() [1/2]
final void com.github.aptd.simulation.elements.IStatefulElement< N extends IElement<?>.output (final IMessage p_message) protected
Definition at line 87 of file IStatefulElement.java.
output() [2/2]
synchronized Stream<IMessage> com.github.aptd.simulation.elements.IStatefulElement< N extends IElement<?>.output ()
Definition at line 93 of file IStatefulElement.java.
Referenced by com.github.aptd.simulation.elements.train.CTrain.CTrain(), com.github.aptd.simulation.elements.passenger.CPassenger.handledoormessage(), com.github.aptd.simulation.elements.passenger.CPassenger.handleplatformmessages(), com.github.aptd.simulation.elements.train.CDoor.lockifrequested(), com.github.aptd.simulation.elements.train.CDoor.nextpassengerifpossible(), com.github.aptd.simulation.elements.train.CDoor.timedstatechangeifnecessary(), com.github.aptd.simulation.elements.graph.network.local.CPlatform.updatestate(), com.github.aptd.simulation.elements.train.CTrain.updatestate(), and com.github.aptd.simulation.elements.passenger.CPassenger.updatestate().
transition()
final synchronized void com.github.aptd.simulation.elements.IStatefulElement< N extends IElement<?>.transition () protected
Definition at line 109 of file IStatefulElement.java.
Referenced by com.github.aptd.simulation.elements.IStatefulElement< IPassenger<?> >.continuousupdate().
updatecontinuous()
abstract boolean com.github.aptd.simulation.elements.IStatefulElement< N extends IElement<?>.updatecontinuous (final Duration p_elapsed) abstract protected
Parameters
p_elapsed elapsed time since last continuous update
Returns
true iff the state has actually changed
Referenced by com.github.aptd.simulation.elements.IStatefulElement< IPassenger<?> >.continuousupdate().
updatestate()
abstract boolean com.github.aptd.simulation.elements.IStatefulElement< N extends IElement<?>.updatestate () abstract protected
continuous state can be adjusted here accordingly, too
Returns
true iff the state has actually changed
Referenced by com.github.aptd.simulation.elements.IStatefulElement< IPassenger<?> >.continuousupdate(), and com.github.aptd.simulation.elements.IStatefulElement< IPassenger<?> >.transition().
writeState()
abstract void com.github.aptd.simulation.elements.IStatefulElement< N extends IElement<?>.writeState (final JsonGenerator p_generator) throws IOException abstract protected
Parameters
p_generator JsonGenerator to use for serialization
Referenced by com.github.aptd.simulation.elements.IStatefulElement< IPassenger<?> >.continuousupdate(), com.github.aptd.simulation.elements.IBaseElement< N extends IElement<?>.IBaseGenerator< N extends IElement<?>.generatesingle(), and com.github.aptd.simulation.elements.IStatefulElement< IPassenger<?> >.transition().
Member Data Documentation
m_factory
JsonFactory com.github.aptd.simulation.elements.IStatefulElement< N extends IElement<?>.m_factory private
Definition at line 63 of file IStatefulElement.java.
Referenced by com.github.aptd.simulation.elements.IStatefulElement< IPassenger<?> >.transition().
m_lastcontinuousupdate
Instant com.github.aptd.simulation.elements.IStatefulElement< N extends IElement<?>.m_lastcontinuousupdate protected
Definition at line 59 of file IStatefulElement.java.
Referenced by com.github.aptd.simulation.elements.train.CDoor.determinenextstatechange(), com.github.aptd.simulation.elements.passenger.CPassenger.determinenextstatechange(), and com.github.aptd.simulation.elements.train.CTrain.determinenextstatechange().
m_laststatechange
Instant com.github.aptd.simulation.elements.IStatefulElement< N extends IElement<?>.m_laststatechange protected
Definition at line 58 of file IStatefulElement.java.
Referenced by com.github.aptd.simulation.elements.train.CTrain.determinenextstatechange().
m_nextstatechange
Instant com.github.aptd.simulation.elements.IStatefulElement< N extends IElement<?>.m_nextstatechange protected
Definition at line 60 of file IStatefulElement.java.
Referenced by com.github.aptd.simulation.elements.train.CDoor.CDoor(), com.github.aptd.simulation.elements.IStatefulElement< IPassenger<?> >.continuousupdate(), com.github.aptd.simulation.elements.passenger.CPassenger.CPassenger(), com.github.aptd.simulation.elements.train.CTrain.CTrain(), com.github.aptd.simulation.elements.IStatefulElement< IPassenger<?> >.nextstatechange(), com.github.aptd.simulation.elements.train.CDoor.timedstatechangeifnecessary(), com.github.aptd.simulation.elements.IStatefulElement< IPassenger<?> >.transition(), com.github.aptd.simulation.elements.train.CTrain.updatestate(), and com.github.aptd.simulation.elements.passenger.CPassenger.updatestate().
m_output
final Set<IMessage> com.github.aptd.simulation.elements.IStatefulElement< N extends IElement<?>.m_output = Collections.synchronizedSet(new HashSet<>()) private
Definition at line 62 of file IStatefulElement.java.
Referenced by com.github.aptd.simulation.elements.IStatefulElement< IPassenger<?> >.output().
serialVersionUID
final long com.github.aptd.simulation.elements.IStatefulElement< N extends IElement<?>.serialVersionUID = 446803774238459492L static private
Definition at line 56 of file IStatefulElement.java.