Asimov - Agentbased Passenger & Train Delay Simulation: com.github.aptd.simulation.core.experiment.IExperiment Interface Reference
com.github.aptd.simulation.core.experiment.IExperiment Interface Reference
a single experiment run
Classes
class CEmptyExperiment
empty experiment
Public Member Functions
Stream< IAction > actions ()
returns internal experiment actions
IElement<?> addAgent (String p_key, IElement<?> p_value)
IElement<?> getAgent (String p_key)
Stream< IElement<?> > objects ()
returns a stream of all executable objects
boolean parallel ()
execute agents in parallel
Stream< Callable<?> > preprocess ()
preprocessing objects
long simulationsteps ()
maximum simulation steps
IExperiment statistic (@Nonnull final IWriter p_writer)
statistic writer
ITime time ()
get the time object
Public Attributes
IExperiment EMPTY = new CEmptyExperiment()
empty experiment
Detailed Description
Bug:
incomplete
Definition at line 41 of file IExperiment.java.
Member Function Documentation
actions()
Stream<IAction> com.github.aptd.simulation.core.experiment.IExperiment.actions ()
Returns
action stream
Implemented in com.github.aptd.simulation.core.experiment.local.CExperiment, and com.github.aptd.simulation.core.experiment.IExperiment.CEmptyExperiment.
addAgent()
IElement<?> com.github.aptd.simulation.core.experiment.IExperiment.addAgent (String p_key, IElement<?> p_value)
Implemented in com.github.aptd.simulation.core.experiment.local.CExperiment, and com.github.aptd.simulation.core.experiment.IExperiment.CEmptyExperiment.
Referenced by com.github.aptd.simulation.elements.passenger.CPassengerSource.generatepassenger().
getAgent()
IElement<?> com.github.aptd.simulation.core.experiment.IExperiment.getAgent (String p_key)
Implemented in com.github.aptd.simulation.core.experiment.local.CExperiment, and com.github.aptd.simulation.core.experiment.IExperiment.CEmptyExperiment.
Referenced by com.github.aptd.simulation.core.messaging.local.CMessenger.call().
objects()
Stream<IElement<?> > com.github.aptd.simulation.core.experiment.IExperiment.objects ()
Returns
callable stream
Implemented in com.github.aptd.simulation.core.experiment.local.CExperiment, and com.github.aptd.simulation.core.experiment.IExperiment.CEmptyExperiment.
Referenced by com.github.aptd.simulation.core.messaging.local.CMessenger.call(), and com.github.aptd.simulation.core.runtime.local.CRuntime.execute().
parallel()
boolean com.github.aptd.simulation.core.experiment.IExperiment.parallel ()
Returns
boolean flag for parallel execution
Implemented in com.github.aptd.simulation.core.experiment.local.CExperiment, and com.github.aptd.simulation.core.experiment.IExperiment.CEmptyExperiment.
Referenced by com.github.aptd.simulation.core.runtime.local.CRuntime.execute().
preprocess()
Stream<Callable<?> > com.github.aptd.simulation.core.experiment.IExperiment.preprocess ()
Returns
object stream
Implemented in com.github.aptd.simulation.core.experiment.local.CExperiment, and com.github.aptd.simulation.core.experiment.IExperiment.CEmptyExperiment.
Referenced by com.github.aptd.simulation.core.runtime.local.CRuntime.execute().
simulationsteps()
long com.github.aptd.simulation.core.experiment.IExperiment.simulationsteps ()
Returns
simulation steps
Implemented in com.github.aptd.simulation.core.experiment.local.CExperiment, and com.github.aptd.simulation.core.experiment.IExperiment.CEmptyExperiment.
statistic()
IExperiment com.github.aptd.simulation.core.experiment.IExperiment.statistic (@Nonnull final IWriter p_writer)
Returns
self-reference
Implemented in com.github.aptd.simulation.core.experiment.local.CExperiment, and com.github.aptd.simulation.core.experiment.IExperiment.CEmptyExperiment.
time()
ITime com.github.aptd.simulation.core.experiment.IExperiment.time ()
Returns
time object
Implemented in com.github.aptd.simulation.core.experiment.local.CExperiment, and com.github.aptd.simulation.core.experiment.IExperiment.CEmptyExperiment.
Referenced by com.github.aptd.simulation.core.runtime.local.CRuntime.execute().
Member Data Documentation
EMPTY
IExperiment com.github.aptd.simulation.core.experiment.IExperiment.EMPTY = new CEmptyExperiment()
Definition at line 46 of file IExperiment.java.