Asimov - Agentbased Passenger & Train Delay Simulation: com.github.aptd.simulation.elements.graph.TestCNetwork Class Reference
com.github.aptd.simulation.elements.graph.TestCNetwork Class Reference
network test
Public Member Functions
void ininitialize ()
initialize test
final void networkbuild ()
network design test
Static Public Member Functions
static void main (final String[] p_args)
main method to run test manual
Private Attributes
IElement.IGenerator< IStation<?> > m_station
station generator
IElement.IGenerator< ITrack<?> > m_track
track generator
Additional Inherited Members
Protected Member Functions inherited from com.github.aptd.simulation.IBaseTest
final void invoketest ()
invoke all test manually
Static Protected Attributes inherited from com.github.aptd.simulation.IBaseTest
static final boolean PRINTENABLE = Files.exists(Paths.get("printing.conf"))
enable printing of test-data
Detailed Description
Definition at line 49 of file TestCNetwork.java.
Member Function Documentation
ininitialize()
void com.github.aptd.simulation.elements.graph.TestCNetwork.ininitialize ()
Definition at line 65 of file TestCNetwork.java.
References com.github.aptd.simulation.common.CConfiguration.agentaction(), com.github.aptd.simulation.common.CConfiguration.INSTANCE, and com.github.aptd.simulation.common.CConfiguration.loadstring().
main()
static void com.github.aptd.simulation.elements.graph.TestCNetwork.main (final String [] p_args) static
Parameters
p_args command-line arguments
Definition at line 169 of file TestCNetwork.java.
References com.github.aptd.simulation.IBaseTest.invoketest().
networkbuild()
final void com.github.aptd.simulation.elements.graph.TestCNetwork.networkbuild ()
Definition at line 98 of file TestCNetwork.java.
References com.github.aptd.simulation.elements.IElement< T extends IAgent<?>.id(), and com.github.aptd.simulation.IBaseTest.PRINTENABLE.
Member Data Documentation
m_station
IElement.IGenerator<IStation<?> > com.github.aptd.simulation.elements.graph.TestCNetwork.m_station private
Definition at line 54 of file TestCNetwork.java.
m_track
IElement.IGenerator<ITrack<?> > com.github.aptd.simulation.elements.graph.TestCNetwork.m_track private
Definition at line 58 of file TestCNetwork.java.