Asimov - Agentbased Passenger & Train Delay Simulation: com.github.aptd.simulation.elements.IBaseElement< N extends IElement<?>.IBaseGenerator< N extends IElement<?> Class Template Reference
com.github.aptd.simulation.elements.IBaseElement< N extends IElement<?>.IBaseGenerator< N extends IElement<?> Class Template Reference abstract
base agent generator
Classes
class CConfiguration
agent configuration
Public Member Functions
final N generatesingle (final Object... p_data)
IGenerator< N > resetcount ()
Protected Member Functions
IBaseGenerator (final InputStream p_stream, final Set< IAction > p_actions, final Class<? extends N > p_agentclass, final ITime p_time) throws Exception
ctor
IAgentConfiguration< N > configuration (@Nonnull final IFuzzyBundle< Boolean > p_fuzzy, @Nonnull final Collection< ILiteral > p_initalbeliefs, @Nonnull final Set< IPlan > p_plans, @Nonnull final Set< IRule > p_rules, @Nullable final ILiteral p_initialgoal, @Nonnull final IUnifier p_unifier, @Nonnull final IVariableBuilder p_variablebuilder)
abstract Pair< N, Stream< String > > generate (final Object... p_data)
generates the agent
Protected Attributes
final ITime m_time
time reference
Private Attributes
JsonFactory m_factory
Detailed Description
Template Parameters
N agent type
Definition at line 302 of file IBaseElement.java.
Constructor & Destructor Documentation
IBaseGenerator()
com.github.aptd.simulation.elements.IBaseElement< N extends IElement<?>.IBaseGenerator< N extends IElement<?>.IBaseGenerator (final InputStream p_stream, final Set< IAction > p_actions, final Class<? extends N > p_agentclass, final ITime p_time) throws Exception protected
Parameters
p_stream stream
p_actions action
p_agentclass agent class with internal actions
p_time time reference
Exceptions
Exception on any error
Definition at line 320 of file IBaseElement.java.
Member Function Documentation
configuration()
IAgentConfiguration<N> com.github.aptd.simulation.elements.IBaseElement< N extends IElement<?>.IBaseGenerator< N extends IElement<?>.configuration (@Nonnull final IFuzzyBundle< Boolean > p_fuzzy, @Nonnull final Collection< ILiteral > p_initalbeliefs, @Nonnull final Set< IPlan > p_plans, @Nonnull final Set< IRule > p_rules, @Nullable final ILiteral p_initialgoal, @Nonnull final IUnifier p_unifier, @Nonnull final IVariableBuilder p_variablebuilder) protected
Definition at line 379 of file IBaseElement.java.
generate()
abstract Pair<N, Stream<String> > com.github.aptd.simulation.elements.IBaseElement< N extends IElement<?>.IBaseGenerator< N extends IElement<?>.generate (final Object... p_data) abstract protected
Parameters
p_data creating arguments
Returns
agent object and group names
Referenced by com.github.aptd.simulation.elements.IBaseElement< N extends IElement<?>.IBaseGenerator< N extends IElement<?>.generatesingle().
generatesingle()
final N com.github.aptd.simulation.elements.IBaseElement< N extends IElement<?>.IBaseGenerator< N extends IElement<?>.generatesingle (final Object... p_data)
Definition at line 329 of file IBaseElement.java.
References com.github.aptd.simulation.elements.IBaseElement< N extends IElement<?>.IBaseGenerator< N extends IElement<?>.generate(), com.github.aptd.simulation.ui.CHTTPServer.register(), and com.github.aptd.simulation.elements.IStatefulElement< N extends IElement<?>.writeState().
resetcount()
IGenerator<N> com.github.aptd.simulation.elements.IBaseElement< N extends IElement<?>.IBaseGenerator< N extends IElement<?>.resetcount ()
Definition at line 373 of file IBaseElement.java.
Member Data Documentation
m_factory
JsonFactory com.github.aptd.simulation.elements.IBaseElement< N extends IElement<?>.IBaseGenerator< N extends IElement<?>.m_factory private
Definition at line 309 of file IBaseElement.java.
m_time
final ITime com.github.aptd.simulation.elements.IBaseElement< N extends IElement<?>.IBaseGenerator< N extends IElement<?>.m_time protected
Definition at line 307 of file IBaseElement.java.
Referenced by com.github.aptd.simulation.elements.IBaseElement< N extends IElement<?>.CTimeBeliefbase.containsLiteral(), com.github.aptd.simulation.elements.IBaseElement< N extends IElement<?>.CTimeBeliefbase.empty(), com.github.aptd.simulation.elements.dispatcher.CDispatcher.CGenerator.generate(), com.github.aptd.simulation.elements.graph.network.local.CStation.CGenerator.generate(), com.github.aptd.simulation.elements.IBaseElement< N extends IElement<?>.CTimeBeliefbase.literal(), com.github.aptd.simulation.elements.IBaseElement< N extends IElement<?>.CTimeBeliefbase.size(), and com.github.aptd.simulation.elements.IBaseElement< N extends IElement<?>.CTimeBeliefbase.streamLiteral().