Asimov - Agentbased Passenger & Train Delay Simulation: com.github.aptd.simulation.elements.IBaseElement< N extends IElement<?>.CTimeBeliefbase Class Reference
com.github.aptd.simulation.elements.IBaseElement< N extends IElement<?>.CTimeBeliefbase Class Reference
on-demand beliefbase to get access to the time structure
Inherits IBeliefbaseOnDemand< N >.
Public Member Functions
final boolean containsLiteral (@Nonnull final String p_key)
final boolean empty ()
final Collection< ILiteral > literal (@Nonnull final String p_key)
final int size ()
final Stream< ILiteral > streamLiteral ()
Detailed Description
Definition at line 429 of file IBaseElement.java.
Member Function Documentation
containsLiteral()
final boolean com.github.aptd.simulation.elements.IBaseElement< N extends IElement<?>.CTimeBeliefbase.containsLiteral (@Nonnull final String p_key)
Definition at line 463 of file IBaseElement.java.
References com.github.aptd.simulation.elements.IPerceiveable.literal(), and com.github.aptd.simulation.elements.IBaseElement< N extends IElement<?>.IBaseGenerator< N extends IElement<?>.m_time.
empty()
final boolean com.github.aptd.simulation.elements.IBaseElement< N extends IElement<?>.CTimeBeliefbase.empty ()
Definition at line 449 of file IBaseElement.java.
References com.github.aptd.simulation.elements.IPerceiveable.literal(), and com.github.aptd.simulation.elements.IBaseElement< N extends IElement<?>.IBaseGenerator< N extends IElement<?>.m_time.
literal()
final Collection<ILiteral> com.github.aptd.simulation.elements.IBaseElement< N extends IElement<?>.CTimeBeliefbase.literal (@Nonnull final String p_key)
Definition at line 441 of file IBaseElement.java.
References com.github.aptd.simulation.elements.IPerceiveable.literal(), and com.github.aptd.simulation.elements.IBaseElement< N extends IElement<?>.IBaseGenerator< N extends IElement<?>.m_time.
size()
final int com.github.aptd.simulation.elements.IBaseElement< N extends IElement<?>.CTimeBeliefbase.size ()
Definition at line 457 of file IBaseElement.java.
References com.github.aptd.simulation.elements.IPerceiveable.literal(), and com.github.aptd.simulation.elements.IBaseElement< N extends IElement<?>.IBaseGenerator< N extends IElement<?>.m_time.
streamLiteral()
final Stream<ILiteral> com.github.aptd.simulation.elements.IBaseElement< N extends IElement<?>.CTimeBeliefbase.streamLiteral ()
Definition at line 434 of file IBaseElement.java.
References com.github.aptd.simulation.elements.IPerceiveable.literal(), and com.github.aptd.simulation.elements.IBaseElement< N extends IElement<?>.IBaseGenerator< N extends IElement<?>.m_time.