Asimov - Agentbased Passenger & Train Delay Simulation: com.github.aptd.simulation.TestCLanguageLabels Class Reference
com.github.aptd.simulation.TestCLanguageLabels Class Reference
test all resource strings
Classes
class CJavaVistor
AST visitor class.
Public Member Functions
void testResourceString () throws IOException
test-case all resource strings
void testTranslation ()
check package translation configuration versus property items
Static Public Member Functions
static void main (final String[] p_args) throws IOException
main method
Static Package Functions
[static initializer]
Static Private Attributes
static final String CLASSSEPARATOR = "."
static final Map< String, URI > LANGUAGEPROPERY = new HashMap<>()
property filenames with language data
static final URI SEARCHPATH
search path
Additional Inherited Members
Protected Member Functions inherited from com.github.aptd.simulation.IBaseTest
final void invoketest ()
invoke all test manually
Static Protected Attributes inherited from com.github.aptd.simulation.IBaseTest
static final boolean PRINTENABLE = Files.exists(Paths.get("printing.conf"))
enable printing of test-data
Detailed Description
Definition at line 67 of file TestCLanguageLabels.java.
Member Function Documentation
[static initializer]()
com.github.aptd.simulation.TestCLanguageLabels.[static initializer] () static package
main()
static void com.github.aptd.simulation.TestCLanguageLabels.main (final String [] p_args) throws IOException static
Parameters
p_args arguments
Exceptions
IOException in file error
Definition at line 293 of file TestCLanguageLabels.java.
References com.github.aptd.simulation.IBaseTest.invoketest().
testResourceString()
void com.github.aptd.simulation.TestCLanguageLabels.testResourceString () throws IOException
Exceptions
IOException throws on io errors
Definition at line 175 of file TestCLanguageLabels.java.
References com.github.aptd.simulation.TestCLanguageLabels.CJavaVistor.labels(), com.github.aptd.simulation.common.CCommon.PACKAGEROOT, and com.github.aptd.simulation.TestCLanguageLabels.CJavaVistor.visit().
testTranslation()
void com.github.aptd.simulation.TestCLanguageLabels.testTranslation ()
Definition at line 131 of file TestCLanguageLabels.java.
References com.github.aptd.simulation.common.CCommon.configuration().
Member Data Documentation
CLASSSEPARATOR
final String com.github.aptd.simulation.TestCLanguageLabels.CLASSSEPARATOR = "." static private
Definition at line 69 of file TestCLanguageLabels.java.
LANGUAGEPROPERY
final Map<String, URI> com.github.aptd.simulation.TestCLanguageLabels.LANGUAGEPROPERY = new HashMap<>() static private
Definition at line 77 of file TestCLanguageLabels.java.
SEARCHPATH
final URI com.github.aptd.simulation.TestCLanguageLabels.SEARCHPATH static private
Definition at line 73 of file TestCLanguageLabels.java.