Asimov - Agentbased Passenger & Train Delay Simulation: com.github.aptd.simulation.elements.IBaseElement< N extends IElement<?> Class Template Reference
com.github.aptd.simulation.elements.IBaseElement< N extends IElement<?> Class Template Reference abstract
base simulation element structure
Classes
class CTimeBeliefbase
on-demand beliefbase to get access to the time structure
class IBaseGenerator
base agent generator
Public Member Functions
N call () throws Exception
final IElement< N > environment (final IEnvironment< N, ?> p_environment)
final boolean equals (final Object p_object)
final int hashCode ()
final String id ()
boolean imminent ()
whether the element has a scheduled activation at the current time
N input (final IMessage p_message)
store an incoming message to be processed
final Stream< ILiteral > literal (final IElement<?>... p_object)
final Stream< ILiteral > literal (final Stream< IElement<?>> p_object)
Instant nextactivation ()
Stream< IMessage > output ()
get outgoing messages.
String toString ()
Public Member Functions inherited from com.github.aptd.simulation.elements.IElement< N >
IElement< T > environment (final IEnvironment< T, ?> p_environment)
changes the environment of the agent
String id ()
name of the object
boolean imminent ()
T input (IMessage p_message)
Instant nextactivation ()
Stream< IMessage > output ()
get pending output messages
Protected Member Functions
IBaseElement (final IAgentConfiguration< N > p_configuration, final String p_functor, final String p_id, final ITime p_time)
ctor
abstract Stream< ILiteral > individualliteral (final Stream< IElement<?>> p_object)
define object literal addons
Protected Attributes
final String m_id
agent name
final ListMultimap< EMessageType, IMessage > m_input = Multimaps.synchronizedListMultimap(ArrayListMultimap.create())
set of inputs to be processed
Instant m_nextactivation = Instant.MAX
simulated time at which the agent will become active again on its own
final ITime m_time
reference to time
Private Member Functions
ZonedDateTime currentTime ()
ZonedDateTime getNextActivation ()
ZonedDateTime maxTime ()
void setNextActivation (@Nullable final ZonedDateTime p_datetime) throws Exception
Private Attributes
final AtomicReference< IEnvironment< N, ?> > m_environment = new AtomicReference<>()
reference of the environment
final IView m_external
reference to external beliefbase
final String m_functor
functor definition
ZoneId m_timezone = ZoneId.systemDefault()
timezone the agent lives in
Static Private Attributes
static final long serialVersionUID = 2131082093359879516L
serial id
Detailed Description
Definition at line 83 of file IBaseElement.java.
Constructor & Destructor Documentation
IBaseElement()
com.github.aptd.simulation.elements.IBaseElement< N extends IElement<?>.IBaseElement (final IAgentConfiguration< N > p_configuration, final String p_functor, final String p_id, final ITime p_time) protected
Parameters
p_configuration agent configuration
p_functor ...
p_id ...
p_time time reference
Definition at line 132 of file IBaseElement.java.
Member Function Documentation
call()
N com.github.aptd.simulation.elements.IBaseElement< N extends IElement<?>.call () throws Exception
Definition at line 144 of file IBaseElement.java.
currentTime()
ZonedDateTime com.github.aptd.simulation.elements.IBaseElement< N extends IElement<?>.currentTime () private
Definition at line 262 of file IBaseElement.java.
environment()
final IElement<N> com.github.aptd.simulation.elements.IBaseElement< N extends IElement<?>.environment (final IEnvironment< N, ?> p_environment)
Definition at line 175 of file IBaseElement.java.
equals()
final boolean com.github.aptd.simulation.elements.IBaseElement< N extends IElement<?>.equals (final Object p_object)
Definition at line 188 of file IBaseElement.java.
getNextActivation()
ZonedDateTime com.github.aptd.simulation.elements.IBaseElement< N extends IElement<?>.getNextActivation () private
Definition at line 276 of file IBaseElement.java.
hashCode()
final int com.github.aptd.simulation.elements.IBaseElement< N extends IElement<?>.hashCode ()
Definition at line 182 of file IBaseElement.java.
Referenced by com.github.aptd.simulation.elements.IBaseElement< IDispatcher<?> >.equals().
id()
final String com.github.aptd.simulation.elements.IBaseElement< N extends IElement<?>.id ()
Definition at line 169 of file IBaseElement.java.
imminent()
boolean com.github.aptd.simulation.elements.IBaseElement< N extends IElement<?>.imminent ()
Returns
true if this component has a scheduled activation at the current time
Definition at line 156 of file IBaseElement.java.
Referenced by com.github.aptd.simulation.elements.IBaseElement< IDispatcher<?> >.call().
individualliteral()
abstract Stream<ILiteral> com.github.aptd.simulation.elements.IBaseElement< N extends IElement<?>.individualliteral (final Stream< IElement<?>> p_object) abstract protected
Parameters
p_object calling objects
Returns
literal stream
Referenced by com.github.aptd.simulation.elements.IBaseElement< IDispatcher<?> >.literal(), and com.github.aptd.simulation.elements.IBaseElement< IDispatcher<?> >.toString().
input()
N com.github.aptd.simulation.elements.IBaseElement< N extends IElement<?>.input (final IMessage p_message)
Parameters
p_message incoming message
Returns
self reference
Definition at line 251 of file IBaseElement.java.
literal() [1/2]
final Stream<ILiteral> com.github.aptd.simulation.elements.IBaseElement< N extends IElement<?>.literal (final IElement<?>... p_object)
Definition at line 194 of file IBaseElement.java.
Referenced by com.github.aptd.simulation.elements.IBaseElement< IDispatcher<?> >.literal().
literal() [2/2]
final Stream<ILiteral> com.github.aptd.simulation.elements.IBaseElement< N extends IElement<?>.literal (final Stream< IElement<?>> p_object)
Definition at line 200 of file IBaseElement.java.
maxTime()
ZonedDateTime com.github.aptd.simulation.elements.IBaseElement< N extends IElement<?>.maxTime () private
Definition at line 269 of file IBaseElement.java.
nextactivation()
Instant com.github.aptd.simulation.elements.IBaseElement< N extends IElement<?>.nextactivation ()
Definition at line 162 of file IBaseElement.java.
output()
Stream<IMessage> com.github.aptd.simulation.elements.IBaseElement< N extends IElement<?>.output ()
empty by default
Returns
Stream of messages
Definition at line 238 of file IBaseElement.java.
setNextActivation()
void com.github.aptd.simulation.elements.IBaseElement< N extends IElement<?>.setNextActivation (@Nullable final ZonedDateTime p_datetime) throws Exception private
Definition at line 283 of file IBaseElement.java.
toString()
String com.github.aptd.simulation.elements.IBaseElement< N extends IElement<?>.toString ()
Definition at line 219 of file IBaseElement.java.
Referenced by com.github.aptd.simulation.elements.dispatcher.CDispatcher.CGenerator.generate(), com.github.aptd.simulation.elements.graph.network.local.CVirtual.CGenerator.generate(), com.github.aptd.simulation.elements.graph.network.local.CTransit.CGenerator.generate(), com.github.aptd.simulation.elements.graph.network.local.CStation.CGenerator.generate(), com.github.aptd.simulation.elements.graph.network.local.CTrack.CGenerator.generate(), and com.github.aptd.simulation.elements.train.CWagon.CGenerator.generate().
Member Data Documentation
m_environment
final AtomicReference<IEnvironment<N, ?> > com.github.aptd.simulation.elements.IBaseElement< N extends IElement<?>.m_environment = new AtomicReference<>() private
Definition at line 120 of file IBaseElement.java.
m_external
final IView com.github.aptd.simulation.elements.IBaseElement< N extends IElement<?>.m_external private
Definition at line 112 of file IBaseElement.java.
m_functor
final String com.github.aptd.simulation.elements.IBaseElement< N extends IElement<?>.m_functor private
Definition at line 108 of file IBaseElement.java.
m_id
final String com.github.aptd.simulation.elements.IBaseElement< N extends IElement<?>.m_id protected
Definition at line 92 of file IBaseElement.java.
Referenced by com.github.aptd.simulation.elements.IBaseElement< IDispatcher<?> >.id(), and com.github.aptd.simulation.elements.IBaseElement< IDispatcher<?> >.toString().
m_input
final ListMultimap<EMessageType, IMessage> com.github.aptd.simulation.elements.IBaseElement< N extends IElement<?>.m_input = Multimaps.synchronizedListMultimap(ArrayListMultimap.create()) protected
Definition at line 104 of file IBaseElement.java.
m_nextactivation
Instant com.github.aptd.simulation.elements.IBaseElement< N extends IElement<?>.m_nextactivation = Instant.MAX protected
Definition at line 100 of file IBaseElement.java.
Referenced by com.github.aptd.simulation.elements.IBaseElement< IDispatcher<?> >.getNextActivation(), com.github.aptd.simulation.elements.IBaseElement< IDispatcher<?> >.nextactivation(), and com.github.aptd.simulation.elements.IBaseElement< IDispatcher<?> >.setNextActivation().
m_time
final ITime com.github.aptd.simulation.elements.IBaseElement< N extends IElement<?>.m_time protected
Definition at line 96 of file IBaseElement.java.
Referenced by com.github.aptd.simulation.elements.graph.network.local.CVirtual.CGenerator.generate(), com.github.aptd.simulation.elements.graph.network.local.CTransit.CGenerator.generate(), com.github.aptd.simulation.elements.graph.network.local.CTrack.CGenerator.generate(), com.github.aptd.simulation.elements.train.CWagon.CGenerator.generate(), and com.github.aptd.simulation.elements.IBaseElement< IDispatcher<?> >.setNextActivation().
m_timezone
ZoneId com.github.aptd.simulation.elements.IBaseElement< N extends IElement<?>.m_timezone = ZoneId.systemDefault() private
Definition at line 116 of file IBaseElement.java.
Referenced by com.github.aptd.simulation.elements.IBaseElement< IDispatcher<?> >.getNextActivation(), and com.github.aptd.simulation.elements.IBaseElement< IDispatcher<?> >.maxTime().
serialVersionUID
final long com.github.aptd.simulation.elements.IBaseElement< N extends IElement<?>.serialVersionUID = 2131082093359879516L static private
Definition at line 88 of file IBaseElement.java.