Asimov - Agentbased Passenger & Train Delay Simulation: com.github.aptd.simulation.elements.train.CWagon Class Reference
com.github.aptd.simulation.elements.train.CWagon Class Reference
wagon class
Classes
class CGenerator
generator
Public Member Functions
IWagon< IWagon<?> > add (final IPassenger<?> p_passenger)
final IWagon< IWagon<?> > announcement (final ITrigger p_trigger)
int free ()
final Stream< IPassenger<?> > passenger ()
IWagon< IWagon<?> > remove (final IPassenger<?> p_passenger)
int size ()
Public Member Functions inherited from com.github.aptd.simulation.elements.IBaseElement< N extends IElement<?>
N call () throws Exception
final IElement< N > environment (final IEnvironment< N, ?> p_environment)
final boolean equals (final Object p_object)
final int hashCode ()
final String id ()
boolean imminent ()
whether the element has a scheduled activation at the current time
N input (final IMessage p_message)
store an incoming message to be processed
final Stream< ILiteral > literal (final IElement<?>... p_object)
final Stream< ILiteral > literal (final Stream< IElement<?>> p_object)
Instant nextactivation ()
Stream< IMessage > output ()
get outgoing messages.
String toString ()
Public Member Functions inherited from com.github.aptd.simulation.elements.IElement< N >
IElement< T > environment (final IEnvironment< T, ?> p_environment)
changes the environment of the agent
String id ()
name of the object
boolean imminent ()
T input (IMessage p_message)
Instant nextactivation ()
Stream< IMessage > output ()
get pending output messages
Public Member Functions inherited from com.github.aptd.simulation.elements.train.IWagon< IWagon<?> >
IWagon< T > add (final IPassenger<?> p_passenger)
adds a passenger to the wagon
IWagon< T > announcement (final ITrigger p_trigger)
anouncement for all agents within the wagon
int free ()
unused places
Stream< IPassenger<?> > passenger ()
stream over all passenger
IWagon< T > remove (final IPassenger<?> p_passenger)
removes a passenger from the wagon
int size ()
number of free placeses
Protected Member Functions
final Stream< ILiteral > individualliteral (final Stream< IElement<?>> p_object)
Protected Member Functions inherited from com.github.aptd.simulation.elements.IBaseElement< N extends IElement<?>
IBaseElement (final IAgentConfiguration< N > p_configuration, final String p_functor, final String p_id, final ITime p_time)
ctor
abstract Stream< ILiteral > individualliteral (final Stream< IElement<?>> p_object)
define object literal addons
Private Member Functions
CWagon (final IAgentConfiguration< IWagon<?>> p_configuration, final String p_id, final int p_maximum, final ITime p_time)
ctor
Private Attributes
final int m_maximum
maximum passanger
Set< IPassenger<?> > m_passanger = Sets.newConcurrentHashSet()
set with agents
Static Private Attributes
static final String FUNCTOR = "wagon"
literal functor
static final long serialVersionUID = -8430529331424623057L
serial id
Additional Inherited Members
Protected Attributes inherited from com.github.aptd.simulation.elements.IBaseElement< N extends IElement<?>
final String m_id
agent name
final ListMultimap< EMessageType, IMessage > m_input = Multimaps.synchronizedListMultimap(ArrayListMultimap.create())
set of inputs to be processed
Instant m_nextactivation = Instant.MAX
simulated time at which the agent will become active again on its own
final ITime m_time
reference to time
Detailed Description
Definition at line 47 of file CWagon.java.
Constructor & Destructor Documentation
CWagon()
com.github.aptd.simulation.elements.train.CWagon.CWagon (final IAgentConfiguration< IWagon<?>> p_configuration, final String p_id, final int p_maximum, final ITime p_time) private
Parameters
p_configuration agent configuration
p_id identifier of the wagon
p_maximum maximum number of passengers
p_time time reference
Definition at line 76 of file CWagon.java.
Referenced by com.github.aptd.simulation.elements.train.CWagon.CGenerator.generate().
Member Function Documentation
add()
IWagon<IWagon<?> > com.github.aptd.simulation.elements.train.CWagon.add (final IPassenger<?> p_passenger)
Definition at line 90 of file CWagon.java.
References com.github.aptd.simulation.elements.train.IWagon< T extends IWagon<?>.add().
announcement()
final IWagon<IWagon<?> > com.github.aptd.simulation.elements.train.CWagon.announcement (final ITrigger p_trigger)
Definition at line 83 of file CWagon.java.
free()
int com.github.aptd.simulation.elements.train.CWagon.free ()
Definition at line 104 of file CWagon.java.
individualliteral()
final Stream<ILiteral> com.github.aptd.simulation.elements.train.CWagon.individualliteral (final Stream< IElement<?>> p_object) protected
Definition at line 122 of file CWagon.java.
passenger()
final Stream<IPassenger<?> > com.github.aptd.simulation.elements.train.CWagon.passenger ()
Definition at line 116 of file CWagon.java.
remove()
IWagon<IWagon<?> > com.github.aptd.simulation.elements.train.CWagon.remove (final IPassenger<?> p_passenger)
Definition at line 97 of file CWagon.java.
References com.github.aptd.simulation.elements.train.IWagon< T extends IWagon<?>.remove().
size()
int com.github.aptd.simulation.elements.train.CWagon.size ()
Definition at line 110 of file CWagon.java.
Member Data Documentation
FUNCTOR
final String com.github.aptd.simulation.elements.train.CWagon.FUNCTOR = "wagon" static private
Definition at line 56 of file CWagon.java.
m_maximum
final int com.github.aptd.simulation.elements.train.CWagon.m_maximum private
Definition at line 65 of file CWagon.java.
m_passanger
Set<IPassenger<?> > com.github.aptd.simulation.elements.train.CWagon.m_passanger = Sets.newConcurrentHashSet() private
Definition at line 61 of file CWagon.java.
serialVersionUID
final long com.github.aptd.simulation.elements.train.CWagon.serialVersionUID = -8430529331424623057L static private
Definition at line 52 of file CWagon.java.