Asimov - Agentbased Passenger & Train Delay Simulation: com.github.aptd.simulation.core.units.CUnit Class Reference
com.github.aptd.simulation.core.units.CUnit Class Reference
unit class
Public Member Functions
CUnit (final Number p_cellsize, final Number p_timestep)
ctor
final Number accelerationtospeed (final Number p_acceleration)
returns the speed change in one timestep
final Number cellsize ()
returns the cell size
final Number celltokilometer (final Number p_cells)
returns cell number to distance in kilometer
final Number celltometer (final Number p_cells)
returns cell number to distance in meter
final Number speedofdistance (final Number p_distance)
returns the speed for traveling the given distance in one timestep
final Number speedtocell (final Number p_speed)
returns the speed in cell positions at one timestep
final Number speedtodistance (final Number p_speed)
returns the distance in meter which can moved in one timestep
final Number time ()
returns the timestep in seconds
final Number time (final Number p_step)
returns the time in seconds for n steps
final Number timeinminutes (final Number p_step)
returns the time in minutes for n steps
Private Attributes
final double m_cellsize
cell size in meter
final double m_celltimestep
number of cells which can be moved at one timestep
final double m_timestep
timestep in seconds
Static Private Attributes
static final double KMHINMS = 1000.0 / 3600.0
constant value to scale km/h in m/s
static final double MSINKMH = 1 / KMHINMS
constant value to scale m/s in km/h
Detailed Description
Definition at line 28 of file core/units/CUnit.java.
Constructor & Destructor Documentation
CUnit()
com.github.aptd.simulation.core.units.CUnit.CUnit (final Number p_cellsize, final Number p_timestep)
Parameters
p_cellsize cell size
p_timestep timestep size
Definition at line 58 of file core/units/CUnit.java.
References com.github.aptd.simulation.core.units.CUnit.m_cellsize.
Member Function Documentation
accelerationtospeed()
final Number com.github.aptd.simulation.core.units.CUnit.accelerationtospeed (final Number p_acceleration)
Parameters
p_acceleration acceleration or deceleration in m/sec^2
Returns
speed change in km/h
Definition at line 72 of file core/units/CUnit.java.
References com.github.aptd.simulation.core.units.CUnit.m_timestep.
cellsize()
final Number com.github.aptd.simulation.core.units.CUnit.cellsize ()
Returns
cell size in meter
Definition at line 82 of file core/units/CUnit.java.
References com.github.aptd.simulation.core.units.CUnit.m_cellsize.
celltokilometer()
final Number com.github.aptd.simulation.core.units.CUnit.celltokilometer (final Number p_cells)
Parameters
p_cells cell number
Returns
kilometer value
Definition at line 104 of file core/units/CUnit.java.
References com.github.aptd.simulation.core.units.CUnit.celltometer().
celltometer()
final Number com.github.aptd.simulation.core.units.CUnit.celltometer (final Number p_cells)
Parameters
p_cells cell number
Returns
meter value
Definition at line 93 of file core/units/CUnit.java.
References com.github.aptd.simulation.core.units.CUnit.m_cellsize.
Referenced by com.github.aptd.simulation.core.units.CUnit.celltokilometer().
speedofdistance()
final Number com.github.aptd.simulation.core.units.CUnit.speedofdistance (final Number p_distance)
Parameters
p_distance distance in meter
Returns
speed in km/h
Definition at line 115 of file core/units/CUnit.java.
References com.github.aptd.simulation.core.units.CUnit.MSINKMH.
speedtocell()
final Number com.github.aptd.simulation.core.units.CUnit.speedtocell (final Number p_speed)
Parameters
p_speed speed in km/h
Returns
amount of cells / timestep
Definition at line 126 of file core/units/CUnit.java.
References com.github.aptd.simulation.core.units.CUnit.m_celltimestep.
speedtodistance()
final Number com.github.aptd.simulation.core.units.CUnit.speedtodistance (final Number p_speed)
Parameters
p_speed speed in km/h
Returns
meter
Definition at line 138 of file core/units/CUnit.java.
References com.github.aptd.simulation.core.units.CUnit.m_timestep.
time() [1/2]
final Number com.github.aptd.simulation.core.units.CUnit.time ()
Returns
timestep
Definition at line 148 of file core/units/CUnit.java.
References com.github.aptd.simulation.core.units.CUnit.m_timestep.
Referenced by com.github.aptd.simulation.core.units.CUnit.timeinminutes().
time() [2/2]
final Number com.github.aptd.simulation.core.units.CUnit.time (final Number p_step)
Parameters
p_step step number
Returns
time in seconds
Definition at line 159 of file core/units/CUnit.java.
References com.github.aptd.simulation.core.units.CUnit.m_timestep.
timeinminutes()
final Number com.github.aptd.simulation.core.units.CUnit.timeinminutes (final Number p_step)
Parameters
p_step step number
Returns
time in minutes
Definition at line 170 of file core/units/CUnit.java.
References com.github.aptd.simulation.core.units.CUnit.time().
Member Data Documentation
KMHINMS
final double com.github.aptd.simulation.core.units.CUnit.KMHINMS = 1000.0 / 3600.0 static private
Definition at line 33 of file core/units/CUnit.java.
m_cellsize
final double com.github.aptd.simulation.core.units.CUnit.m_cellsize private
Definition at line 41 of file core/units/CUnit.java.
Referenced by com.github.aptd.simulation.core.units.CUnit.cellsize(), com.github.aptd.simulation.core.units.CUnit.celltometer(), and com.github.aptd.simulation.core.units.CUnit.CUnit().
m_celltimestep
final double com.github.aptd.simulation.core.units.CUnit.m_celltimestep private
Definition at line 49 of file core/units/CUnit.java.
Referenced by com.github.aptd.simulation.core.units.CUnit.speedtocell().
m_timestep
final double com.github.aptd.simulation.core.units.CUnit.m_timestep private
Definition at line 45 of file core/units/CUnit.java.
Referenced by com.github.aptd.simulation.core.units.CUnit.accelerationtospeed(), com.github.aptd.simulation.core.units.CUnit.speedtodistance(), and com.github.aptd.simulation.core.units.CUnit.time().
MSINKMH
final double com.github.aptd.simulation.core.units.CUnit.MSINKMH = 1 / KMHINMS static private
Definition at line 37 of file core/units/CUnit.java.
Referenced by com.github.aptd.simulation.core.units.CUnit.speedofdistance().