Asimov - Agentbased Passenger & Train Delay Simulation: com.github.aptd.simulation.core.statistic.local.CStatistic Class Reference
com.github.aptd.simulation.core.statistic.local.CStatistic Class Reference
statistic collector
Classes
class CStatisticAction
agent action for statistic access
Public Member Functions
final Stream< IAction > action ()
agent action of statistic
final IStatistic write (@Nonnull final IWriter p_writer)
export statistic data
Static Private Member Functions
static void apply (final IWriter p_writer, final String p_name, final DescriptiveStatistics p_statistic)
write data
Private Attributes
final Map< String, DescriptiveStatistics > m_data = new ConcurrentHashMap<>()
map with statistic objects
Additional Inherited Members
Public Attributes inherited from com.github.aptd.simulation.core.statistic.IStatistic
IStatistic EMPTY
Detailed Description
Note
inner classes defines agent-agents, so data-structures must be thread-safe
Bug:
incomplete
Definition at line 56 of file CStatistic.java.
Member Function Documentation
action()
final Stream<IAction> com.github.aptd.simulation.core.statistic.local.CStatistic.action ()
Returns
action stream
Implements com.github.aptd.simulation.core.statistic.IStatistic.
Definition at line 75 of file CStatistic.java.
apply()
static void com.github.aptd.simulation.core.statistic.local.CStatistic.apply (final IWriter p_writer, final String p_name, final DescriptiveStatistics p_statistic) static private
Parameters
p_writer writer instance
p_name section name
p_statistic statistic value
Definition at line 87 of file CStatistic.java.
References com.github.aptd.simulation.core.writer.IWriter.section(), and com.github.aptd.simulation.core.writer.IWriter.value().
Referenced by com.github.aptd.simulation.core.statistic.local.CStatistic.write().
write()
final IStatistic com.github.aptd.simulation.core.statistic.local.CStatistic.write (@Nonnull final IWriter p_writer)
Parameters
p_writer writer instance
Returns
self-reference
Implements com.github.aptd.simulation.core.statistic.IStatistic.
Definition at line 66 of file CStatistic.java.
References com.github.aptd.simulation.core.statistic.local.CStatistic.apply().
Member Data Documentation
m_data
final Map<String, DescriptiveStatistics> com.github.aptd.simulation.core.statistic.local.CStatistic.m_data = new ConcurrentHashMap<>() private
Definition at line 61 of file CStatistic.java.