Asimov - Agentbased Passenger & Train Delay Simulation: com.github.aptd.simulation.core.time.IBaseTime Class Reference
com.github.aptd.simulation.core.time.IBaseTime Class Reference abstract
Base implementation of time mechanism with member variable and literal representation.
Public Member Functions
boolean active ()
indicates whether the experiment is not over yet
void addagent (final IElement<?> p_element)
add an agent
ITime call () throws Exception
final Instant current ()
get the current time
final Stream< ILiteral > literal (final IElement<?>... p_object)
get literal of the current time
Stream< ILiteral > literal (final Stream< IElement<?>> p_object)
get literal of the current time
final< N extends ITime > N raw ()
cast to time instance
void removeagent (final IElement<?> p_element)
remove an agent
Protected Member Functions
IBaseTime (final Instant p_currenttime, final long p_steplimit, final ZoneId p_zone)
ctor
Protected Attributes
final AtomicReference< Instant > m_currenttime
current time
final AtomicLong m_stepcount = new AtomicLong(0)
step counter
final long m_steplimit
step limit
Private Attributes
final ZoneId m_zone
time zone
Detailed Description
Definition at line 43 of file IBaseTime.java.
Constructor & Destructor Documentation
IBaseTime()
com.github.aptd.simulation.core.time.IBaseTime.IBaseTime (final Instant p_currenttime, final long p_steplimit, final ZoneId p_zone) protected
Parameters
p_currenttime current time
p_zone time zone
Definition at line 68 of file IBaseTime.java.
Member Function Documentation
active()
boolean com.github.aptd.simulation.core.time.IBaseTime.active ()
Returns
true if the experiment is not over yet, false if it is
Implements com.github.aptd.simulation.core.time.ITime.
Definition at line 141 of file IBaseTime.java.
References com.github.aptd.simulation.core.time.IBaseTime.m_stepcount, and com.github.aptd.simulation.core.time.IBaseTime.m_steplimit.
addagent()
void com.github.aptd.simulation.core.time.IBaseTime.addagent (final IElement<?> p_element)
Parameters
p_element the new agent
Implements com.github.aptd.simulation.core.time.ITime.
Definition at line 130 of file IBaseTime.java.
call()
ITime com.github.aptd.simulation.core.time.IBaseTime.call () throws Exception
Definition at line 123 of file IBaseTime.java.
References com.github.aptd.simulation.core.time.IBaseTime.m_stepcount.
current()
final Instant com.github.aptd.simulation.core.time.IBaseTime.current ()
Returns
current time
Implements com.github.aptd.simulation.core.time.ITime.
Definition at line 76 of file IBaseTime.java.
literal() [1/2]
final Stream<ILiteral> com.github.aptd.simulation.core.time.IBaseTime.literal (final IElement<?>... p_object)
Parameters
p_object objects
Returns
stream of literal representation of current time
Implements com.github.aptd.simulation.elements.IPerceiveable.
Definition at line 95 of file IBaseTime.java.
literal() [2/2]
Stream<ILiteral> com.github.aptd.simulation.core.time.IBaseTime.literal (final Stream< IElement<?>> p_object)
Parameters
p_object objects
Returns
stream of literal representation of current time
Implements com.github.aptd.simulation.elements.IPerceiveable.
Definition at line 107 of file IBaseTime.java.
References com.github.aptd.simulation.core.time.IBaseTime.m_currenttime, and com.github.aptd.simulation.core.time.IBaseTime.m_zone.
raw()
final<N extends ITime> N com.github.aptd.simulation.core.time.IBaseTime.raw ()
Template Parameters
N time type
Returns
casted time object
Implements com.github.aptd.simulation.core.time.ITime.
Definition at line 83 of file IBaseTime.java.
removeagent()
void com.github.aptd.simulation.core.time.IBaseTime.removeagent (final IElement<?> p_element)
Parameters
p_element the removed agent
Implements com.github.aptd.simulation.core.time.ITime.
Definition at line 135 of file IBaseTime.java.
Member Data Documentation
m_currenttime
final AtomicReference<Instant> com.github.aptd.simulation.core.time.IBaseTime.m_currenttime protected
Definition at line 48 of file IBaseTime.java.
Referenced by com.github.aptd.simulation.core.time.local.CStepTime.call(), com.github.aptd.simulation.core.time.local.CJumpTime.call(), and com.github.aptd.simulation.core.time.IBaseTime.literal().
m_stepcount
final AtomicLong com.github.aptd.simulation.core.time.IBaseTime.m_stepcount = new AtomicLong(0) protected
Definition at line 52 of file IBaseTime.java.
Referenced by com.github.aptd.simulation.core.time.IBaseTime.active(), com.github.aptd.simulation.core.time.local.CJumpTime.call(), and com.github.aptd.simulation.core.time.IBaseTime.call().
m_steplimit
final long com.github.aptd.simulation.core.time.IBaseTime.m_steplimit protected
Definition at line 56 of file IBaseTime.java.
Referenced by com.github.aptd.simulation.core.time.IBaseTime.active().
m_zone
final ZoneId com.github.aptd.simulation.core.time.IBaseTime.m_zone private
Definition at line 60 of file IBaseTime.java.
Referenced by com.github.aptd.simulation.core.time.IBaseTime.literal().