Asimov - Agentbased Passenger & Train Delay Simulation: com.github.aptd.simulation.elements.graph.network.local.CPlatform Class Reference
com.github.aptd.simulation.elements.graph.network.local.CPlatform Class Reference
platform class
Classes
class CGenerator
generator
Public Member Functions
String stationid ()
returns the ID of the station this platform belongs to
Public Member Functions inherited from com.github.aptd.simulation.elements.IStatefulElement< N extends IElement<?>
final Instant nextstatechange ()
synchronized Stream< IMessage > output ()
Public Member Functions inherited from com.github.aptd.simulation.elements.IBaseElement< N >
N call () throws Exception
final IElement< N > environment (final IEnvironment< N, ?> p_environment)
final boolean equals (final Object p_object)
final int hashCode ()
final String id ()
boolean imminent ()
whether the element has a scheduled activation at the current time
N input (final IMessage p_message)
store an incoming message to be processed
final Stream< ILiteral > literal (final IElement<?>... p_object)
final Stream< ILiteral > literal (final Stream< IElement<?>> p_object)
Instant nextactivation ()
Stream< IMessage > output ()
get outgoing messages.
String toString ()
Public Member Functions inherited from com.github.aptd.simulation.elements.IElement< T extends IAgent<?>
IElement< T > environment (final IEnvironment< T, ?> p_environment)
changes the environment of the agent
String id ()
name of the object
boolean imminent ()
T input (IMessage p_message)
Instant nextactivation ()
Stream< IMessage > output ()
get pending output messages
Public Member Functions inherited from com.github.aptd.simulation.elements.IPerceiveable
Stream< ILiteral > literal (final IElement<?>... p_object)
get literal of the object
Stream< ILiteral > literal (final Stream< IElement<?>> p_object)
get literal of the object
Protected Member Functions
Instant determinenextstatechange ()
Stream< ILiteral > individualliteral (final Stream< IElement<?>> p_object)
boolean updatecontinuous (final Duration p_elapsed)
boolean updatestate ()
void writeState (final JsonGenerator p_generator) throws IOException
Protected Member Functions inherited from com.github.aptd.simulation.elements.IStatefulElement< N extends IElement<?>
IStatefulElement (final IAgentConfiguration< N > p_configuration, final String p_functor, final String p_id, final ITime p_time)
ctor
final synchronized void continuousupdate ()
abstract Instant determinenextstatechange ()
calculates the time instant at which the next (internal) state change happens unless the agent is interrupted by input.
final void flushOutput ()
final void output (final IMessage p_message)
final synchronized void transition ()
abstract boolean updatecontinuous (final Duration p_elapsed)
apart from updatestate(), this is the only place where continuous state shall be changed; discrete state must not be changed here
abstract boolean updatestate ()
this is the ONLY place where the discrete state shall be touched.
abstract void writeState (final JsonGenerator p_generator) throws IOException
every implementing class must provide this method that serializes the current state of the object into the provided JsonGenerator (fasterxml-core)
Protected Member Functions inherited from com.github.aptd.simulation.elements.IBaseElement< N >
IBaseElement (final IAgentConfiguration< N > p_configuration, final String p_functor, final String p_id, final ITime p_time)
ctor
abstract Stream< ILiteral > individualliteral (final Stream< IElement<?>> p_object)
define object literal addons
Private Member Functions
CPlatform (final IAgentConfiguration< IPlatform<?>> p_configuration, final String p_id, final String p_stationid, final ITime p_time)
ctor
Private Attributes
final List< IDoor<?> > m_doors = Collections.synchronizedList(new LinkedList<>())
final Set< IPassenger<?> > m_passengers = Collections.synchronizedSet(new HashSet<>())
set of passengers at the platform (subscribers to notifcations of arriving trains)
final String m_stationid
ID of the station this platform belongs to.
ITrain<?> m_train
reference to the train currently standing at the platform
Static Private Attributes
static final String FUNCTOR = "platform"
literal functor
static final long serialVersionUID = -7374587357204465585L
serial id
Additional Inherited Members
Static Public Member Functions inherited from com.github.aptd.simulation.elements.IStatefulElement< N extends IElement<?>
static final String getDefaultAsl (final String p_name)
generates a default asl script string calling "state/transition" upon "!activate", and greeting upon initialisation
Protected Attributes inherited from com.github.aptd.simulation.elements.IStatefulElement< N extends IElement<?>
Instant m_lastcontinuousupdate
Instant m_laststatechange
Instant m_nextstatechange
Protected Attributes inherited from com.github.aptd.simulation.elements.IBaseElement< N >
final String m_id
agent name
final ListMultimap< EMessageType, IMessage > m_input
set of inputs to be processed
Instant m_nextactivation
simulated time at which the agent will become active again on its own
final ITime m_time
reference to time
Detailed Description
Definition at line 59 of file CPlatform.java.
Constructor & Destructor Documentation
CPlatform()
com.github.aptd.simulation.elements.graph.network.local.CPlatform.CPlatform (final IAgentConfiguration< IPlatform<?>> p_configuration, final String p_id, final String p_stationid, final ITime p_time) private
Parameters
p_configuration agent configuration
p_id ...
p_stationid ID of the station
p_time time reference
Definition at line 92 of file CPlatform.java.
Referenced by com.github.aptd.simulation.elements.graph.network.local.CPlatform.CGenerator.generate().
Member Function Documentation
determinenextstatechange()
Instant com.github.aptd.simulation.elements.graph.network.local.CPlatform.determinenextstatechange () protected
Definition at line 104 of file CPlatform.java.
individualliteral()
Stream<ILiteral> com.github.aptd.simulation.elements.graph.network.local.CPlatform.individualliteral (final Stream< IElement<?>> p_object) protected
Definition at line 172 of file CPlatform.java.
stationid()
String com.github.aptd.simulation.elements.graph.network.local.CPlatform.stationid ()
Returns
station ID
Implements com.github.aptd.simulation.elements.graph.network.IPlatform< T extends IPlatform<?>.
Definition at line 179 of file CPlatform.java.
References com.github.aptd.simulation.elements.graph.network.local.CPlatform.m_stationid.
updatecontinuous()
boolean com.github.aptd.simulation.elements.graph.network.local.CPlatform.updatecontinuous (final Duration p_elapsed) protected
Definition at line 153 of file CPlatform.java.
updatestate()
boolean com.github.aptd.simulation.elements.graph.network.local.CPlatform.updatestate () protected
Definition at line 111 of file CPlatform.java.
References com.github.aptd.simulation.core.time.ITime.current(), com.github.aptd.simulation.elements.IElement< T extends IAgent<?>.id(), com.github.aptd.simulation.elements.IBaseElement< N >.m_id, com.github.aptd.simulation.elements.IBaseElement< N >.m_input, com.github.aptd.simulation.elements.IBaseElement< N >.m_time, com.github.aptd.simulation.elements.IStatefulElement< N extends IElement<?>.output(), com.github.aptd.simulation.core.messaging.EMessageType.PASSENGER_TO_PLATFORM_SUBSCRIBE, com.github.aptd.simulation.core.messaging.EMessageType.PASSENGER_TO_PLATFORM_UNSUBSCRIBE, com.github.aptd.simulation.core.messaging.EMessageType.PLATFORM_TO_PASSENGER_TRAINARRIVED, com.github.aptd.simulation.core.messaging.EMessageType.PLATFORM_TO_PASSENGER_TRAINDEPARTED, com.github.aptd.simulation.core.messaging.EMessageType.TRAIN_TO_PLATFORM_ARRIVING, and com.github.aptd.simulation.core.messaging.EMessageType.TRAIN_TO_PLATFORM_DEPARTING.
writeState()
void com.github.aptd.simulation.elements.graph.network.local.CPlatform.writeState (final JsonGenerator p_generator) throws IOException protected
Definition at line 160 of file CPlatform.java.
Member Data Documentation
FUNCTOR
final String com.github.aptd.simulation.elements.graph.network.local.CPlatform.FUNCTOR = "platform" static private
Definition at line 69 of file CPlatform.java.
m_doors
final List<IDoor<?> > com.github.aptd.simulation.elements.graph.network.local.CPlatform.m_doors = Collections.synchronizedList(new LinkedList<>()) private
Definition at line 82 of file CPlatform.java.
m_passengers
final Set<IPassenger<?> > com.github.aptd.simulation.elements.graph.network.local.CPlatform.m_passengers = Collections.synchronizedSet(new HashSet<>()) private
Definition at line 77 of file CPlatform.java.
m_stationid
final String com.github.aptd.simulation.elements.graph.network.local.CPlatform.m_stationid private
Definition at line 73 of file CPlatform.java.
Referenced by com.github.aptd.simulation.elements.graph.network.local.CPlatform.stationid().
m_train
ITrain<?> com.github.aptd.simulation.elements.graph.network.local.CPlatform.m_train private
Definition at line 81 of file CPlatform.java.
serialVersionUID
final long com.github.aptd.simulation.elements.graph.network.local.CPlatform.serialVersionUID = -7374587357204465585L static private
Definition at line 65 of file CPlatform.java.