Asimov - Agentbased Passenger & Train Delay Simulation: com.github.aptd.simulation.core.time.ITime Interface Reference
com.github.aptd.simulation.core.time.ITime Interface Reference
time interface
Public Member Functions
boolean active ()
indicates whether the experiment is not over yet
void addagent (IElement<?> p_element)
add an agent
Instant current ()
get the current time
< N extends ITime > N raw ()
cast to time instance
void removeagent (IElement<?> p_element)
remove an agent
Public Member Functions inherited from com.github.aptd.simulation.elements.IPerceiveable
Stream< ILiteral > literal (final IElement<?>... p_object)
get literal of the object
Stream< ILiteral > literal (final Stream< IElement<?>> p_object)
get literal of the object
Detailed Description
Definition at line 35 of file ITime.java.
Member Function Documentation
active()
boolean com.github.aptd.simulation.core.time.ITime.active ()
Returns
true if the experiment is not over yet, false if it is
Implemented in com.github.aptd.simulation.core.time.IBaseTime, and com.github.aptd.simulation.core.time.local.CJumpTime.
Referenced by com.github.aptd.simulation.core.runtime.local.CRuntime.execute().
addagent()
void com.github.aptd.simulation.core.time.ITime.addagent (IElement<?> p_element)
Parameters
p_element the new agent
Implemented in com.github.aptd.simulation.core.time.IBaseTime, and com.github.aptd.simulation.core.time.local.CJumpTime.
Referenced by com.github.aptd.simulation.core.experiment.local.CExperiment.addAgent().
current()
Instant com.github.aptd.simulation.core.time.ITime.current ()
Returns
current time
Implemented in com.github.aptd.simulation.core.time.IBaseTime.
Referenced by com.github.aptd.simulation.elements.IStatefulElement< IPassenger<?> >.continuousupdate(), com.github.aptd.simulation.elements.train.CTrain.CTrain(), com.github.aptd.simulation.elements.IBaseElement< IDispatcher<?> >.currentTime(), com.github.aptd.simulation.elements.IBaseElement< IDispatcher<?> >.imminent(), com.github.aptd.simulation.elements.IBaseElement< IDispatcher<?> >.input(), com.github.aptd.simulation.elements.IStatefulElement< IPassenger<?> >.IStatefulElement(), com.github.aptd.simulation.elements.IBaseElement< IDispatcher<?> >.setNextActivation(), com.github.aptd.simulation.elements.train.CDoor.timedstatechangeifnecessary(), com.github.aptd.simulation.datamodel.CXMLReader.train(), com.github.aptd.simulation.elements.IStatefulElement< IPassenger<?> >.transition(), com.github.aptd.simulation.elements.train.CDoor.unlockifrequested(), com.github.aptd.simulation.elements.graph.network.local.CPlatform.updatestate(), com.github.aptd.simulation.elements.passenger.CPassengerSource.updatestate(), com.github.aptd.simulation.elements.train.CTrain.updatestate(), and com.github.aptd.simulation.elements.passenger.CPassenger.updatestate().
raw()
<N extends ITime> N com.github.aptd.simulation.core.time.ITime.raw ()
Template Parameters
N time type
Returns
casted time object
Implemented in com.github.aptd.simulation.core.time.IBaseTime.
removeagent()
void com.github.aptd.simulation.core.time.ITime.removeagent (IElement<?> p_element)
Parameters
p_element the removed agent
Implemented in com.github.aptd.simulation.core.time.IBaseTime, and com.github.aptd.simulation.core.time.local.CJumpTime.