Asimov - Agentbased Passenger & Train Delay Simulation: com.github.aptd.simulation.ui.CHTTPServer Class Reference
com.github.aptd.simulation.ui.CHTTPServer Class Reference
Jersey-Jetty-HTTP server for UI.
Static Public Member Functions
static void execute ()
execute the server instance
static< T extends IElement<?> T register (final T p_agent, final String... p_group)
register agent if server is started
static< T extends IElement<?> T register (final Pair< T, Stream< String >> p_agentgroup)
register agent if server started
Private Member Functions
CHTTPServer ()
ctor
Private Attributes
final CApplication m_restagent = new CApplication()
REST-API application.
final Server m_server
server instance
Static Private Attributes
static final CHTTPServer INSTANCE = CConfiguration.INSTANCE.<Boolean>getOrDefault(false, "httpserver", "enable") ? new CHTTPServer() : null
webservcer instance
Detailed Description
debug: -Dorg.eclipse.jetty.servlet.LEVEL=ALL
Definition at line 57 of file CHTTPServer.java.
Constructor & Destructor Documentation
CHTTPServer()
com.github.aptd.simulation.ui.CHTTPServer.CHTTPServer () private
Definition at line 75 of file CHTTPServer.java.
References com.github.aptd.simulation.common.CConfiguration.INSTANCE, and com.github.aptd.simulation.common.CCommon.PACKAGEROOT.
Member Function Documentation
execute()
static void com.github.aptd.simulation.ui.CHTTPServer.execute () static
Definition at line 105 of file CHTTPServer.java.
References com.github.aptd.simulation.common.CConfiguration.INSTANCE, and com.github.aptd.simulation.ui.CHTTPServer.m_server.
Referenced by com.github.aptd.simulation.CMain.execute().
register() [1/2]
static <T extends IElement<?> T com.github.aptd.simulation.ui.CHTTPServer.register (final T p_agent, final String... p_group) static
Parameters
p_agent agent object
p_group additional group
Returns
agent object
Definition at line 145 of file CHTTPServer.java.
References com.github.aptd.simulation.ui.CHTTPServer.m_restagent.
Referenced by com.github.aptd.simulation.elements.IBaseElement< N extends IElement<?>.IBaseGenerator< N extends IElement<?>.generatesingle().
register() [2/2]
static <T extends IElement<?> T com.github.aptd.simulation.ui.CHTTPServer.register (final Pair< T, Stream< String >> p_agentgroup) static
Parameters
p_agentgroup tupel of agent and stream of group names
Returns
agent object
Template Parameters
T agent type
Definition at line 162 of file CHTTPServer.java.
Member Data Documentation
INSTANCE
final CHTTPServer com.github.aptd.simulation.ui.CHTTPServer.INSTANCE = CConfiguration.INSTANCE.<Boolean>getOrDefault(false, "httpserver", "enable") ? new CHTTPServer() : null static private
Definition at line 62 of file CHTTPServer.java.
m_restagent
final CApplication com.github.aptd.simulation.ui.CHTTPServer.m_restagent = new CApplication() private
Definition at line 70 of file CHTTPServer.java.
Referenced by com.github.aptd.simulation.ui.CHTTPServer.register().
m_server
final Server com.github.aptd.simulation.ui.CHTTPServer.m_server private
Definition at line 66 of file CHTTPServer.java.
Referenced by com.github.aptd.simulation.ui.CHTTPServer.execute().